### ISSUE TITLE
TC-DESC-2.2 - Chip tool Darwin not showing the right output for few steps

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#18907] opened 2022-05-27 18:08 UTC
As per the step 1 in TC-DESC-2.2, chip tool Darwin has to show device list but the response is not as expected. Below is the response from the chip tool Darwin output.

[1653674557664] [66433:11674598] CHIP: [EM] Sending Standalone Ack for MessageCounter:6000312 on exchange 15763i
[1653674557664] [66433:11674598] CHIP: [IN] Prepared secure message 0x70000bd83560 to 0x0000000000000001 (1)  of type 0x10 and protocolId (0, 0) on exchange 15763i with MessageCounter:1465411.
[1653674557664] [66433:11674598] CHIP: [IN] Sending encrypted msg 0x70000bd83560 with MessageCounter:1465411 to 0x0000000000000001 (1) at monotonic time: 0000000048723176 msec
2022-05-27 11:02:37.664 chip-tool-darwin[66433:11674599] Descriptor.DeviceList response (
    "<CHIPDescriptorClusterDeviceType: 0x7f858da1daa0>"
)
[1653674557664] [66433:11674598] CHIP: [EM] Flushed pending ack for MessageCounter:6000312 on exchange 15763i
[1653674557664] [66433:11674599] CHIP: [TOO] Shutting down controller

Chip tool output:
[1653674630429] [66455:11675777] CHIP: [DMG] }
[1653674630430] [66455:11675777] CHIP: [TOO] Endpoint: 0 Cluster: 0x0000_001D Attribute 0x0000_0000 DataVersion: 3900821601
[1653674630430] [66455:11675777] CHIP: [TOO]   device list: 1 entries
[1653674630430] [66455:11675777] CHIP: [TOO]     [1]: {
[1653674630430] [66455:11675777] CHIP: [TOO]       Type: 22
[1653674630430] [66455:11675777] CHIP: [TOO]       Revision: 1
[1653674630430] [66455:11675777] CHIP: [TOO]      }
[1653674630431] [66455:11675777] CHIP: [EM] Sending Standalone Ack for MessageCounter:6196449 on exchange 62165i
[1653674630431] [66455:11675777] CHIP: [IN] Prepared secure message 0x7000044c4560 to 0x0000000000000001 (4)  of type 0x10 and protocolId (0, 0) on exchange 62165i with MessageCounter:5197264.
[1653674630431] [66455:11675777] CHIP: [IN] Sending encrypted msg 0x7000044c4560 with MessageCounter:5197264 to 0x0000000000000001 (4) at monotonic time: 0000000048734DB7 msec
[1653674630431] [66455:11675777] CHIP: [EM] Flushed pending ack for MessageCounter:6196449 on exchange 62165i

**Comment by bzbarsky-apple** [comment] 2022-05-28 05:11
Duplicate of https://github.com/project-chip/connectedhomeip/issues/16148

**Closed by bzbarsky-apple** 2022-05-28 05:11 UTC
