### ISSUE TITLE
Add the CHIP Profile ID to the transport message header

### ISSUE THREAD

**Issue by shana-apple** [project-chip/connectedhomeip#1652] opened 2020-07-20 08:34 UTC
We will be introducing something similar to weave profiles so adding the profile id to the message header.

Note from @pan-apple :  The profile ID will eventually be in the encrypted section of the message header. Right now it is being added in the non-encrypted part. That’s ok for time being, as we still need to finalize the message header format and encrypt relevant portions.

Follow up questions:
Should this be called a profile ID/ CHIP Profiles? "Profiles" are also a ZCL concept so should we change it to something different to avoid confusion.

**Comment by gerickson** [comment] 2020-07-20 23:36
/cc/ @yufengwangca

**Comment by yunhanw-google** [comment] 2020-07-22 06:30
Hi, 
We are porting weave exchange manager to CHIP, which route packet to different profile including echo, network provisioning, zcl.
@yufengwangca @gerickson @kghost 
https://github.com/project-chip/connectedhomeip/issues/1670

**Comment by yufengwangca** [comment] 2020-07-23 19:33
This issue seems has been covered by https://github.com/project-chip/connectedhomeip/issues/1692

**Comment by woody-apple** [comment] 2020-07-23 20:09
Agree, duplicate of #1692

**Closed by woody-apple** 2020-07-23 20:09 UTC
Labels: triage
