### ISSUE TITLE
FeatureMap attributes verification throws (UNSUPPORTED_ATTRIBUTE) error for chip-tool and chip-tool-darwin

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#18648] opened 2022-05-20 00:59 UTC
FeatureMap attributes verification throws (UNSUPPORTED_ATTRIBUTE) error for chip-tool and chip-tool-darwin

**Python code:**

./chip-tool-darwin timeformatlocalization read feature-map 1 0

Attaching the logs;

[TC-TFL-1.1-logs.txt](https://github.com/project-chip/connectedhomeip/files/8734982/TC-TFL-1.1-logs.txt)

**Comment by sstruchtrup** [comment] 2022-05-20 06:25
Duplicate of #16725.

**Closed** 2022-05-20 12:55 UTC
