### ISSUE TITLE
Add mDNS for finding device by discriminator in chip device controller

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#4069] opened 2020-12-03 07:27 UTC
#### Problem

We does not support select device by discriminator in chip device controller.

This is used for commissionable discovery. We should be able to get a list of devices with their discriminator / vendorid / product id so they can be used for discovery before service commissioning.

 #### Proposed Solution
Implement it after https://github.com/project-chip/connectedhomeip/pull/4068 is merged.

**Comment by andy31415** [comment] 2021-02-22 17:16
Is this for commisionable discovery?

I would expect controllers needing to search by NodeID and not by discriminators as discriminators may not be unique.
Could you extend the description on why the functionality is needed and what the use would be?

**Comment by erjiaqing** [comment] 2021-02-23 01:58
This is used for commissionable discovery. We should be able to get a list of devices with their discriminator / vendorid / product id so they can be used for discovery before service commissioning.

> Is this for commisionable discovery?
> 
> I would expect controllers needing to search by NodeID and not by discriminators as discriminators may not be unique.
> Could you extend the description on why the functionality is needed and what the use would be?

**Comment by Damian-Nordic** [comment] 2021-04-13 13:50
Is it a duplicate of https://github.com/project-chip/connectedhomeip/issues/5715?

**Closed** 2021-07-21 07:28 UTC
Labels: TE3, V0.7, p1, rendezvous
