### ISSUE TITLE
[BUG] (Android) Commissioning fails - getting "Device not found" error

### ISSUE THREAD

**Issue by abhishekpalaspure20** [project-chip/connectedhomeip#27056] opened 2023-06-03 19:55 UTC
### Reproduction steps

**Reproduction steps:**
I have an ESP32 kit with a lighting app. When I try to commission it using the Android Chiptool sample app, I get a "Device not found" error after entering wifi credentials.  But the same kit I am able to commission using the Google Matter sample app.
1. Select Provision chip device with Wi-Fi
2. scan the Qr code
3. Enter Wifi SSID and password

**Bug prevalence**
Every time I try to commission the device

**Platform**
Android

![Screenshot_2023-06-04-00-33-08-59_a4fdb60577a8ecae165827f629480909](https://github.com/project-chip/connectedhomeip/assets/61469599/6890e44d-1119-4f31-9eeb-ca787e9758fa)

**Logs:**
java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@d6a6004
IllegalArgumentException:java.lang.IllegalArgumentException: Unknown URL content://com.oplus.statistics.provider/track_event
java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@af3ef7d
java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@a34e5c5
java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@8584828
SettingNotFoundException, fall through to G.downloadBytesOverMobileMaximum
SettingNotFoundException, fall through to G.downloadBytesOverMobileRecommended
java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@5ed048d
java.lang.IllegalArgumentException: Receiver not registered: android.view.OplusScrollToTopManager$2@6c56cab
       E  ARP read failure: android.system.ErrnoException: read failed: EAGAIN (Try again)
 E  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference
  java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.Bundle.get(java.lang.String)' on a null object reference

### Bug prevalence

Every time I try to commission the device

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip/commit/de0dfcfbc42fe574774dc440a0e89a8884b28573

### Platform

android, esp32

### Type

Core SDK Crash

**Comment by yunhanw-google** [comment] 2024-01-18 02:10
locally try it, and cannot reproduce it, would close it now. I guess you esp may not be beaconing in ble?  let me know whether it is still problem in your side, feel free to create new ticket with more logging on accessory and controller. thanks

**Closed by yunhanw-google** 2024-01-18 02:10 UTC
Labels: android
