### ISSUE TITLE
[TC-SWDIAG-3.1] The value of CurrentHeapHighWatermark should match with the value of CurrentHeapUsed but failed to do so.

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#14590] opened 2022-01-31 13:51 UTC
#### Problem
**Issue** : In [TC-SWDIAG-3.1] testcase fails because in step 2d the value of CurrentHeapHighWatermark should match with the value of CurrentHeapUsed in step 2c according to test-plan.
But in master branch while running those commands the values are diiferent.

**Expected behaviour** :  The value of CurrentHeapHighWatermark and CurrentHeapUsed should be same.

**Actual behaviour** : The value of CurrentHeapHighWatermark and CurrentHeapUsed are different 

**Steps to reproduce** : ./chip-tool softwarediagnostics read current-heap-high-watermark 1 0
                                  ./chip-tool softwarediagnostics read current-heap-used 1 0

**Test platform** :
               Chip-tool - RPI/MAC
               DUT - RPI

**CommitID used** : fa5561c23d8c1f9464da8669931affbae0660f51		

Test-plan reference : https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/software_diagnostics.adoc#tc-swdiag-3-1-command-received-functionality-with-server-as-dut

[TC_SWDIAG_3_1_manual.txt](https://github.com/project-chip/connectedhomeip/files/7971194/TC_SWDIAG_3_1_manual.txt)

**Comment by tcarmelveilleux** [comment] 2022-01-31 14:43
@sowmyassp Can you please provide the text of the steps you ran, so that we have the correct context?

**Comment by sowmyassp** [comment] 2022-02-02 03:31
@tcarmelveilleux ./chip-tool softwarediagnostics read current-heap-high-watermark 1 0
                             ./chip-tool  softwarediagnostics  read current-heap-used 1 0

**Comment by yufengwangca** [comment] 2022-04-18 23:02
It indicates we have memory leak

**Comment by bzbarsky-apple** [comment] 2022-04-19 15:16
Per Slack discussion, @yufengwangca found that `ReleaseObject` on the heap object pull unconditionally defers the deletion of the node even if we're not in the middle of iteration (i.e. even if `mIterationDepth` is 0).  For pools that never get iterated, or that don't ever do `ReleaseObject` from inside iteration, this ends up leaking the nodes...

**Comment by yufengwangca** [comment] 2022-04-19 19:55
https://github.com/project-chip/connectedhomeip/pull/17516 Fix part of memory leak, I can see the increment became less with this fix, but it shows there is still memory leak in our stack.

**Comment by yufengwangca** [comment] 2022-04-28 00:57
After tracking the memory leak, I found the leak is caused by the UnauthenticatedSession object allocated for each attribute transaction. 

It looks like the UnauthenticatedSession object is only allocated, but not released for later re-use. UnauthenticatedSessionTable is rotated by LRU.

**Comment by yufengwangca** [comment] 2022-04-28 17:42
@sowmyassp  please see my analysis above, current behavior reflects our current design.

**Comment by sowmyassp** [comment] 2022-05-20 09:24
Based on the comment given by jaehs6sam on issue([1238](https://github.com/CHIP-Specifications/chip-test-plans/issues/1238))I have reopened this iissue

**Comment by woody-apple** [comment] 2022-05-23 16:30
Cert Blocker Review: Assigning to @cjandhyala to update the test cases.

**Comment by cjandhyala** [comment] 2022-05-24 05:58
Closing the issue and followed up with a test plan ticket to update the TC

**Closed by cjandhyala** 2022-05-24 05:58 UTC
Labels: p2, V1.0, spec, cert, cert blocker

**Comment by sowmyassp** [comment] 2022-05-24 06:33
I have raised this ticket long back and later the test-plan is updated with test-case IDs so now this issue is for TC-DGSW-2.3, I will update the same in the heading, this ticket is valid @cjandhyala
