### ISSUE TITLE
[TC-RVCOPSTATE-2.4] - The Python script should be updated in accordance with the latest changes in the Test Plan.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#32031] opened 2024-02-09 07:25 UTC
### Feature Area

OperationalState 

### Test Case

[TC-RVCOPSTATE-2.4]

### Reproduction steps

The Python script should be updated in accordance with the latest changes in the Test Plan.

Please refer to the Test Plan PR that has been updated for the relevant test case : https://github.com/CHIP-Specifications/chip-test-plans/pull/3915/files

Python Script : https://github.com/project-chip/connectedhomeip/blob/master/src/python_testing/TC_RVCOPSTATE_2_4.py

**Test-Plan Reference :** 
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/rvcoperationalstate.adoc#tc-rvcopstate-2-4-gohome-command-dut_server

### Bug prevalence

Whenever I do

### GitHub hash of the SDK that was being used

7be9d886ffc50abcbc9fd96abad1cf5c2cab933a

### Platform

raspi

**Comment by plauric** [comment] 2024-02-09 14:09
This looks like a duplicate of https://github.com/project-chip/connectedhomeip/issues/31829

If you agree, please close the issue

**Closed** 2024-02-09 16:27 UTC
Labels: bug, cert blocker, needs triage
