### ISSUE TITLE
Pump Configuration and Control Cluster - optional attributes in Pump Information Attributes not implemented in SDK

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#9902] opened 2021-09-22 23:12 UTC
Spec Snapshot : 
<img width="1214" alt="Screen Shot 2021-09-22 at 4 09 04 PM" src="https://user-images.githubusercontent.com/84206864/134433818-73de5cbc-06f6-4519-bc73-cd10c3e646bd.png">

All the optional attributes indicated in the table above ( ID: 3 - 12 ) are not implemented in SDK . Only the mandatory ones have been implemented by SDK so far.

**Comment by vivien-apple** [comment] 2021-11-16 16:05
That looks like a duplicate of https://github.com/project-chip/connectedhomeip/issues/9809

**Closed by vivien-apple** 2021-11-16 16:05 UTC
