### ISSUE TITLE
[CERT-TEST-FAILURE] - TC-SMCO-2.5 - Test failed

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#27746] opened 2023-07-07 07:53 UTC
### Feature Area

Area:SmokeCO2

### Test Case

TC-SMCO-2.5

### **Summary**

All-clusters-app has to be enabled with below mentioned Attributes :

- [ ]  expressed-state
- [ ]  smoke-state
- [ ]  costate
- [ ]  battery-alert
- [ ]  device-muted
- [ ]  test-in-progress
- [ ]  hardware-fault-alert
- [ ]  end-of-service-alert
- [ ]  interconnect-smoke-alarm
- [ ]  interconnect-coalarm
- [ ]  contamination-state
- [ ]  sensitivity-level
- [ ]  expiry-date

All-clusters-app has to be enabled with below mentioned commands : 

- [ ] SelfTestRequest command

All-clusters-app has to be enabled with below mentioned events :

- [ ]  smoke-alarm
- [ ]  coalarm
- [ ]  low-battery
- [ ]  hardware-fault
- [ ]  end-of-service
- [ ]  self-test-complete
- [ ]  alarm-muted
- [ ]  mute-ended
- [ ]  interconnect-smoke-alarm
- [ ]  interconnect-coalarm
- [ ]  all-clear

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

d55f68526864b2986404d1da9c2ccd8b64735b6e - master

### Platform

raspi

### Platform Version(s)

RPI4 8GB RAM

**Comment by bzbarsky-apple** [comment] 2023-07-07 08:18
Duplicate of https://github.com/project-chip/connectedhomeip/issues/27742

**Closed** 2023-08-22 10:47 UTC
Labels: bug, examples, cert blocker, yaml, needs triage, smoke & c02
