### ISSUE TITLE
TC-IDM-6.3, 6.4 Chip tool Darwin testing: Need support for read-event-by-id and subscribe-event-by-id in wildcard

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#18693] opened 2022-05-20 20:18 UTC
As part of steps in TC-IDM-6.3 and TC-IDM-6.4, need support in chip tool Darwin for read-event-by-id and subscribe-event-by-id. These attributes are present in chip tool but is not present in chip tool Darwin.

<img width="704" alt="Screen Shot 2022-05-20 at 1 16 41 PM" src="https://user-images.githubusercontent.com/34750871/169604379-ff39c400-d55d-478e-a21b-069211f9f52e.png">

**Comment by Garik098** [comment] 2022-05-20 20:44
As per the comments of Josh and Boris in ticket https://github.com/project-chip/connectedhomeip/issues/18185, read events won't be supported

**Comment by bzbarsky-apple** [comment] 2022-05-21 06:21
Duplicate of https://github.com/project-chip/connectedhomeip/issues/18185

**Closed by bzbarsky-apple** 2022-05-21 06:21 UTC
