### ISSUE TITLE
TC-DM-1.2, 1.4 chip tool Darwin testing: read_event and read_event_by_id attributes are not present in Darwin tool

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#16544] opened 2022-03-23 00:41 UTC
As per the steps in TC-DM-1.2 and 1.4, read_event and read_event_by_id attributes are needed in chip tool Darwin. They are present in chip tool but not in the Darwin tool. In the below screenshot, the above list is chip-tool while the below one is the Darwin tool.
<img width="669" alt="Screen Shot 2022-03-22 at 5 41 51 PM" src="https://user-images.githubusercontent.com/34750871/159599548-3397f324-43f0-49f4-9f74-8e979048ed63.png">

**Comment by bzbarsky-apple** [comment] 2022-05-21 06:20
Duplicate of #18185 (which has a bit more info).

**Closed by bzbarsky-apple** 2022-05-21 06:20 UTC
