### ISSUE TITLE
TE9 chip tool testing: Event List global attributes were not present in timeformatlocalization and unit localization

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#17871] opened 2022-04-28 22:34 UTC
As per the mandatory Global Attributes list, Event List should be present to read. While trying to read it with Chip-tool, the Event List attribute is not present in the list of available attributes to read.
![Screen Shot 2022-04-28 at 3 32 56 PM](https://user-images.githubusercontent.com/34750871/165858581-46bf96a7-1d86-4b63-9a02-39c21e8476fb.png)
![Screen Shot 2022-04-28 at 3 34 44 PM](https://user-images.githubusercontent.com/34750871/165858768-7f2bc94c-d6ad-46dc-a840-9d8523b57f8b.png)

**Comment by bzbarsky-apple** [comment] 2022-05-21 05:10
Duplicate of #15011

**Closed by bzbarsky-apple** 2022-05-21 05:10 UTC
