### ISSUE TITLE
TE9 TC_TFL-1.2 Chip-tool read error TimeFormatLocalization cluster

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#18211] opened 2022-05-09 16:40 UTC
#### Problem
<what's wrong or missing, please include any applicable:
 * chip-tool doesn't allow EventList attribute to be read
 >

Below the 
  ./chip-tool timeformatlocalization read attribute-name [param1 param2 ...]

  +-------------------------------------------------------------------------------------+
  | Attributes:                                                                         |
  +-------------------------------------------------------------------------------------+
  | * hour-format                                                                       |
  | * active-calendar-type                                                              |
  | * supported-calendar-types                                                          |
  | * generated-command-list                                                            |
  | * accepted-command-list                                                             |
  | * attribute-list                                                                    |
  | * feature-map                                                                       |
  | * cluster-revision                                                                  |
  +-------------------------------------------------------------------------------------+

**Comment by bzbarsky-apple** [comment] 2022-05-21 05:11
Duplicate of #15011

**Closed by bzbarsky-apple** 2022-05-21 05:11 UTC
