### ISSUE TITLE
Thread provisioning not supported for Nordic dev board using chip device controller run on Raspi running Ubuntu

### ISSUE THREAD

**Issue by SaileeG** [project-chip/connectedhomeip#4400] opened 2021-01-15 22:56 UTC
Flashed the dev board with Lighting sample app for nrf connect. using chip device controller to connect over BLE fails due to Thread provisioning not supported

chip-device-ctrl > connect -ble 12345678
Rendezvous Complete
Connected
chip-device-ctrl > CHIP:BLE: subscribe complete, ep = 0xffff898cde08
CHIP:BLE: peripheral chose BTP version 3; central expected between 2 and 3
CHIP:BLE: using BTP fragment sizes rx 20 / tx 20.
CHIP:BLE: local and remote recv window size = 3
CHIP:BLE: Sent PBKDF param request
CHIP:BLE: Received PBKDF param response
CHIP:BLE: Sent spake2p msg1
CHIP:BLE: Received spake2p msg2
CHIP:BLE: Sent spake2p msg3
CHIP:CTL: Remote device completed SPAKE2+ handshake

CHIP:NP: Sending Network Creds. Delegate 0x125eebb8

**Board Logs:** 
D: 282782811[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
I: 282782818[BLE] local and remote recv window sizes = 3
I: 282782823[BLE] selected BTP version 3
I: 282782827[BLE] using BTP fragment sizes rx 20 / tx 20.
D: 282783006[DL] ConnId: 0x00, New CCCD value: 0x0002
D: 282783010[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 6)
I: 282783018[DL] CHIPoBLE connection established (ConnId: 0x00, GATT MTU: 23)
D: 282783103[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282783445[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282783640[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282783647[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
D: 282783737[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282783932[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282784176[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282784183[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
I: 282784191[BLE] Received rendezvous message from lu
D: 282784196[BLE] Received PBKDF param request
D: 282784415[BLE] Sent PBKDF param response
E: 282784419[DL] Long dispatch time: 243 ms
D: 282784517[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282784525[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282784614[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282784761[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282784769[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282784858[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282784866[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282784955[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282785199[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282785207[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282785297[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282785305[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 19)
D: 282785394[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282785492[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282785736[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282785743[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
D: 282785833[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282786028[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282786223[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282786231[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
D: 282786320[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282786418[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282786662[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282786670[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
D: 282786759[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282786954[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
I: 282786962[BLE] Received rendezvous message from lu
D: 282786967[BLE] Received spake2p msg1
D: 282787125[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282787133[BLE] Sent spake2p msg2
E: 282787136[DL] Long dispatch time: 182 ms
D: 282787198[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282787393[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282787401[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282787490[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282787498[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282787588[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282787783[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282787791[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282787880[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282787888[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282787978[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282788222[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282788229[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 20)
D: 282788319[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282788327[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 13)
D: 282788417[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282788612[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282788807[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282788814[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
D: 282788904[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282789148[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282789343[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282789351[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
D: 282789440[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282789636[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
I: 282789643[BLE] Received rendezvous message from lu
D: 282789648[BLE] Received spake2p msg3
I: 282789653[SVR] Device completed SPAKE2+ handshake
D: 282789879[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282789887[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
D: 282789977[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282790172[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282790367[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282790374[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
D: 282790464[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282790708[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282790903[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282790911[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)
I: 282790919[BLE] Received rendezvous message for lu
I: 282790923[BLE] Received rendezvous message from lu
I: 282790928[NP] Received kWiFiAssociationRequest.

E: 282790933[NP] Failed in HandleNetworkProvisioningMessage. error Error 4045 (0x00000FCD)

E: 282790941[SVR] OnRendezvousStatusUpdate: Error 4045 (0x00000FCD)
I: 282790947[SVR] OnRendezvousError: Error 4045 (0x00000FCD)
E: 282790953[SVR] OnRendezvousStatusUpdate: Error 4045 (0x00000FCD)
I: 282790959[SVR] OnRendezvousError: Error 4045 (0x00000FCD)
D: 282791049[DL] Indication for CHIPoBLE TX characteristic done (ConnId 0x00, result 0x00)
D: 282793730[DL] Write request received for CHIPoBLE RX characteristic (ConnId 0x00)
D: 282796238[DL] Sending indication for CHIPoBLE TX characteristic (ConnId 0, len 3)

Will  #3830 also add support for chip device controller on Linux?

**Comment by woody-apple** [comment] 2021-02-03 00:07
Yup, duplicate of: https://github.com/project-chip/connectedhomeip/issues/4225

**Closed by woody-apple** 2021-02-03 00:07 UTC
