### ISSUE TITLE
Global attribute-Event-List is not implemented in chip-tool. 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#23929] opened 2022-12-06 11:58 UTC
**Problem**
As per Spec (7.13. Global Elements) chip-tool need to be implemented Mandatory global attribute event-list.
Below mentioned cluster needs an EventList attribute implementation
- [ ] Low Power Cluster
- [ ] Keypad Input Cluster
- [ ] Application Launcher Cluster
- [ ] Media Input Cluster
- [ ] Wake on LAN Cluster
- [ ] Channel Cluster
- [ ] Media Playback Cluster
- [ ] Audio Output Cluster
- [ ] Target Navigator Cluster
- [ ] Application Basic Cluster
- [ ] Content Launcher Cluster
- [ ] Account Login Cluster

**Platform Version(s)**
Chip-tool - RPI-4, 8GB RAM
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/25e241ebcbf11b1f63dbe25546b1f10219866ad0
Dut application: tv-app

**PFA Spec screenshot below:-**
![image](https://user-images.githubusercontent.com/95841834/205905124-578fc5f8-360e-4313-8f22-6f48ed005e62.png)

**PFA Chip-tool screenshot below:-**
![image](https://user-images.githubusercontent.com/95841834/205905260-79d55fc0-5516-413d-8db8-a4fd44fa96df.png)

**Comment by bzbarsky-apple** [comment] 2022-12-06 16:20
Duplicate of https://github.com/project-chip/connectedhomeip/issues/15011

**Closed by bzbarsky-apple** 2022-12-06 16:20 UTC
