### ISSUE TITLE
[CERT-TEST-FAILURE] - TC-DISHMS-1.2 - Test failed 

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#27705] opened 2023-07-07 06:54 UTC
Feature Area
Area:ModeSelect

Test Case
TC-DISHMS-1.2

All-clusters-app has to be enabled with below mentioned commands :

- [ ]   supported-modes                                                                   
- [ ]   current-mode                                                                      
- [ ]   start-up-mode                                                                    
- [ ]    on-mode       

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

d55f68526864b2986404d1da9c2ccd8b64735b6e - master

### Platform

raspi

### Platform Version(s)

RPI4 8GB RAM

**Comment by bzbarsky-apple** [comment] 2023-07-07 15:53
Duplicate of https://github.com/project-chip/connectedhomeip/issues/27229

**Comment by cjandhyala** [comment] 2023-07-10 18:47
dup, closing

**Closed by cjandhyala** 2023-07-10 18:47 UTC
Labels: bug, examples, spec, cert blocker, needs triage, mode select
