### ISSUE TITLE
[TC-DD-3.4] Chip-tool Support required for the verifying the DD Test cases

### ISSUE THREAD

**Issue by Saravana-kr22** [project-chip/connectedhomeip#27692] opened 2023-07-07 06:27 UTC
**Issue:**
Chip-tool support is required to verify the below test cases in RPI-platform.

**Test cases required Chip-tool support**

- TC-DD-3.4

 **Area of concern:**

Identification Declaration message ( TC-DD-3.4)

**Platform**:
Raspi

**Platform Verision:**
RPI - 4, 8GB RAM

**Comment by bzbarsky-apple** [comment] 2023-07-07 07:49
This is either a duplicate of #27685 or not actionable due to not actually saying what the issue is: it looks identical to #27685 except for the testcase id.

**Closed by bzbarsky-apple** 2023-07-07 07:49 UTC
