### ISSUE TITLE
TE7.5 [TC-PSCFG-2.1]VerifyOrDie failure at ../../examples/chip-tool/third_party/connectedhomeip/src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0 Aborted (core dumped)

### ISSUE THREAD

**Issue by nanmu2018** [project-chip/connectedhomeip#14494] opened 2022-01-28 10:22 UTC
platform:
Testing image on RasPi：v1.7.img
Connectedhomeip commitID : b0af6ba
OTBR commitID：72bb3d45684f837e67e7f1ec20a9a8e3ac4a4419
lighting-app run on the EFR32MG24 board base on commitID : b0af6ba
[light-log.txt](https://github.com/project-chip/connectedhomeip/files/7957820/light-log.txt)
[otbr-log.txt](https://github.com/project-chip/connectedhomeip/files/7957831/otbr-log.txt)
```
ubuntu@matter-7-5:~/connectedhomeip/out/standalone$ ./chip-tool powersourceconfiguration read sources 12344321 1
[1643365050.716048][3317:3317] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-PqdaOE)
[1643365050.716745][3317:3317] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1643365050.716804][3317:3317] CHIP:DL: NVS set: chip-counters/reboot-count = 2 (0x2)
[1643365050.717740][3317:3317] CHIP:DL: Got Ethernet interface: eth0
[1643365050.718354][3317:3317] CHIP:DL: Found the primary Ethernet interface:eth0
[1643365050.719079][3317:3317] CHIP:DL: Got WiFi interface: wlan0
[1643365050.719156][3317:3317] CHIP:DL: Failed to reset WiFi statistic counts
[1643365050.719226][3317:3317] CHIP:IN: UDP::Init bind&listen port=5542
[1643365050.719338][3317:3317] CHIP:IN: UDP::Init bound to port=5542
[1643365050.719365][3317:3317] CHIP:IN: UDP::Init bind&listen port=5542
[1643365050.719452][3317:3317] CHIP:IN: UDP::Init bound to port=5542
[1643365050.719478][3317:3317] CHIP:IN: TransportMgr initialized
[1643365050.719517][3317:3317] CHIP:DIS: Init fabric pairing table with server storage
[1643365050.719798][3317:3317] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-BVb9OX)
[1643365050.720482][3317:3317] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1643365050.720539][3317:3317] CHIP:DL: NVS set: chip-counters/GlobalMCTR = 2000 (0x7D0)
[1643365050.720664][3317:3317] CHIP:ZCL: Using ZAP configuration...
[1643365050.723948][3317:3317] CHIP:DL: MDNS failed to join multicast group on wlan0 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643365050.731412][3317:3317] CHIP:DL: MDNS failed to join multicast group on vethe317c79 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643365050.733369][3317:3317] CHIP:DL: MDNS failed to join multicast group on veth024b54e for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643365050.735174][3317:3317] CHIP:DL: MDNS failed to join multicast group on vetha392c31 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643365050.737148][3317:3317] CHIP:DL: MDNS failed to join multicast group on wpan0 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643365050.737494][3317:3317] CHIP:CTL: System State Initialized...
[1643365050.740673][3317:3317] CHIP:CTL: Generating NOC
[1643365050.741006][3317:3317] CHIP:CTL: Generating ICAC
[1643365050.741768][3317:3317] CHIP:DIS: Verifying the received credentials
[1643365050.743518][3317:3317] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000001 and root pubkey
[1643365050.743557][3317:3317] CHIP:IN: 0x04, 0x79, 0x28, 0xfa, 0xae, 0x58, 0x9c, 0x2f,
[1643365050.743581][3317:3317] CHIP:IN: 0x77, 0xd7, 0xc2, 0x3d, 0x9e, 0xcd, 0x56, 0x59,
[1643365050.743606][3317:3317] CHIP:IN: 0x5c, 0x49, 0x83, 0xa0, 0xac, 0xd5, 0x9b, 0xb8,
[1643365050.743629][3317:3317] CHIP:IN: 0xaf, 0x54, 0x25, 0xfb, 0x9c, 0x26, 0xe2, 0x0e,
[1643365050.743652][3317:3317] CHIP:IN: 0x48, 0xc3, 0x61, 0xbb, 0x88, 0xab, 0x5f, 0xdf,
[1643365050.743675][3317:3317] CHIP:IN: 0xd7, 0x16, 0x8e, 0x0f, 0xcd, 0x36, 0x31, 0x4c,
[1643365050.743698][3317:3317] CHIP:IN: 0x96, 0x08, 0x0e, 0xe4, 0xd3, 0xf9, 0x13, 0x42,
[1643365050.743721][3317:3317] CHIP:IN: 0xc8, 0xd5, 0x12, 0x7f, 0xbc, 0x64, 0x7b, 0xcb,
[1643365050.743741][3317:3317] CHIP:IN: 0x43,
[1643365050.743795][3317:3317] CHIP:IN: Generated compressed fabric ID
[1643365050.743821][3317:3317] CHIP:IN: 0xf0, 0x53, 0xa5, 0xba, 0x88, 0xd7, 0x23, 0x99,
[1643365050.743850][3317:3317] CHIP:DIS: Added new fabric at index: 1, Initialized: 1
[1643365050.743873][3317:3317] CHIP:DIS: Assigned compressed fabric ID: 0xF053A5BA88D72399, node ID: 0x000000000001B669
[1643365050.743896][3317:3317] CHIP:CTL: Joined the fabric at index 1. Compressed fabric ID is: 0xF053A5BA88D72399
[1643365050.743959][3317:3317] CHIP:IN: UDP::Init bind&listen port=5550
[1643365050.744098][3317:3317] CHIP:IN: UDP::Init bound to port=5550
[1643365050.744141][3317:3317] CHIP:IN: UDP::Init bind&listen port=5550
[1643365050.744231][3317:3317] CHIP:IN: UDP::Init bound to port=5550
[1643365050.744256][3317:3317] CHIP:IN: TransportMgr initialized
[1643365050.745115][3317:3317] CHIP:CTL: Generating NOC
[1643365050.745413][3317:3317] CHIP:CTL: Generating ICAC
[1643365050.746105][3317:3317] CHIP:DIS: Verifying the received credentials
[1643365050.747825][3317:3317] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000002 and root pubkey
[1643365050.747862][3317:3317] CHIP:IN: 0x04, 0x79, 0x28, 0xfa, 0xae, 0x58, 0x9c, 0x2f,
[1643365050.747886][3317:3317] CHIP:IN: 0x77, 0xd7, 0xc2, 0x3d, 0x9e, 0xcd, 0x56, 0x59,
[1643365050.747910][3317:3317] CHIP:IN: 0x5c, 0x49, 0x83, 0xa0, 0xac, 0xd5, 0x9b, 0xb8,
[1643365050.747933][3317:3317] CHIP:IN: 0xaf, 0x54, 0x25, 0xfb, 0x9c, 0x26, 0xe2, 0x0e,
[1643365050.747956][3317:3317] CHIP:IN: 0x48, 0xc3, 0x61, 0xbb, 0x88, 0xab, 0x5f, 0xdf,
[1643365050.747979][3317:3317] CHIP:IN: 0xd7, 0x16, 0x8e, 0x0f, 0xcd, 0x36, 0x31, 0x4c,
[1643365050.748002][3317:3317] CHIP:IN: 0x96, 0x08, 0x0e, 0xe4, 0xd3, 0xf9, 0x13, 0x42,
[1643365050.748025][3317:3317] CHIP:IN: 0xc8, 0xd5, 0x12, 0x7f, 0xbc, 0x64, 0x7b, 0xcb,
[1643365050.748045][3317:3317] CHIP:IN: 0x43,
[1643365050.748097][3317:3317] CHIP:IN: Generated compressed fabric ID
[1643365050.748272][3317:3317] CHIP:IN: 0xb6, 0x66, 0x1d, 0xac, 0xc4, 0x3d, 0xe9, 0x31,
[1643365050.748311][3317:3317] CHIP:DIS: Added new fabric at index: 2, Initialized: 1
[1643365050.748334][3317:3317] CHIP:DIS: Assigned compressed fabric ID: 0xB6661DACC43DE931, node ID: 0x000000000001B669
[1643365050.748357][3317:3317] CHIP:CTL: Joined the fabric at index 2. Compressed fabric ID is: 0xB6661DACC43DE931
[1643365050.748437][3317:3317] CHIP:IN: UDP::Init bind&listen port=5550
[1643365050.748559][3317:3317] CHIP:IN: UDP::Init bound to port=5550
[1643365050.748585][3317:3317] CHIP:IN: UDP::Init bind&listen port=5550
[1643365050.748679][3317:3317] CHIP:IN: UDP::Init bound to port=5550
[1643365050.748704][3317:3317] CHIP:IN: TransportMgr initialized
[1643365050.749682][3317:3317] CHIP:CTL: Generating NOC
[1643365050.750034][3317:3317] CHIP:CTL: Generating ICAC
[1643365050.750844][3317:3317] CHIP:DIS: Verifying the received credentials
[1643365050.752718][3317:3317] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000003 and root pubkey
[1643365050.752764][3317:3317] CHIP:IN: 0x04, 0x79, 0x28, 0xfa, 0xae, 0x58, 0x9c, 0x2f,
[1643365050.752789][3317:3317] CHIP:IN: 0x77, 0xd7, 0xc2, 0x3d, 0x9e, 0xcd, 0x56, 0x59,
[1643365050.752812][3317:3317] CHIP:IN: 0x5c, 0x49, 0x83, 0xa0, 0xac, 0xd5, 0x9b, 0xb8,
[1643365050.752835][3317:3317] CHIP:IN: 0xaf, 0x54, 0x25, 0xfb, 0x9c, 0x26, 0xe2, 0x0e,
[1643365050.752858][3317:3317] CHIP:IN: 0x48, 0xc3, 0x61, 0xbb, 0x88, 0xab, 0x5f, 0xdf,
[1643365050.752881][3317:3317] CHIP:IN: 0xd7, 0x16, 0x8e, 0x0f, 0xcd, 0x36, 0x31, 0x4c,
[1643365050.752903][3317:3317] CHIP:IN: 0x96, 0x08, 0x0e, 0xe4, 0xd3, 0xf9, 0x13, 0x42,
[1643365050.752926][3317:3317] CHIP:IN: 0xc8, 0xd5, 0x12, 0x7f, 0xbc, 0x64, 0x7b, 0xcb,
[1643365050.752946][3317:3317] CHIP:IN: 0x43,
[1643365050.753006][3317:3317] CHIP:IN: Generated compressed fabric ID
[1643365050.753033][3317:3317] CHIP:IN: 0x24, 0x2d, 0xc3, 0x3d, 0x1a, 0x13, 0x5a, 0x15,
[1643365050.753065][3317:3317] CHIP:DIS: Added new fabric at index: 3, Initialized: 1
[1643365050.753088][3317:3317] CHIP:DIS: Assigned compressed fabric ID: 0x242DC33D1A135A15, node ID: 0x000000000001B669
[1643365050.753110][3317:3317] CHIP:CTL: Joined the fabric at index 3. Compressed fabric ID is: 0x242DC33D1A135A15
[1643365050.753207][3317:3317] CHIP:IN: UDP::Init bind&listen port=5550
[1643365050.753337][3317:3317] CHIP:IN: UDP::Init bound to port=5550
[1643365050.753364][3317:3317] CHIP:IN: UDP::Init bind&listen port=5550
[1643365050.753461][3317:3317] CHIP:IN: UDP::Init bound to port=5550
[1643365050.753485][3317:3317] CHIP:IN: TransportMgr initialized
[1643365050.753816][3317:3322] CHIP:DL: CHIP task running
[1643365050.753944][3317:3322] CHIP:TOO: Sending command to node 0xbc5c01
[1643365050.754589][3317:3322] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643365050.755174][3317:3322] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643365050.755329][3317:3322] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643365050.755475][3317:3322] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643365050.756435][3317:3322] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643365050.756493][3317:3322] CHIP:DIS:     Addr 0: [2001:db8::ce6d:a9ec:e77a:696e]:5540
[1643365050.756520][3317:3322] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643365050.757169][3317:3322] CHIP:IN: Generating DestinationID. Fabric ID 0x0000000000000001, Dest node ID 0x0000000000BC5C01, Random data
[1643365050.757221][3317:3322] CHIP:IN: 0xd4, 0x77, 0xb0, 0xc2, 0xdd, 0xa3, 0x99, 0xc8,
[1643365050.757245][3317:3322] CHIP:IN: 0x6f, 0xf5, 0x4e, 0x71, 0x43, 0x1b, 0x6b, 0x89,
[1643365050.757270][3317:3322] CHIP:IN: 0x18, 0x73, 0x6b, 0x69, 0x56, 0x73, 0xbd, 0x48,
[1643365050.757293][3317:3322] CHIP:IN: 0xa4, 0x26, 0xc4, 0xc7, 0x9a, 0xaf, 0xdd, 0x2c,
[1643365050.757315][3317:3322] CHIP:IN: Root pubkey
[1643365050.757336][3317:3322] CHIP:IN: 0x04, 0x79, 0x28, 0xfa, 0xae, 0x58, 0x9c, 0x2f,
[1643365050.757360][3317:3322] CHIP:IN: 0x77, 0xd7, 0xc2, 0x3d, 0x9e, 0xcd, 0x56, 0x59,
[1643365050.757383][3317:3322] CHIP:IN: 0x5c, 0x49, 0x83, 0xa0, 0xac, 0xd5, 0x9b, 0xb8,
[1643365050.757406][3317:3322] CHIP:IN: 0xaf, 0x54, 0x25, 0xfb, 0x9c, 0x26, 0xe2, 0x0e,
[1643365050.757429][3317:3322] CHIP:IN: 0x48, 0xc3, 0x61, 0xbb, 0x88, 0xab, 0x5f, 0xdf,
[1643365050.757452][3317:3322] CHIP:IN: 0xd7, 0x16, 0x8e, 0x0f, 0xcd, 0x36, 0x31, 0x4c,
[1643365050.757476][3317:3322] CHIP:IN: 0x96, 0x08, 0x0e, 0xe4, 0xd3, 0xf9, 0x13, 0x42,
[1643365050.757499][3317:3322] CHIP:IN: 0xc8, 0xd5, 0x12, 0x7f, 0xbc, 0x64, 0x7b, 0xcb,
[1643365050.757519][3317:3322] CHIP:IN: 0x43,
[1643365050.757540][3317:3322] CHIP:IN: IPK
[1643365050.757563][3317:3322] CHIP:IN: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
[1643365050.757587][3317:3322] CHIP:IN: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
[1643365050.757627][3317:3322] CHIP:IN: Generated DestinationID output
[1643365050.757653][3317:3322] CHIP:IN: 0x6d, 0xf7, 0x58, 0x05, 0x78, 0x1c, 0x1e, 0xf1,
[1643365050.757676][3317:3322] CHIP:IN: 0x86, 0xdb, 0xb6, 0x6e, 0xc2, 0xbd, 0xec, 0xca,
[1643365050.757699][3317:3322] CHIP:IN: 0x6c, 0x8b, 0xa6, 0xa1, 0xec, 0x44, 0xe4, 0xfb,
[1643365050.757721][3317:3322] CHIP:IN: 0x56, 0x36, 0xdc, 0x55, 0x57, 0x37, 0x19, 0xdf,
[1643365050.757747][3317:3322] CHIP:SC: Including MRP parameters
[1643365050.757816][3317:3322] CHIP:IN: Prepared plaintext message 0xaaaaeff65810 to 0x0000000000000000 (0)  of type 0x30 and protocolId (0, 0) on exchange 51454i with MessageCounter:4230937856.
[1643365050.757862][3317:3322] CHIP:IN: Sending plaintext msg 0xaaaaeff65810 with MessageCounter:4230937856 to 0x0000000000000000 at monotonic time: 179933 msec
[1643365050.758004][3317:3322] CHIP:SC: Sent Sigma1 msg
[1643365050.758044][3317:3322] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643365050.758372][3317:3322] CHIP:DIS: Discovered node without a pending query
[1643365050.758402][3317:3322] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643365050.758430][3317:3322] CHIP:DIS:     Addr 0: [2001:db8::ce6d:a9ec:e77a:696e]:5540
[1643365050.758452][3317:3322] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643365050.758480][3317:3322] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643365050.758631][3317:3322] CHIP:DIS: Discovered node without a pending query
[1643365050.758656][3317:3322] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643365050.758680][3317:3322] CHIP:DIS:     Addr 0: [2001:db8::ce6d:a9ec:e77a:696e]:5540
[1643365050.758700][3317:3322] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643365050.758725][3317:3322] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643365050.758870][3317:3322] CHIP:DIS: Discovered node without a pending query
[1643365050.758894][3317:3322] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643365050.758917][3317:3322] CHIP:DIS:     Addr 0: [2001:db8::ce6d:a9ec:e77a:696e]:5540
[1643365050.758938][3317:3322] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643365050.758962][3317:3322] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643365050.759107][3317:3322] CHIP:DIS: Discovered node without a pending query
[1643365050.759131][3317:3322] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643365050.759154][3317:3322] CHIP:DIS:     Addr 0: [2001:db8::ce6d:a9ec:e77a:696e]:5540
[1643365050.759174][3317:3322] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643365050.759199][3317:3322] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643365052.760234][3317:3322] CHIP:EM: Received message of type 0x31 with protocolId (0, 0) and MessageCounter:2481834428 on exchange 51454i
[1643365052.760332][3317:3322] CHIP:EM: Found matching exchange: 51454i, Delegate: 0xffff90644348
[1643365052.760424][3317:3322] CHIP:EM: Rxd Ack; Removing MessageCounter:4230937856 from Retrans Table on exchange 51454i
[1643365052.760487][3317:3322] CHIP:EM: Removed CHIP MessageCounter:4230937856 from RetransTable on exchange 51454i
[1643365052.760572][3317:3322] CHIP:SC: Received Sigma2 msg
[1643365052.760653][3317:3322] CHIP:SC: Peer assigned session session ID 3
[1643365052.765930][3317:3322] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000001 and root pubkey
[1643365052.766008][3317:3322] CHIP:IN: 0x04, 0x79, 0x28, 0xfa, 0xae, 0x58, 0x9c, 0x2f,
[1643365052.766054][3317:3322] CHIP:IN: 0x77, 0xd7, 0xc2, 0x3d, 0x9e, 0xcd, 0x56, 0x59,
[1643365052.766098][3317:3322] CHIP:IN: 0x5c, 0x49, 0x83, 0xa0, 0xac, 0xd5, 0x9b, 0xb8,
[1643365052.766143][3317:3322] CHIP:IN: 0xaf, 0x54, 0x25, 0xfb, 0x9c, 0x26, 0xe2, 0x0e,
[1643365052.766188][3317:3322] CHIP:IN: 0x48, 0xc3, 0x61, 0xbb, 0x88, 0xab, 0x5f, 0xdf,
[1643365052.766230][3317:3322] CHIP:IN: 0xd7, 0x16, 0x8e, 0x0f, 0xcd, 0x36, 0x31, 0x4c,
[1643365052.766273][3317:3322] CHIP:IN: 0x96, 0x08, 0x0e, 0xe4, 0xd3, 0xf9, 0x13, 0x42,
[1643365052.766316][3317:3322] CHIP:IN: 0xc8, 0xd5, 0x12, 0x7f, 0xbc, 0x64, 0x7b, 0xcb,
[1643365052.766355][3317:3322] CHIP:IN: 0x43,
[1643365052.766470][3317:3322] CHIP:IN: Generated compressed fabric ID
[1643365052.766521][3317:3322] CHIP:IN: 0xf0, 0x53, 0xa5, 0xba, 0x88, 0xd7, 0x23, 0x99,
[1643365052.768157][3317:3322] CHIP:SC: Found MRP parameters in the message
[1643365052.768225][3317:3322] CHIP:SC: Sending Sigma3
[1643365052.768860][3317:3322] CHIP:EM: Piggybacking Ack for MessageCounter:2481834428 on exchange: 51454i
[1643365052.768938][3317:3322] CHIP:IN: Prepared plaintext message 0xaaaaeff65810 to 0x0000000000000000 (0)  of type 0x32 and protocolId (0, 0) on exchange 51454i with MessageCounter:4230937857.
[1643365052.769008][3317:3322] CHIP:IN: Sending plaintext msg 0xaaaaeff65810 with MessageCounter:4230937857 to 0x0000000000000000 at monotonic time: 181944 msec
[1643365052.769254][3317:3322] CHIP:SC: Sent Sigma3 msg
[1643365053.124929][3317:3322] CHIP:EM: Received message of type 0x40 with protocolId (0, 0) and MessageCounter:2481834429 on exchange 51454i
[1643365053.125021][3317:3322] CHIP:EM: Found matching exchange: 51454i, Delegate: 0xffff90644348
[1643365053.125771][3317:3322] CHIP:EM: Rxd Ack; Removing MessageCounter:4230937857 from Retrans Table on exchange 51454i
[1643365053.125863][3317:3322] CHIP:EM: Removed CHIP MessageCounter:4230937857 from RetransTable on exchange 51454i
[1643365053.125952][3317:3322] CHIP:SC: Success status report received. Session was established
[1643365053.126022][3317:3322] CHIP:IN: New secure session created for device 0x0000000000BC5C01, key 3!!
[1643365053.126263][3317:3322] CHIP:TOO: Sending cluster (0x002E) command (0x00) on endpoint 1
[1643365053.141419][3317:3322] CHIP:DMG: SendReadRequest ReadClient[0xffff78001950]: Sending Read Request
[1643365053.141625][3317:3322] CHIP:IN: Prepared encrypted message 0xaaaaeff65810 to 0x0000000000BC5C01 (1)  of type 0x2 and protocolId (0, 1) on exchange 51455i with MessageCounter:2541147.
[1643365053.141699][3317:3322] CHIP:IN: Sending encrypted msg 0xaaaaeff65810 with MessageCounter:2541147 to 0x0000000000BC5C01 (1) at monotonic time: 182317 msec
[1643365053.141914][3317:3322] CHIP:DMG: MoveToState ReadClient[0xffff78001950]: Moving to [AwaitingIn]
[1643365053.141981][3317:3322] CHIP:CTL: Device connected callback with null pairing delegate. Ignoring
[1643365053.142029][3317:3322] CHIP:EM: Sending Standalone Ack for MessageCounter:2481834429 on exchange 51454i
[1643365053.142084][3317:3322] CHIP:IN: Prepared plaintext message 0xffff8b7ed9c8 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 51454i with MessageCounter:4230937858.
[1643365053.142141][3317:3322] CHIP:IN: Sending plaintext msg 0xffff8b7ed9c8 with MessageCounter:4230937858 to 0x0000000000000000 at monotonic time: 182318 msec
[1643365053.142266][3317:3322] CHIP:EM: Flushed pending ack for MessageCounter:2481834429 on exchange 51454i
[1643365053.269922][3317:3322] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:1031449 on exchange 51455i
[1643365053.270032][3317:3322] CHIP:EM: Found matching exchange: 51455i, Delegate: 0xffff78001950
[1643365053.270129][3317:3322] CHIP:EM: Rxd Ack; Removing MessageCounter:2541147 from Retrans Table on exchange 51455i
[1643365053.270193][3317:3322] CHIP:EM: Removed CHIP MessageCounter:2541147 from RetransTable on exchange 51455i
[1643365053.270312][3317:3322] CHIP:DMG: ReportDataMessage =
[1643365053.270374][3317:3322] CHIP:DMG: {
[1643365053.270435][3317:3322] CHIP:DMG:        AttributeReportIBs =
[1643365053.270520][3317:3322] CHIP:DMG:        [
[1643365053.270585][3317:3322] CHIP:DMG:                AttributeReportIB =
[1643365053.270677][3317:3322] CHIP:DMG:                {
[1643365053.270745][3317:3322] CHIP:DMG:                        AttributeStatusIB =
[1643365053.270839][3317:3322] CHIP:DMG:                        {
[1643365053.270917][3317:3322] CHIP:DMG:                                AttributePathIB =
[1643365053.271014][3317:3322] CHIP:DMG:                                {
[1643365053.271103][3317:3322] CHIP:DMG:                                        Endpoint = 0x1,
[1643365053.271206][3317:3322] CHIP:DMG:                                        Cluster = 0x2e,
[1643365053.271309][3317:3322] CHIP:DMG:                                        Attribute = 0x0000_0000,
[1643365053.271406][3317:3322] CHIP:DMG:                                }
[1643365053.271506][3317:3322] CHIP:DMG:
[1643365053.271603][3317:3322] CHIP:DMG:                                StatusIB =
[1643365053.271695][3317:3322] CHIP:DMG:                                {
[1643365053.271792][3317:3322] CHIP:DMG:                                        status = 0x86,
[1643365053.271895][3317:3322] CHIP:DMG:                                },
[1643365053.271978][3317:3322] CHIP:DMG:
[1643365053.272065][3317:3322] CHIP:DMG:                        },
[1643365053.272234][3317:3322] CHIP:DMG:
[1643365053.272306][3317:3322] CHIP:DMG:                },
[1643365053.272393][3317:3322] CHIP:DMG:
[1643365053.272456][3317:3322] CHIP:DMG:        ],
[1643365053.272539][3317:3322] CHIP:DMG:
[1643365053.272592][3317:3322] CHIP:DMG:        SuppressResponse = true,
[1643365053.272665][3317:3322] CHIP:DMG: }
[1643365053.272976][3317:3322] CHIP:TOO: Default Failure Response: 0x86
[1643365053.273127][3317:3322] CHIP:EM: Sending Standalone Ack for MessageCounter:1031449 on exchange 51455i
[1643365053.273268][3317:3322] CHIP:IN: Prepared encrypted message 0xffff8b7ed9d8 to 0x0000000000BC5C01 (1)  of type 0x10 and protocolId (0, 0) on exchange 51455i with MessageCounter:2541148.
[1643365053.273364][3317:3322] CHIP:IN: Sending encrypted msg 0xffff8b7ed9d8 with MessageCounter:2541148 to 0x0000000000BC5C01 (1) at monotonic time: 182449 msec
[1643365053.273623][3317:3322] CHIP:EM: Flushed pending ack for MessageCounter:1031449 on exchange 51455i
[1643365053.274016][3317:3317] CHIP:-: ../../examples/chip-tool/third_party/connectedhomeip/zzz_generated/chip-tool/zap-generated/cluster/Commands.h:2502: CHIP Error 0x000000AC: Internal error at ../../examples/chip-tool/commands/common/CHIPCommand.cpp:59
[1643365053.274112][3317:3317] CHIP:TOO: Run command failure: ../../examples/chip-tool/third_party/connectedhomeip/zzz_generated/chip-tool/zap-generated/cluster/Commands.h:2502: CHIP Error 0x000000AC: Internal error
[1643365053.279242][3317:3317] CHIP:SPT: VerifyOrDie failure at ../../examples/chip-tool/third_party/connectedhomeip/src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0
Aborted (core dumped)
ubuntu@matter-7-5:~/connectedhomeip/out/standalone$

```

**Comment by andy31415** [comment] 2022-01-31 18:45
Looks like a duplicate of #14472

**Closed by andy31415** 2022-01-31 18:45 UTC
