### ISSUE TITLE
Pre SVE chip tool testing: Few steps in TC-DL-3.2 are giving general error (0x8b) response

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#19652] opened 2022-06-16 01:27 UTC
SHA:5d8599d195a93dfe5473f64e4f888c322e5df1d2

Platform: Chip Tool running on Mac, all cluster app running on nRF52840-DK (Thread setup)

As per the steps in TC-DL-3.2, the below commands are giving general error (0x8b) response

Commands used:

./chip-tool doorlock set-week-day-schedule 3 2 2 8 15 9 15 1 1
./chip-tool doorlock clear-week-day-schedule 1 1 1 1
./chip-tool doorlock set-year-day-schedule 3 3 6 21 1 1
./chip-tool doorlock clear-year-day-schedule 1 1 1 1
./chip-tool doorlock set-holiday-schedule 1 20 30 0 1 1
./chip-tool doorlock get-holiday-schedule 1 1 1
./chip-tool doorlock clear-holiday-schedule 1 1 1

[1655342103958] [30412:5015406] CHIP: [DMG] ICR moving to [ResponseRe]
[1655342103958] [30412:5015406] CHIP: [DMG] InvokeResponseMessage =
[1655342103958] [30412:5015406] CHIP: [DMG] {
[1655342103958] [30412:5015406] CHIP: [DMG] 	suppressResponse = false, 
[1655342103958] [30412:5015406] CHIP: [DMG] 	InvokeResponseIBs =
[1655342103958] [30412:5015406] CHIP: [DMG] 	[
[1655342103958] [30412:5015406] CHIP: [DMG] 		InvokeResponseIB =
[1655342103958] [30412:5015406] CHIP: [DMG] 		{
[1655342103958] [30412:5015406] CHIP: [DMG] 			CommandStatusIB =
[1655342103958] [30412:5015406] CHIP: [DMG] 			{
[1655342103958] [30412:5015406] CHIP: [DMG] 				CommandPathIB =
[1655342103958] [30412:5015406] CHIP: [DMG] 				{
[1655342103958] [30412:5015406] CHIP: [DMG] 					EndpointId = 0x1,
[1655342103958] [30412:5015406] CHIP: [DMG] 					ClusterId = 0x101,
[1655342103958] [30412:5015406] CHIP: [DMG] 					CommandId = 0xe,
[1655342103958] [30412:5015406] CHIP: [DMG] 				},
[1655342103958] [30412:5015406] CHIP: [DMG] 				
[1655342103958] [30412:5015406] CHIP: [DMG] 				StatusIB =
[1655342103958] [30412:5015406] CHIP: [DMG] 				{
[1655342103958] [30412:5015406] CHIP: [DMG] 					status = 0x8b (NOT_FOUND),
[1655342103958] [30412:5015406] CHIP: [DMG] 				},
[1655342103958] [30412:5015406] CHIP: [DMG] 				
[1655342103958] [30412:5015406] CHIP: [DMG] 			},
[1655342103958] [30412:5015406] CHIP: [DMG] 			
[1655342103958] [30412:5015406] CHIP: [DMG] 		},
[1655342103958] [30412:5015406] CHIP: [DMG] 		
[1655342103958] [30412:5015406] CHIP: [DMG] 	],
[1655342103958] [30412:5015406] CHIP: [DMG] 	
[1655342103958] [30412:5015406] CHIP: [DMG] 	InteractionModelRevision = 1
[1655342103958] [30412:5015406] CHIP: [DMG] },
[1655342103958] [30412:5015406] CHIP: [DMG] Received Command Response Status for Endpoint=1 Cluster=0x0000_0101 Command=0x0000_000E Status=0x8b
[1655342103959] [30412:5015406] CHIP: [TOO] Error: IM Error 0x0000058B: General error: 0x8b (NOT_FOUND)
[1655342103959] [30412:5015406] CHIP: [DMG] ICR moving to [AwaitingDe]
[1655342103959] [30412:5015406] CHIP: [EM] Sending Standalone Ack for MessageCounter:22946566 on exchange 26679i
[1655342103959] [30412:5015406] CHIP: [IN] Prepared secure message 0x70000c9cc4f0 to 0x0000000000000001 (1)  of type 0x10 and protocolId (0, 0) on exchange 26679i with MessageCounter:220735223.
[1655342103959] [30412:5015406] CHIP: [IN] Sending encrypted msg 0x70000c9cc4f0 with MessageCounter:220735223 to 0x0000000000000001 (1) at monotonic time: 000000001A37CC26 msec
[1655342103959] [30412:5015406] CHIP: [EM] Flushed pending ack for MessageCounter:22946566 on exchange 26679i
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the commissioner
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the controller
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the commissioner
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the controller
[1655342103959] [30412:5015401] CHIP: [IN] Expiring all connections for fabric 1!!
[1655342103959] [30412:5015401] CHIP: [IN] SecureSession[0x7ff1e1c2bc80]: MarkForRemoval Type:2 LSID:36706
[1655342103959] [30412:5015401] CHIP: [IN] SecureSession[0x7ff1e1c2bc80]: Released - Type:2 LSID:36706
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the commissioner
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the controller
[1655342103959] [30412:5015401] CHIP: [IN] Expiring all connections for fabric 2!!
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the commissioner
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the controller
[1655342103959] [30412:5015401] CHIP: [IN] Expiring all connections for fabric 3!!
[1655342103959] [30412:5015401] CHIP: [CTL] Shutting down the System State, this will teardown the CHIP Stack
[1655342103959] [30412:5015401] CHIP: [DMG] IM WH moving to [Uninitialized]
[1655342103959] [30412:5015401] CHIP: [DMG] IM WH moving to [Uninitialized]
[1655342103959] [30412:5015401] CHIP: [DMG] IM WH moving to [Uninitialized]
[1655342103959] [30412:5015401] CHIP: [DMG] IM WH moving to [Uninitialized]
[1655342103959] [30412:5015401] CHIP: [DMG] All ReadHandler-s are clean, clear GlobalDirtySet
[1655342103959] [30412:5015401] CHIP: [BLE] CancelConnection
[1655342103959] [30412:5015401] CHIP: [DL] Inet Layer shutdown
[1655342103959] [30412:5015401] CHIP: [DL] BLE shutdown
[1655342103959] [30412:5015401] CHIP: [DL] System Layer shutdown
[1655342103960] [30412:5015401] CHIP: [TOO] Run command failure: IM Error 0x0000058B: General error: 0x8b (NOT_FOUND)

**Comment by bzbarsky-apple** [comment] 2022-06-16 05:12
Duplicate of #19622

**Closed by bzbarsky-apple** 2022-06-16 05:12 UTC
