### ISSUE TITLE
Darwin Build Failure

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#32841] opened 2024-04-03 22:23 UTC
https://github.com/project-chip/connectedhomeip/actions/runs/8539323034

**Comment by bzbarsky-apple** [comment] 2024-04-05 19:26
This is failing in TestDiagnosticLogsDownloadCommand.

Duplicate of https://github.com/project-chip/connectedhomeip/issues/32636

**Closed by bzbarsky-apple** 2024-04-05 19:26 UTC
Labels: build issue, darwin
