### ISSUE TITLE
[TC-OO-2.3] Commands Failing OffWithEffect , OnWithRecallGlobalScene and OnWithTimedOff

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#11526] opened 2021-11-08 13:37 UTC
Summary : 
             As per test plane the commands  OffWithEffect , OnWithRecallGlobalScene and OnWithTimedOff are to be send from the TH and should return a successful status, however when we try to use these commands in the YAML test scripts they seem to always fail, please refer attached screenshots and logs

Test plan Screenshot:
![image](https://user-images.githubusercontent.com/84442963/140100722-719c4baa-b87d-4dbd-8624-8d13b725608e.png)
![image](https://user-images.githubusercontent.com/84442963/140101155-51dbb457-0e9a-4083-8d27-a2afc77f5004.png)
![image](https://user-images.githubusercontent.com/84442963/140101393-4d4ab265-3830-41fe-8be9-253764de6f57.png)

Spec Screenshot :
![image](https://user-images.githubusercontent.com/84442963/140101688-39a50ab2-50f6-4ffb-8655-9f3e15d08b7b.png)
![image](https://user-images.githubusercontent.com/84442963/140101942-8156b539-e693-48bd-a36f-ad7fc6141fb5.png)
![image](https://user-images.githubusercontent.com/84442963/140102227-2a8974e9-2b25-430d-8c5e-14ca44e6738b.png)

Log file and YAML execution Screenshot :
[oo_2_3.txt](https://github.com/CHIP-Specifications/chip-test-plans/files/7469080/oo_2_3.txt)
![OO_2_3](https://user-images.githubusercontent.com/84442963/140099717-6d396486-2bbf-4d84-bc34-a2611b7b8089.png)

**Comment by raju-apple** [comment] 2022-02-23 17:11
P3

**Comment by woody-apple** [comment] 2022-03-03 17:33
We expect this is an issue in the DUT app, removing SDK requirements for test harness

**Comment by bzbarsky-apple** [comment] 2022-05-04 20:09
@raju-apple @manjunath-grl What are the actual steps to reproduce here?

**Comment by manjunath-grl** [comment] 2022-05-11 09:50
This issue was created by me using a account that i had to delete due to access issues, I will continue to follow these issues with my current id.

**Comment by manjunath-grl** [comment] 2022-05-11 09:50
All 3 commands are working fine

**Comment by bzbarsky-apple** [comment] 2022-05-11 19:58
@manjunath-grl so issue can be closed?

**Comment by naveenkommareddi** [comment] 2022-05-17 01:43
Yes. lets close this issue

**Comment by franck-apple** [comment] 2022-05-17 09:44
Can be closed. Issue is resolved

**Closed by franck-apple** 2022-05-17 09:44 UTC
Labels: V1.0, spec, app-clusters, cert, sdk requirements from test harness
