### ISSUE TITLE
TE9 TC-DESC-1-1 Chip-tool is missing EventList for Descriptor cluster

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#18218] opened 2022-05-09 18:03 UTC
#### Problem
<what's wrong or missing, please include any applicable:
CHIP-TOOL No global EventList attribute to be read on the descriptor cluster
 >

  ./chip-tool descriptor read attribute-name [param1 param2 ...]

  +-------------------------------------------------------------------------------------+
  | Attributes:                                                                         |
  +-------------------------------------------------------------------------------------+
  | * device-list                                                                       |
  | * server-list                                                                       |
  | * client-list                                                                       |
  | * parts-list                                                                        |
  | * generated-command-list                                                            |
  | * accepted-command-list                                                             |
  | * attribute-list                                                                    |
  | * feature-map                                                                       |
  | * cluster-revision                                                                  |
  +-------------------------------------------------------------------------------------+

**Comment by bzbarsky-apple** [comment] 2022-05-21 05:12
Duplicate of https://github.com/project-chip/connectedhomeip/issues/15011

**Closed by bzbarsky-apple** 2022-05-21 05:12 UTC
