### ISSUE TITLE
TC-SWTCH-1.1 - Feature map should support either LS or MS flag as per spec.

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#19263] opened 2022-06-07 08:24 UTC
**Problem:**
As per spec the implementation of the feature is mandatory for LS or MS . But feature map value shows as "0" while executing.

**Actual outcome:**
./chip-tool switch read feature-map 1 1
[1646208136.242043][2390:2395] CHIP:TOO:   FeatureMap: 0

**App used** - all clusters app
**platform** - Raspi
spec screenshot for ref:
![TC-SWTCH-1 1](https://user-images.githubusercontent.com/93810525/172332869-7cab1e4c-a21b-45fd-9425-0f0aaa40a220.png)

spec link:
https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/app_clusters/Switch.adoc#features

**Comment by bzbarsky-apple** [comment] 2022-06-07 12:47
Duplicate of #19228

**Closed by bzbarsky-apple** 2022-06-07 12:47 UTC
