### ISSUE TITLE
 [TC-DISHMS-2.3] SDK has to be implemented for Dishwasher Mode Select Cluster

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#27790] opened 2023-07-07 09:50 UTC
All-clusters-app has to be enabled with below mentioned attributes :

- [ ] SupportedModes attribute
- [ ] CurrentMode attribute

All-clusters-app has to be enabled with below mentioned commands :
- [ ] ChangeToModeWithStatus command 

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

d55f68526864b2986404d1da9c2ccd8b64735b6e - master

### Platform

raspi

### Platform Version(s)

RPI4 8GB RAM

**Comment by bzbarsky-apple** [comment] 2023-07-07 15:52
There is no ChangeToModeWithStatus in this cluster (see spec) and the rest us a duplicate of https://github.com/project-chip/connectedhomeip/issues/27229

**Closed by bzbarsky-apple** 2023-07-07 15:52 UTC
Labels: bug, examples, spec, request cert blocker, needs triage, dishwashers
