### ISSUE TITLE
[TC-DIAGLOG-1.1] Global attribute-Cluster-Revision and FeatureMap returns status code as 0x86 Error(unsupported attribute) Response.

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#17275] opened 2022-04-12 11:04 UTC
#### Problem
Though the "Cluster-revision and feature map" attribute is implemented in below mentioned clusters it throws an error code as 0x86(unsupported attribute).
 
For Cluster-revision:-
  expected behavior:-ClusterRevision attribute has the value 1
  actual behavior:-0x86(unsupported attribute)
* steps to reproduce:- sudo ./chip-tool diagnosticlogs read cluster-revision 1 0

For feature-map
    expected behavior:-FeatureMap bitmap value
    actual behavior:-0x86(unsupported attribute)
* steps to reproduce:- ./chip-tool diagnosticlogs read feature-map 1 0

PFA log below
[TC-DIAGLOG-1.1.txt](https://github.com/project-chip/connectedhomeip/files/8472270/TC-DIAGLOG-1.1.txt)

**Comment by bzbarsky-apple** [comment] 2022-05-09 15:52
Duplicate of https://github.com/project-chip/connectedhomeip/issues/16725

**Closed by bzbarsky-apple** 2022-05-09 15:52 UTC
Labels: V1.0, cert
