### ISSUE TITLE
Unable build the Android app in the Mac OS[1.3] 

### ISSUE THREAD

**Issue by uiabhishek15** [project-chip/connectedhomeip#34386] opened 2024-07-18 05:54 UTC
### Reproduction steps

Can anyone give the steps to build the Android app in the MAC OS

### Bug prevalence

daily

### GitHub hash of the SDK that was being used

https://github.com/project-chip/connectedhomeip.git

### Platform

android

### Type

Platform Issue

**Comment by joonhaengHeo** [comment] 2024-07-29 06:12
@uiabhishek15 
I successfully built the build using the Build Script in the guide below. Is there anything that doesn't work?
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/android_building.md#building-android-chiptool-from-scripts

**Comment by yunhanw-google** [comment] 2024-10-08 04:43
it works in my side as well. closing this one, feel free to reopen if the issue is still outstanding.

**Closed by yunhanw-google** 2024-10-08 04:43 UTC
Labels: bug, android, needs triage
