### ISSUE TITLE
all-clusters-app/linux crashing on receiving "remove-fabric" command

### ISSUE THREAD

**Issue by shubhamdp** [project-chip/connectedhomeip#17680] opened 2022-04-25 08:10 UTC
#### Problem
* head commit: 077e44eadf46f349916b3f4f358da6126be2ed48
* Platfrom: Darwin

Build and commission the all-clusters-app/linux and then send remove-fabric command, app crashes here: https://github.com/project-chip/connectedhomeip/blob/077e44eadf46f349916b3f4f358da6126be2ed48/src/transport/SessionManager.cpp#L209

I am not sure if is it expected because we are removing the last fabric here, but it even crashes if app has multiple fabrics.

Also, wandering if this the right way to decommission the device?

```
./out/debug/chip-all-clusters-app
./out/debug/chip-tool pairing onnetwork-long 11 20202021 3840
./out/debug/chip-tool operationalcredentials remove-fabric 1 11 0
```

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by Damian-Nordic** [comment] 2022-04-25 10:58
Duplicate of https://github.com/project-chip/connectedhomeip/issues/16748

**Closed** 2022-04-26 04:12 UTC
