### ISSUE TITLE
G_SOURCE_FUNC error when running chef.py

### ISSUE THREAD

**Issue by tugceakkirisken** [project-chip/connectedhomeip#26791] opened 2023-05-24 10:20 UTC
### Reproduction steps

1. We installed Docker on Ubuntu 18.04
 2. We downloaded Docker image
 3. We run Docker
 4. https://developers.home.google.com/codelabs/matter-device-virtual#1 we completed the steps here
 5. We created a project in Google Home Developer Console
 6. We upgraded python 3.8, we upgraded gcc and g++ 9
 7. When we run ./chef.py -zbr -d rootnode_dimmablelight_bCwGYSDpoe -t linux we get G_SOURCE_FUNC error , how can we solve this?
 8. We tried Include <glib.h>, define the callback as a GSourceFunction variable and pass that callback to the function
 

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

non

### Platform

vscode

### Platform Version(s)

b3e4e68a
[log-connectedhomeip.txt](https://github.com/project-chip/connectedhomeip/files/11553511/log-connectedhomeip.txt)

### Anything else?

I downloaded as zip on may 22 and couldnt find "GitHub hash of the SDK that was being used". Also I added log message as txt

**Comment by andy31415** [comment] 2023-05-24 18:12
I don't think ubutu 18 is supported by the chip SDK. https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md asks for 22.04

**Comment by andy31415** [comment] 2023-05-24 18:14
Could you confirm what O/S are you using? You installed docker on 18.04 ... are you running a new ubuntu on there? What is your environment?

Currently chef compiles fine on the chip-build docker image I believe, however from your description I suspect you may be using a different O/S version or glib version.

**Comment by andy31415** [comment] 2023-05-24 19:12
Also since you are following https://developers.home.google.com/codelabs/matter-device-virtual#1 , the Open source SDK is probably not the right place for issues. https://developers.home.google.com/matter/support seems like a better starting point.

**Comment by andy31415** [comment] 2023-05-24 19:12
Closing: this is a non-oss sdk guide following. Not sure what the issue is (may be ubuntu version related, likely glib-version related) however support should be through google home if following google home codelabs.

**Closed by andy31415** 2023-05-24 19:12 UTC

**Comment by tugceakkirisken** [comment] 2023-05-26 07:04
> Could you confirm what O/S are you using? You installed docker on 18.04 ... are you running a new ubuntu on there? What is your environment?
> 
> Currently chef compiles fine on the chip-build docker image I believe, however from your description I suspect you may be using a different O/S version or glib version.
Hi, I'am using ubuntu 18.04. I did all the updates and followed the steps to install docker. Also glib version is GLIBC 2.27
