### ISSUE TITLE
chip-tool-darwin: `generaldiagnostics read network-interfaces` returns improper structure in logs for Network interfaces

### ISSUE THREAD

**Issue by liamgonyea** [project-chip/connectedhomeip#18911] opened 2022-05-27 20:04 UTC
#### Problem
When running Step 2 in `TC-DGGEN-3.1`, the output on `chip-tool-darwin` is not correct for the following command: 
`./out/chip-tool-darwin/chip-tool-darwin generaldiagnostics read network-interfaces 1 0`
when paired to `chip-all-clusters-app`.

`chip-tool-darwin` output looks like this:

> 2022-05-27 12:35:35.821 chip-tool-darwin[53604:2159596] GeneralDiagnostics.NetworkInterfaces response (
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec370>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec190>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec280>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec230>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec2d0>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec1e0>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec4b0>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec5f0>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec640>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec690>",
    "<CHIPGeneralDiagnosticsClusterNetworkInterfaceType: 0x600001eec6e0>"
)

Whereas in `chip-tool`, output looks like this:

> [1653681300190] [53867:2173044] CHIP: [TOO]     [9]: {
[1653681300190] [53867:2173044] CHIP: [TOO]       Name: wlan0
[1653681300190] [53867:2173044] CHIP: [TOO]       IsOperational: TRUE
[1653681300190] [53867:2173044] CHIP: [TOO]       OffPremiseServicesReachableIPv4: null
[1653681300190] [53867:2173044] CHIP: [TOO]       OffPremiseServicesReachableIPv6: null
[1653681300190] [53867:2173044] CHIP: [TOO]       HardwareAddress: DCA6328D2BA0
[1653681300190] [53867:2173044] CHIP: [TOO]       IPv4Addresses: 0 entries
[1653681300190] [53867:2173044] CHIP: [TOO]       IPv6Addresses: 0 entries
[1653681300190] [53867:2173044] CHIP: [TOO]       Type: 1
[1653681300190] [53867:2173044] CHIP: [TOO]      }
[1653681300190] [53867:2173044] CHIP: [TOO]     [10]: {
[1653681300190] [53867:2173044] CHIP: [TOO]       Name: eth0
[1653681300190] [53867:2173044] CHIP: [TOO]       IsOperational: TRUE
[1653681300190] [53867:2173044] CHIP: [TOO]       OffPremiseServicesReachableIPv4: null
[1653681300190] [53867:2173044] CHIP: [TOO]       OffPremiseServicesReachableIPv6: null
[1653681300190] [53867:2173044] CHIP: [TOO]       HardwareAddress: DCA6328D2B9F
[1653681300190] [53867:2173044] CHIP: [TOO]       IPv4Addresses: 0 entries
[1653681300190] [53867:2173044] CHIP: [TOO]       IPv6Addresses: 0 entries
[1653681300190] [53867:2173044] CHIP: [TOO]       Type: 2
[1653681300190] [53867:2173044] CHIP: [TOO]      }
[1653681300190] [53867:2173044] CHIP: [TOO]     [11]: {

#### Test Case
[TC-DGGEN-3.1 - Attributes observation with client as DUT](https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/general_diagnostics.adoc#331-tc-dggen-31-attributes-observation-with-client-as-dut)
 
![image](https://user-images.githubusercontent.com/80923273/170782034-396c92da-f55c-481d-ace3-4695c790d55a.png)

#### Logs
[TC-DGGEN-3.1 Error Logs.txt](https://github.com/project-chip/connectedhomeip/files/8789478/TC-DGGEN-3.1.Error.Logs.txt)

**Comment by bzbarsky-apple** [comment] 2022-05-28 05:11
Duplicate of https://github.com/project-chip/connectedhomeip/issues/16148

**Closed by bzbarsky-apple** 2022-05-28 05:11 UTC
