### ISSUE TITLE
TC-IDM-6.4 chip tool Darwin testing: Subscribe-Events support needed to perform the steps

### ISSUE THREAD

**Issue by Garik098** [project-chip/connectedhomeip#17151] opened 2022-04-06 22:50 UTC
As per step 1 description in TC-IDM-6.4, chip-tool-darwin should have support to do subscribe event.
<img width="1058" alt="Screen Shot 2022-03-23 at 1 03 58 PM" src="https://user-images.githubusercontent.com/34750871/159786074-1e5c91af-af53-48fb-940d-039680a7ee48.png">

Below is the example for basic cluster for chip-tool vs chip-tool-darwin. The subscribe event commands are needed to execute this step. Currently in chip-tool-darwin there is no support for subscribe events in any of the cluster.
<img width="865" alt="Screen Shot 2022-04-06 at 3 49 05 PM" src="https://user-images.githubusercontent.com/34750871/162085349-ce82e363-da4e-4000-b03f-9994e49ec3d7.png">

**Comment by bzbarsky-apple** [comment] 2022-05-28 05:31
Note that you can use `darwin-framework-tool any subscribe-all-events` to subscribe to all events.  The Darwin framework does not currently support individual event subscriptions.

**Comment by bzbarsky-apple** [comment] 2022-05-28 05:31
Duplicate of https://github.com/project-chip/connectedhomeip/issues/18387

**Closed by bzbarsky-apple** 2022-05-28 05:31 UTC
