### ISSUE TITLE
Events: add support for global EventList attribute as per specification

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#18759] opened 2022-05-24 14:42 UTC
#### Problem
The global EventList attribute is not implemented neither on the client, e.g. query with chip-tool, nor on the server.

 #### Proposed Solution
Implement EventList attribute so it can be verified during SVE and certification.

**Comment by bzbarsky-apple** [comment] 2022-05-24 17:39
Duplicate of #15011

**Closed by bzbarsky-apple** 2022-05-24 17:39 UTC
Labels: TE9 feedback, SVE
