### ISSUE TITLE
Fail Installation on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by ashegheparyshun** [project-chip/connectedhomeip#17947] opened 2022-05-02 10:18 UTC
#### Problem
I've tried Matter SDK on Ubuntu 20.04 LTS and Docker with no problem. Now I've switched to Ubuntu 22.04 LTS. I applied the same installation process to build Matter SDK but the installation failed. The first mismatch result to Ubuntu 20.04 LTS is this line:
`sudo apt-get install git gcc g++ python pkg-config libssl-dev libdbus-1-dev \
     libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev \
     python3-pip unzip libgirepository1.0-dev libcairo2-dev`
Which it successes on Ubuntu 20 but fails on Ubuntu 22 the result is 
 
![image](https://user-images.githubusercontent.com/85277214/166215090-dc4c6b58-143b-4741-98a0-3e83813c5c3e.png)
Then I tried 
`sudo apt-get install git gcc g++ python3 pkg-config libssl-dev libdbus-1-dev \
     libglib2.0-dev libavahi-client-dev ninja-build python3-venv python3-dev \
     python3-pip unzip libgirepository1.0-dev libcairo2-dev`
Note that, I changed python to python3 at the first line.
After this change the installation finished successfully. Then I've followed the installation according to [https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md](url) until
`source scripts/activate.sh`
But I got this error
![image](https://user-images.githubusercontent.com/85277214/166218802-493dc80d-9ffc-48ff-b599-1ac0cc493452.png)

I tried python3-is-python
`sudo apt install python-is-python3`
But the same result.
 System information:
OS: Ubuntu 22.04 LTS
CPU: Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
RAM: 8G

**Comment by rosahay-silabs** [comment] 2022-05-03 04:49
Duplicate of https://github.com/project-chip/connectedhomeip/issues/16664

**Comment by mikaelhm** [comment] 2022-07-29 22:52
This can be closed, verified no longer an issue.

**Comment by franck-apple** [comment] 2022-07-29 23:19
Closing per above comment.

**Closed by franck-apple** 2022-07-29 23:19 UTC
