### ISSUE TITLE
TE7.5 [TC-PSCFG-1.1]VerifyOrDie failure at ../../examples/chip-tool/third_party/connectedhomeip/src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0 Aborted (core dumped)

### ISSUE THREAD

**Issue by nanmu2018** [project-chip/connectedhomeip#14493] opened 2022-01-28 10:13 UTC
platform:
Testing image on RasPi：v1.7.img
Connectedhomeip commitID : b0af6ba
OTBR commitID：72bb3d45684f837e67e7f1ec20a9a8e3ac4a4419
lighting-app run on the EFR32MG24 board base on commitID : b0af6ba
[light-log.txt](https://github.com/project-chip/connectedhomeip/files/7957750/light-log.txt)
[otbr-log.txt](https://github.com/project-chip/connectedhomeip/files/7957752/otbr-log.txt)
```
ubuntu@matter-7-5:~/connectedhomeip/out/standalone$ ./chip-tool powersourceconfiguration read cluster-revision 12344321 1
[1643364426.487141][3494:3494] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-y5dcR7)
[1643364426.487810][3494:3494] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1643364426.487868][3494:3494] CHIP:DL: NVS set: chip-counters/reboot-count = 3 (0x3)
[1643364426.488870][3494:3494] CHIP:DL: Got Ethernet interface: eth0
[1643364426.489489][3494:3494] CHIP:DL: Found the primary Ethernet interface:eth0
[1643364426.490107][3494:3494] CHIP:DL: Got WiFi interface: wlan0
[1643364426.490182][3494:3494] CHIP:DL: Failed to reset WiFi statistic counts
[1643364426.490262][3494:3494] CHIP:IN: UDP::Init bind&listen port=5542
[1643364426.490380][3494:3494] CHIP:IN: UDP::Init bound to port=5542
[1643364426.490408][3494:3494] CHIP:IN: UDP::Init bind&listen port=5542
[1643364426.490499][3494:3494] CHIP:IN: UDP::Init bound to port=5542
[1643364426.490524][3494:3494] CHIP:IN: TransportMgr initialized
[1643364426.490564][3494:3494] CHIP:DIS: Init fabric pairing table with server storage
[1643364426.490878][3494:3494] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-q8DoWo)
[1643364426.491464][3494:3494] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1643364426.491520][3494:3494] CHIP:DL: NVS set: chip-counters/GlobalMCTR = 3000 (0xBB8)
[1643364426.491661][3494:3494] CHIP:ZCL: Using ZAP configuration...
[1643364426.495722][3494:3494] CHIP:DL: MDNS failed to join multicast group on wlan0 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643364426.504164][3494:3494] CHIP:DL: MDNS failed to join multicast group on veth7d28b1b for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643364426.505962][3494:3494] CHIP:DL: MDNS failed to join multicast group on veth0af677f for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643364426.507751][3494:3494] CHIP:DL: MDNS failed to join multicast group on veth2e90ded for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643364426.509783][3494:3494] CHIP:DL: MDNS failed to join multicast group on wpan0 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643364426.510120][3494:3494] CHIP:CTL: System State Initialized...
[1643364426.513224][3494:3494] CHIP:CTL: Generating NOC
[1643364426.513550][3494:3494] CHIP:CTL: Generating ICAC
[1643364426.514308][3494:3494] CHIP:DIS: Verifying the received credentials
[1643364426.516089][3494:3494] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000001 and root pubkey
[1643364426.516130][3494:3494] CHIP:IN: 0x04, 0x33, 0x4d, 0xdf, 0x93, 0xde, 0xde, 0x2a,
[1643364426.516155][3494:3494] CHIP:IN: 0x02, 0x27, 0x65, 0xf2, 0x1f, 0xfc, 0x5e, 0x22,
[1643364426.516179][3494:3494] CHIP:IN: 0x47, 0xe6, 0x6d, 0xbb, 0xbb, 0xe1, 0x87, 0x97,
[1643364426.516202][3494:3494] CHIP:IN: 0x7f, 0x88, 0xfa, 0xf8, 0x04, 0x66, 0xfe, 0xf4,
[1643364426.516225][3494:3494] CHIP:IN: 0xd3, 0x17, 0x28, 0x54, 0x1b, 0x50, 0x58, 0x3f,
[1643364426.516248][3494:3494] CHIP:IN: 0xce, 0xce, 0xb6, 0xb5, 0x51, 0xd9, 0x7d, 0xb1,
[1643364426.516270][3494:3494] CHIP:IN: 0xc3, 0xe4, 0x52, 0xa4, 0x77, 0x57, 0x38, 0xd3,
[1643364426.516292][3494:3494] CHIP:IN: 0xc5, 0x12, 0xfa, 0xc5, 0x84, 0x76, 0xbc, 0x99,
[1643364426.516313][3494:3494] CHIP:IN: 0x4b,
[1643364426.516370][3494:3494] CHIP:IN: Generated compressed fabric ID
[1643364426.516397][3494:3494] CHIP:IN: 0x0f, 0x56, 0x74, 0x92, 0x4a, 0x2a, 0xd6, 0xc8,
[1643364426.516427][3494:3494] CHIP:DIS: Added new fabric at index: 1, Initialized: 1
[1643364426.516451][3494:3494] CHIP:DIS: Assigned compressed fabric ID: 0x0F5674924A2AD6C8, node ID: 0x000000000001B669
[1643364426.516473][3494:3494] CHIP:CTL: Joined the fabric at index 1. Compressed fabric ID is: 0x0F5674924A2AD6C8
[1643364426.516545][3494:3494] CHIP:IN: UDP::Init bind&listen port=5550
[1643364426.516686][3494:3494] CHIP:IN: UDP::Init bound to port=5550
[1643364426.516713][3494:3494] CHIP:IN: UDP::Init bind&listen port=5550
[1643364426.516804][3494:3494] CHIP:IN: UDP::Init bound to port=5550
[1643364426.516829][3494:3494] CHIP:IN: TransportMgr initialized
[1643364426.517670][3494:3494] CHIP:CTL: Generating NOC
[1643364426.517970][3494:3494] CHIP:CTL: Generating ICAC
[1643364426.518680][3494:3494] CHIP:DIS: Verifying the received credentials
[1643364426.520613][3494:3494] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000002 and root pubkey
[1643364426.520672][3494:3494] CHIP:IN: 0x04, 0x33, 0x4d, 0xdf, 0x93, 0xde, 0xde, 0x2a,
[1643364426.520695][3494:3494] CHIP:IN: 0x02, 0x27, 0x65, 0xf2, 0x1f, 0xfc, 0x5e, 0x22,
[1643364426.520722][3494:3494] CHIP:IN: 0x47, 0xe6, 0x6d, 0xbb, 0xbb, 0xe1, 0x87, 0x97,
[1643364426.520746][3494:3494] CHIP:IN: 0x7f, 0x88, 0xfa, 0xf8, 0x04, 0x66, 0xfe, 0xf4,
[1643364426.520769][3494:3494] CHIP:IN: 0xd3, 0x17, 0x28, 0x54, 0x1b, 0x50, 0x58, 0x3f,
[1643364426.520791][3494:3494] CHIP:IN: 0xce, 0xce, 0xb6, 0xb5, 0x51, 0xd9, 0x7d, 0xb1,
[1643364426.520814][3494:3494] CHIP:IN: 0xc3, 0xe4, 0x52, 0xa4, 0x77, 0x57, 0x38, 0xd3,
[1643364426.520836][3494:3494] CHIP:IN: 0xc5, 0x12, 0xfa, 0xc5, 0x84, 0x76, 0xbc, 0x99,
[1643364426.520857][3494:3494] CHIP:IN: 0x4b,
[1643364426.520921][3494:3494] CHIP:IN: Generated compressed fabric ID
[1643364426.520948][3494:3494] CHIP:IN: 0x8a, 0xce, 0x8f, 0xc2, 0x45, 0x13, 0x54, 0x53,
[1643364426.520981][3494:3494] CHIP:DIS: Added new fabric at index: 2, Initialized: 1
[1643364426.521004][3494:3494] CHIP:DIS: Assigned compressed fabric ID: 0x8ACE8FC245135453, node ID: 0x000000000001B669
[1643364426.521027][3494:3494] CHIP:CTL: Joined the fabric at index 2. Compressed fabric ID is: 0x8ACE8FC245135453
[1643364426.521115][3494:3494] CHIP:IN: UDP::Init bind&listen port=5550
[1643364426.521245][3494:3494] CHIP:IN: UDP::Init bound to port=5550
[1643364426.521273][3494:3494] CHIP:IN: UDP::Init bind&listen port=5550
[1643364426.521366][3494:3494] CHIP:IN: UDP::Init bound to port=5550
[1643364426.521394][3494:3494] CHIP:IN: TransportMgr initialized
[1643364426.522421][3494:3494] CHIP:CTL: Generating NOC
[1643364426.522786][3494:3494] CHIP:CTL: Generating ICAC
[1643364426.523581][3494:3494] CHIP:DIS: Verifying the received credentials
[1643364426.525366][3494:3494] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000003 and root pubkey
[1643364426.525408][3494:3494] CHIP:IN: 0x04, 0x33, 0x4d, 0xdf, 0x93, 0xde, 0xde, 0x2a,
[1643364426.525432][3494:3494] CHIP:IN: 0x02, 0x27, 0x65, 0xf2, 0x1f, 0xfc, 0x5e, 0x22,
[1643364426.525455][3494:3494] CHIP:IN: 0x47, 0xe6, 0x6d, 0xbb, 0xbb, 0xe1, 0x87, 0x97,
[1643364426.525479][3494:3494] CHIP:IN: 0x7f, 0x88, 0xfa, 0xf8, 0x04, 0x66, 0xfe, 0xf4,
[1643364426.525501][3494:3494] CHIP:IN: 0xd3, 0x17, 0x28, 0x54, 0x1b, 0x50, 0x58, 0x3f,
[1643364426.525524][3494:3494] CHIP:IN: 0xce, 0xce, 0xb6, 0xb5, 0x51, 0xd9, 0x7d, 0xb1,
[1643364426.525546][3494:3494] CHIP:IN: 0xc3, 0xe4, 0x52, 0xa4, 0x77, 0x57, 0x38, 0xd3,
[1643364426.525569][3494:3494] CHIP:IN: 0xc5, 0x12, 0xfa, 0xc5, 0x84, 0x76, 0xbc, 0x99,
[1643364426.525589][3494:3494] CHIP:IN: 0x4b,
[1643364426.525645][3494:3494] CHIP:IN: Generated compressed fabric ID
[1643364426.525672][3494:3494] CHIP:IN: 0x32, 0xf1, 0x87, 0xa5, 0xf1, 0xc8, 0x56, 0x44,
[1643364426.525701][3494:3494] CHIP:DIS: Added new fabric at index: 3, Initialized: 1
[1643364426.525723][3494:3494] CHIP:DIS: Assigned compressed fabric ID: 0x32F187A5F1C85644, node ID: 0x000000000001B669
[1643364426.525747][3494:3494] CHIP:CTL: Joined the fabric at index 3. Compressed fabric ID is: 0x32F187A5F1C85644
[1643364426.525830][3494:3494] CHIP:IN: UDP::Init bind&listen port=5550
[1643364426.525966][3494:3494] CHIP:IN: UDP::Init bound to port=5550
[1643364426.525992][3494:3494] CHIP:IN: UDP::Init bind&listen port=5550
[1643364426.526085][3494:3494] CHIP:IN: UDP::Init bound to port=5550
[1643364426.526109][3494:3494] CHIP:IN: TransportMgr initialized
[1643364426.526440][3494:3499] CHIP:DL: CHIP task running
[1643364426.526571][3494:3499] CHIP:TOO: Sending command to node 0xbc5c01
[1643364426.527235][3494:3499] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643364426.527964][3494:3499] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643364426.528189][3494:3499] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643364426.528344][3494:3499] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643364426.529248][3494:3499] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643364426.529302][3494:3499] CHIP:DIS:     Addr 0: [2001:db8::24b:36bd:6701:ac13]:5540
[1643364426.529324][3494:3499] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643364426.530025][3494:3499] CHIP:IN: Generating DestinationID. Fabric ID 0x0000000000000001, Dest node ID 0x0000000000BC5C01, Random data
[1643364426.530067][3494:3499] CHIP:IN: 0x22, 0x47, 0xa4, 0x10, 0xf9, 0x7a, 0xfe, 0x76,
[1643364426.530094][3494:3499] CHIP:IN: 0x02, 0xec, 0x1c, 0xf4, 0x08, 0x97, 0x2e, 0x80,
[1643364426.530118][3494:3499] CHIP:IN: 0x79, 0xcf, 0x59, 0x9b, 0x79, 0x13, 0xc9, 0x60,
[1643364426.530142][3494:3499] CHIP:IN: 0xfa, 0xa1, 0x27, 0x9f, 0x12, 0xa8, 0x08, 0x51,
[1643364426.530180][3494:3499] CHIP:IN: Root pubkey
[1643364426.530204][3494:3499] CHIP:IN: 0x04, 0x33, 0x4d, 0xdf, 0x93, 0xde, 0xde, 0x2a,
[1643364426.530227][3494:3499] CHIP:IN: 0x02, 0x27, 0x65, 0xf2, 0x1f, 0xfc, 0x5e, 0x22,
[1643364426.530250][3494:3499] CHIP:IN: 0x47, 0xe6, 0x6d, 0xbb, 0xbb, 0xe1, 0x87, 0x97,
[1643364426.530283][3494:3499] CHIP:IN: 0x7f, 0x88, 0xfa, 0xf8, 0x04, 0x66, 0xfe, 0xf4,
[1643364426.530306][3494:3499] CHIP:IN: 0xd3, 0x17, 0x28, 0x54, 0x1b, 0x50, 0x58, 0x3f,
[1643364426.530329][3494:3499] CHIP:IN: 0xce, 0xce, 0xb6, 0xb5, 0x51, 0xd9, 0x7d, 0xb1,
[1643364426.530351][3494:3499] CHIP:IN: 0xc3, 0xe4, 0x52, 0xa4, 0x77, 0x57, 0x38, 0xd3,
[1643364426.530373][3494:3499] CHIP:IN: 0xc5, 0x12, 0xfa, 0xc5, 0x84, 0x76, 0xbc, 0x99,
[1643364426.530393][3494:3499] CHIP:IN: 0x4b,
[1643364426.530414][3494:3499] CHIP:IN: IPK
[1643364426.530437][3494:3499] CHIP:IN: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
[1643364426.530469][3494:3499] CHIP:IN: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
[1643364426.530507][3494:3499] CHIP:IN: Generated DestinationID output
[1643364426.530532][3494:3499] CHIP:IN: 0x77, 0xdb, 0xea, 0xc3, 0xe3, 0x33, 0xdb, 0x32,
[1643364426.530555][3494:3499] CHIP:IN: 0x76, 0x76, 0x18, 0x1b, 0x3f, 0xc2, 0x6b, 0xeb,
[1643364426.530577][3494:3499] CHIP:IN: 0xa5, 0xdd, 0xfe, 0x45, 0x38, 0x47, 0xff, 0x1b,
[1643364426.530609][3494:3499] CHIP:IN: 0x07, 0xde, 0xc2, 0x0d, 0x7f, 0x2c, 0xcb, 0x01,
[1643364426.530633][3494:3499] CHIP:SC: Including MRP parameters
[1643364426.530701][3494:3499] CHIP:IN: Prepared plaintext message 0xaaaad9979810 to 0x0000000000000000 (0)  of type 0x30 and protocolId (0, 0) on exchange 25909i with MessageCounter:1983584652.
[1643364426.530753][3494:3499] CHIP:IN: Sending plaintext msg 0xaaaad9979810 with MessageCounter:1983584652 to 0x0000000000000000 at monotonic time: 393830 msec
[1643364426.530893][3494:3499] CHIP:SC: Sent Sigma1 msg
[1643364426.530928][3494:3499] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643364426.531253][3494:3499] CHIP:DIS: Discovered node without a pending query
[1643364426.531282][3494:3499] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643364426.531308][3494:3499] CHIP:DIS:     Addr 0: [2001:db8::24b:36bd:6701:ac13]:5540
[1643364426.531331][3494:3499] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643364426.531359][3494:3499] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643364426.531507][3494:3499] CHIP:DIS: Discovered node without a pending query
[1643364426.531531][3494:3499] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643364426.531555][3494:3499] CHIP:DIS:     Addr 0: [2001:db8::24b:36bd:6701:ac13]:5540
[1643364426.531576][3494:3499] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643364426.531601][3494:3499] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643364426.531744][3494:3499] CHIP:DIS: Discovered node without a pending query
[1643364426.531768][3494:3499] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643364426.531791][3494:3499] CHIP:DIS:     Addr 0: [2001:db8::24b:36bd:6701:ac13]:5540
[1643364426.531811][3494:3499] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643364426.531836][3494:3499] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643364426.531980][3494:3499] CHIP:DIS: Discovered node without a pending query
[1643364426.532003][3494:3499] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643364426.532026][3494:3499] CHIP:DIS:     Addr 0: [2001:db8::24b:36bd:6701:ac13]:5540
[1643364426.532047][3494:3499] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643364426.532110][3494:3499] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643364436.526982][3494:3494] CHIP:-: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:232: CHIP Error 0x00000032: Timeout at ../../examples/chip-tool/commands/common/CHIPCommand.cpp:59
[1643364436.527084][3494:3494] CHIP:TOO: Run command failure: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:232: CHIP Error 0x00000032: Timeout
[1643364436.533690][3494:3494] CHIP:SPT: VerifyOrDie failure at ../../examples/chip-tool/third_party/connectedhomeip/src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0
Aborted (core dumped)
ubuntu@matter-7-5:~/connectedhomeip/out/standalone$

```

**Comment by andy31415** [comment] 2022-01-31 18:45
Looks like a duplicate of #14472

**Closed by andy31415** 2022-01-31 18:45 UTC
