### ISSUE TITLE
M1 Mac Build issue

### ISSUE THREAD

**Issue by raman325** [project-chip/connectedhomeip#19215] opened 2022-06-06 05:21 UTC
#### Problem

Follow the wiki here: https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/BUILDING.md

at `ninja -C out/host` see the following: https://rentry.co/b5nu4

It appears my laptop wants to target the x86_64 architecture even though I am running an arm64 architecture. I tried setting the `target_cpu` option to no avail. Any suggestions on how to resolve?

**Comment by bzbarsky-apple** [comment] 2022-06-07 03:21
Duplicate of #19134

**Comment by raman325** [comment] 2022-06-07 05:35
thanks for the heads up, I will track this in the other issue

**Closed** 2022-06-07 05:34 UTC
