### ISSUE TITLE
Use of Variable Length Arrays in generated code

### ISSUE THREAD

**Issue by mdamle** [project-chip/connectedhomeip#8558] opened 2021-07-22 01:38 UTC
#### Problem
variable length arrays  are used in generated code: CHIPClientCallbacks.cpp. For example:  https://github.com/project-chip/connectedhomeip/blob/master/src/controller/data_model/gen/CHIPClientCallbacks.cpp#L854 
`
uint16_t count = chip::Encoding::LittleEndian::Read16(message);
`
_AudioOutputInfo` data[count];
`
There are about 24 such instances. There are 2 issues with this usage:

1. Variable Length Arrays are not universally supported by all compilers since they are not part of c++ standard
2. The generated code uses over the wire value to allocate data on stack which is dangerous.

 * expected behavior
 
1. Check size before allocation
2. Allocate on heap instead of stack

 * actual behavior
 As explained in the problem section.
 * steps to reproduce
Compile code on top of tree and inspect generated CHIPClientCallbacks.cpp file.
 >

**Comment by mdamle** [comment] 2021-07-22 01:38
cc @tcarmelveilleux for visibility

**Comment by bzbarsky-apple** [comment] 2021-07-22 02:13
@vivien-apple @mrjerryjohns

**Comment by tcarmelveilleux** [comment] 2021-07-22 15:05
The root cause of this issue is wanted to pass "flat arrays" to callbacks when lists are used. I think these lists should be handled by iteration over the payload with an abstracted list iterator backed by a TLV reader, rather than copy to flat arrays. That would avoid alloc entirely, and avoid requiring to trust any sizes from the wire for an alloc. A temporary reader could be used to schema-validate, but access to the list elements should be abstracted with an iterator.

**Comment by mlepage-google** [comment] 2021-07-22 15:11
+1 for iterator access.

**Comment by bzbarsky-apple** [comment] 2021-11-04 01:04
Fixed in https://github.com/project-chip/connectedhomeip/pull/10681

**Closed by bzbarsky-apple** 2021-11-04 01:04 UTC
