### ISSUE TITLE
[ESP32] On-network commissioning does not work

### ISSUE THREAD

**Issue by jadhavrohit924** [project-chip/connectedhomeip#15952] opened 2022-03-08 08:53 UTC
#### Problem
* After boot device is not connecting to provided AP.
Through menuconfig
* Changed Rendezvous mode to On-Network ( Demo -->  Rendezvous Mode ).
* Set ssid and password  ( Example Connection Configuration ).
* Also tried with full IP-based commissioning ( Component config  --> CHIP Device Layer  --> Commissioning options  --> )

On commit 1f458a5342cf1cfacc6ac54b7c8020f7cfd49a74 

 #### Proposed Solution
After boot device should connet to AP

**Comment by dhrishi** [comment] 2022-03-08 09:00
@cecille Can you please check if we are missing something here?

**Comment by jadhavrohit924** [comment] 2022-03-08 11:30
Setting ssid and pass through ( Component config --> CHIP Device Layer --> WiFi Station Options ) is working.
And no need of full IP-based commissioning.

**Comment by dhrishi** [comment] 2022-03-08 11:31
Thanks @jadhavrohit924 . @cecille @wqx6 Please confirm what should be used here?

**Comment by cecille** [comment] 2022-03-08 16:23
I'm not sure what you're trying to do. If you're using on-network commissioning, the device should already be connected to the network before commissioning is attempted.

**Comment by dhrishi** [comment] 2022-03-08 18:52
@cecille That is right. The question really is about configuration of SSID and passphrase through menuconfig. And there seem to be 2 choices:

i. idf.py menuconfig -> Example Connection Configuration (with this on-network commissioning does not work)

ii. idf.py menuconfig -> Component config --> CHIP Device Layer --> WiFi Station Options (with this on-network commissioning works)

If i. above is to be used then commissioning should be fixed and ii. removed

If ii. above is to be used then the fix is not required and i. should be removed

**Comment by cecille** [comment] 2022-03-09 01:49
I've always used ii and it seems to work.

I also don't know what i was intended for. I think we need espressif folks to chime in on that one. I'm not sure who though, because I don't think that original option is from us. It's not in the chip Kconfig.

**Comment by dhrishi** [comment] 2022-03-09 02:49
@cecille I thought it was added by some Matter folks related to on-network commissioning and hence pulled you in. Sorry for the confusion :-)

Thanks a lot @chshu for the clarification.

**Comment by dhrishi** [comment] 2022-03-11 09:24
#15955 is merged. Closing this

**Closed by dhrishi** 2022-03-11 09:24 UTC
