### ISSUE TITLE
presubmit does not catch the compilation failure introduced by PR 7080

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#7199] opened 2021-05-27 18:33 UTC
all presubmit are  green for PR 7080, but locally it fails in gn_build.sh

-------------------------------
-- Build: GN configure
'--------------------------------
ERROR at //examples/platform/linux/AppMain.cpp:28:11: Include not allowed.
#include <lib/shell/Engine.h>
     ^-----------------
It is not in any dependency of
 //examples/platform/linux:app-main
The include file is in the target(s):
 //src/lib/shell:shell_core
which should somehow be reachable.

**Comment by turon** [comment] 2021-05-27 18:43
Duplicate of #7197

**Closed** 2021-06-08 06:58 UTC
