### ISSUE TITLE
[Build]  Bootstrap.sh Failing 

### ISSUE THREAD

**Issue by mttrRDRSDX** [project-chip/connectedhomeip#31237] opened 2024-01-04 06:26 UTC
### Build issue(s)

**Trying to build bridge app , previously it was working fine till last week of previous year 

but now am facing multiple issues while bootstrapping it self and unable to build :

with existing cloned repo i faced the following issue :** 

  WELCOME TO...
 
         █
         █
     ▄   █   ▄                                █     █
     ▀▀█████▀▀      ▄▀▀▀▄ ▄▀▀▀▄    ▄▀▀▀▀▄█  ▀▀█▀▀▀▀▀█▀▀   ▄▀▀▀▀▄    ▄▀▀
   ▀█▄       ▄█▀   █     █     █  █      █    █     █    █▄▄▄▄▄▄█  █   
     ▀█▄   ▄█▀     █     █     █  █      █    █     █    █         █   
  ▄██▀▀█   █▀▀██▄  █     █     █   ▀▄▄▄▄▀█    ▀▄▄   ▀▄▄   ▀▄▄▄▄▀   █   
▀▀    █   █    ▀▀
 
  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.
 
Downloading and installing packages into local source directory:
 
  Setting up CIPD package manager...done (5.2s)
warning: pattern "/home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/.environment/pigweed.json" matched 0 files
  Setting up Project actions........skipped (0.1s)
  Setting up Python environment.....Traceback (most recent call last):
  File "/home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 982, in <module>
    sys.exit(main())
  File "/home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 974, in main
    return EnvSetup(**vars(parse())).setup()
  File "/home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 573, in setup
    result = step(spin)
  File "/home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/env_setup.py", line 762, in virtualenv
    if not virtualenv_setup.install(
  File "/home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 443, in install
    install_packages(gn_target)
  File "/home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/third_party/pigweed/repo/pw_env_setup/py/pw_env_setup/virtualenv_setup/install.py", line 402, in install_packages
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
**FileNotFoundError: [Errno 2] No such file or directory: 'gn'**

**so i recloned the repo and tried again to bootstrap but now am facing the following issue :** 

source ../../../scripts/bootstrap.sh 

Synchronizing submodule url for '../../common/QRCode/repo'

Synchronizing submodule url for '../../common/m5stack-tft/repo'

Synchronizing submodule url for '../../../third_party/asr/asr550x/asr_sdk'

Synchronizing submodule url for '../../../third_party/asr/asr582x/asr_sdk'

Synchronizing submodule url for '../../../third_party/asr/asr595x/asr_sdk'

Synchronizing submodule url for '../../../third_party/asr/components'

Synchronizing submodule url for '../../../third_party/boringssl/repo/src'

Synchronizing submodule url for '../../../third_party/bouffalolab/repo'

Synchronizing submodule url for '../../../third_party/cirque/repo'

Synchronizing submodule url for '../../../third_party/editline/repo'

Synchronizing submodule url for '../../../third_party/freertos/repo'

Synchronizing submodule url for '../../../third_party/imgui/repo'

Synchronizing submodule url for '../../../third_party/infineon/cyw30739_sdk/repos/30739A0'

Synchronizing submodule url for '../../../third_party/infineon/cyw30739_sdk/repos/CYW930739M2EVB-01'

Synchronizing submodule url for '../../../third_party/infineon/cyw30739_sdk/repos/btsdk-include'

Synchronizing submodule url for '../../../third_party/infineon/cyw30739_sdk/repos/btsdk-tools'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/TARGET_CY8CKIT-062S2-43012'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/abstraction-rtos'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/anycloud-ota'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/bluetooth-freertos'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/btstack'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/clib-support'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/connectivity-utilities'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/core-lib'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/core-make'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/freertos'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/kv-store'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/lwip'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/lwip-network-interface-integration'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/mbedtls'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/mtb-hal-cat1'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/mtb-pdl-cat1'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/psoc6cm0p'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/recipe-make-cat1a'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/retarget-io'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/secure-sockets'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/serial-flash'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/whd-bsp-integration'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/wifi-connection-manager'

Synchronizing submodule url for '../../../third_party/infineon/psoc6/psoc6_sdk/libs/wifi-host-driver'

Synchronizing submodule url for '../../../third_party/jsoncpp/repo'

Synchronizing submodule url for '../../../third_party/libwebsockets/repo'

Synchronizing submodule url for '../../../third_party/mbed-mcu-boot/repo'

Synchronizing submodule url for '../../../third_party/mbed-os-cypress-capsense-button/repo'

Synchronizing submodule url for '../../../third_party/mbed-os-posix-socket/repo'

Synchronizing submodule url for '../../../third_party/mbed-os/repo'

Synchronizing submodule url for '../../../third_party/mbedtls/repo'

Synchronizing submodule url for '../../../third_party/mt793x_sdk/filogic'

Synchronizing submodule url for '../../../third_party/mt793x_sdk/lwip'

Synchronizing submodule url for '../../../third_party/mt793x_sdk/mDNSResponder'

Synchronizing submodule url for '../../../third_party/nanopb/repo'

Synchronizing submodule url for '../../../third_party/nlassert/repo'

Synchronizing submodule url for '../../../third_party/nlio/repo'

Synchronizing submodule url for '../../../third_party/nlunit-test/repo'

Synchronizing submodule url for '../../../third_party/nxp/mw320_sdk/repo'

Synchronizing submodule url for '../../../third_party/open-iot-sdk/sdk'

Synchronizing submodule url for '../../../third_party/openthread/ot-efr32'

Synchronizing submodule url for '../../../third_party/openthread/ot-ifx'

Synchronizing submodule url for '../../../third_party/openthread/ot-nxp'

Synchronizing submodule url for '../../../third_party/openthread/ot-qorvo'

Synchronizing submodule url for '../../../third_party/openthread/ot-ti'

Synchronizing submodule url for '../../../third_party/openthread/repo'

Synchronizing submodule url for '../../../third_party/ot-br-posix/repo'

Synchronizing submodule url for '../../../third_party/perfetto/repo'

Synchronizing submodule url for '../../../third_party/pigweed/repo'

Synchronizing submodule url for '../../../third_party/pybind11/repo'

Synchronizing submodule url for '../../../third_party/qpg_sdk/repo'

Synchronizing submodule url for '../../../third_party/silabs/gecko_sdk'

Synchronizing submodule url for '../../../third_party/silabs/matter_support'

Synchronizing submodule url for '../../../third_party/silabs/wifi_sdk'

Synchronizing submodule url for '../../../third_party/silabs/wiseconnect-wifi-bt-sdk'

Synchronizing submodule url for '../../../third_party/simw-top-mini/repo'

Synchronizing submodule url for '../../../third_party/st/STM32CubeWB'

Synchronizing submodule url for '../../../third_party/ti_simplelink_sdk/repo_cc13xx_cc26xx'

Synchronizing submodule url for '../../../third_party/ti_simplelink_sdk/repo_cc32xx'

bash: scripts/setup/gen_pigweed_cipd_json.py: No such file or directory
 
  WELCOME TO...
 
         █

         █

     ▄   █   ▄                                █     █

     ▀▀█████▀▀      ▄▀▀▀▄ ▄▀▀▀▄    ▄▀▀▀▀▄█  ▀▀█▀▀▀▀▀█▀▀   ▄▀▀▀▀▄    ▄▀▀

   ▀█▄       ▄█▀   █     █     █  █      █    █     █    █▄▄▄▄▄▄█  █   

     ▀█▄   ▄█▀     █     █     █  █      █    █     █    █         █   

  ▄██▀▀█   █▀▀██▄  █     █     █   ▀▄▄▄▄▀█    ▀▄▄   ▀▄▄   ▀▄▄▄▄▀   █   

▀▀    █   █    ▀▀
 
  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.
 
**bash: /home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/.environment/pigweed-venv/bin/python3: No such file or directory

Installing pip requirements for all...

bash: /home/rf6000eng1/Desktop/new/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/.environment/pigweed-venv/bin/pip: No such file or directory**

i even tried checking out to the previous commit which was working from me for last 6 Months : 
**commit-ID : 5313f741b3b8c0eaf2a0dc22157fc9016e4ec4bb**

above commit was working fine for me from last  couple of months but it is also troubling now with pip version even after upgrading pip and it is successful still it says its an older one 
 
follow is the problem which is being face with older crepo which was working fine:

    raise Error(f'Failed to import module "{module_name}"') from err
pw_cli.plugins.Error: Failed to import module "pw_watch.watch" (ImportError: cannot import name 'OneStyleAndTextTuple' from 'prompt_toolkit.formatted_text' (/home/rf6et/Desktop/saransh_mttr/private_clusters/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/prompt_toolkit/formatted_text/__init__.py))
Error during bootstrap--see messages above.
Installing pip requirements for all...

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

then upgraded the pip

pip install --upgrade pip
Requirement already satisfied: pip in /home/rf6et/Desktop/saransh_mttr/private_clusters/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/15/aa/3f4c7bcee2057a76562a5b33ecbd199be08cdb4443a02e26bd2c3cf6fc39/pip-23.3.2-py3-none-any.whl.metadata
  Using cached pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)
Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-23.3.2
$ pip --version
pip 23.3.2 from /home/rf6et/Desktop/saransh_mttr/private_clusters/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/pip (python 3.8)

still it gave same issue : 

    raise Error(f'Failed to import module "{module_name}"') from err
pw_cli.plugins.Error: Failed to import module "pw_watch.watch" (ImportError: cannot import name 'OneStyleAndTextTuple' from 'prompt_toolkit.formatted_text' (/home/rf6et/Desktop/saransh_mttr/private_clusters/connectedhomeip/examples/bridge-app/linux/third_party/connectedhomeip/.environment/pigweed-venv/lib/python3.8/site-packages/prompt_toolkit/formatted_text/__init__.py))
Error during bootstrap--see messages above.
Installing pip requirements for all...

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

**Comment by minq-park-lge** [comment] 2024-01-11 07:47
maybe the same issue → https://github.com/project-chip/connectedhomeip/issues/31360

**Comment by andy31415** [comment] 2024-01-11 14:47
Duplicate of #30981 - please apply #30987

**Closed by andy31415** 2024-01-11 14:47 UTC
Labels: build issue, linux, needs triage
