### ISSUE TITLE
TC-IDM-3.1: Test#2 Write Action Request Failure

### ISSUE THREAD

**Issue by cm-s-dev** [project-chip/connectedhomeip#16023] opened 2022-03-09 17:35 UTC
#### Problem
Write Action Request fails with `General error: 0x80`. 
RPI Controlee outputs error 
`Failed to process write request: ../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/lib/core/CHIPTLVReader.cpp:516: CHIP Error 0x00000021: End of TLV`

#### Commands
`chip-tool any write-by-id  0x0008 0x0010 1 1 0xffff`

 #### Test Setup:
`chip-tool` and `chip-all-clusters-app`: 
commit `5cbe2931f64e16a44fc843e148325909fbe1511d (tag: TE8/rc3)`

#### Log
[IDM-3.1_test2_error.txt](https://github.com/project-chip/connectedhomeip/files/8216864/IDM-3.1_test2_error.txt)

**Comment by bzbarsky-apple** [comment] 2022-03-09 17:40
Duplicate of https://github.com/project-chip/connectedhomeip/issues/15999

**Closed by bzbarsky-apple** 2022-03-09 17:40 UTC
Labels: Interaction Model Work
