### ISSUE TITLE
[Feature] Integrate tv-app and tv-casting-app into our CI system

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#30906] opened 2023-12-10 17:10 UTC
### Feature description

...
we have two Android apps, namely, the tv-app and tv-casting-app, that are not integrated into our CI system. We need to  integrate them into CI to detect any potential issues or breaks. Here is the reference.

full android builds we have here:
https://github.com/project-chip/connectedhomeip/blob/master/.github/workflows/full-android.yaml
smoketest here:
https://github.com/project-chip/connectedhomeip/blob/master/.github/workflows/smoketest-android.yaml
NRF is an example that does path detection to run more things when specific paths are changed:
https://github.com/project-chip/connectedhomeip/blob/master/.github/workflows/examples-nrfconnect.yaml#L51

### Platform

android

**Comment by kliao-csa** [comment] 2024-02-15 19:59
#32012

**Comment by kliao-csa** [comment] 2024-02-16 00:00
Now runs on PR

Next steps:
NRF style path detection
Possibly move code to scripts/examples/tv_app_example.sh to match convention
Remove from smoke tests

**Comment by kliao-csa** [comment] 2024-03-28 16:22
https://github.com/project-chip/connectedhomeip/pull/32774 Reverting changes made so far - I thought we wanted to add smoketest CI builds into standalone non-preliminary CI builds, but it seems we would actually like runtime testing.

**Comment by kliao-csa** [comment] 2024-04-09 22:18
After reading over the additional context provided, I believe this issue is a duplicate of #32787

**Comment by kliao-csa** [comment] 2024-04-09 22:18
As there is already work done on that issue, I believe we can close this duplicate. Second opinions welcome.

**Comment by kliao-csa** [comment] 2024-04-09 22:19
Mark not as complete, but as duplicate

**Closed by kliao-csa** 2024-04-09 22:18 UTC
Labels: feature work, feature request, tv, needs triage, CI/CD improvements
