### ISSUE TITLE
[TC-MF-1.25], [TC-MF-1.26] - Received incorrect error code in step5 

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#17217] opened 2022-04-08 16:16 UTC
**Issue** : 
./chip-tool pairing open-commissioning-window 1 1 901 1000 3840(on TH1)
When we run the above command chip-tool throws an error code as 0x85 (INVALID_COMMAND), but according to spec chip-tool need to provide cluster-specific-error code in log.

**Spec reference** : https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/AdminCommissioningCluster.adoc#ref_AdminCommissioningCluster_Status

**Steps to reproduce** :

- DUT side :

1. sudo rm -rf /tmp/chip_*
2. sudo ./chip-all-clusters-app --wifi

- TH side :

1. ./chip-tool pairing ble-wifi 1 zigbeehome matter123 20202021 3840 (on TH1)
2. ./chip-tool pairing open-commissioning-window 1 1 900 1000 3840(on TH1)
3. After the timeout that is after 900 seconds run below command
4. ./chip-tool pairing open-commissioning-window 1 1 901 1000 3840(on TH1)

**Test platform** :
Chip-tool - RPI
DUT - RPI
 
**Expected behaviour** : DUT_CE does not open its Commissioning window to allow a second commissioning

**Actual behaviour** : Run command failure: IM Error 0x00000585: General error: 0x85 (INVALID_COMMAND)

**PFA logs** : 
[MF_cntrl.txt](https://github.com/project-chip/connectedhomeip/files/8453861/MF_cntrl.txt)

**Comment by tehampson** [comment] 2022-04-21 14:47
When I try this out locally, on the TH side, I get `Run command failure: IM Error 0x00000601: Cluster-specific error: 0x01`. On the DUT side I see `Failed to open commissioning window. Cluster status 1`.

Based on spec `11.19.8. Commands` it says `Only one commissioning window can be active at a time. If a Node receives another open commissioning command when one OCW is already active, it SHALL return a failure response`. I am seeing the right error code as per `11.19.9. Status Codes`

MF_cntrl.txt only contains logs from TH side and not, DUT. If the issue is reproducible for sowmyassp, can we get logs from DUT? That would be more helpful in understanding why they were seeing `General error: 0x85` instead of the expected error

**Comment by sowmyassp** [comment] 2022-04-22 09:56
@tehampson 
[log_dut.txt](https://github.com/project-chip/connectedhomeip/files/8539716/log_dut.txt)

**Comment by sowmyassp** [comment] 2022-04-25 12:40
Facing same issue in [TC-MF-1.27], [TC-MF-1.28] 

Steps to reproduce 
DUT side :
sudo rm -rf /tmp/chip_*
sudo ./chip-all-clusters-app --wifi

TH side :
./chip-tool pairing ble-wifi 1 zigbeehome matter123 20202021 3840 (on TH1)
./chip-tool pairing open-commissioning-window 1 1 180 1000 3840(on TH1)
After the timeout that is after 900 seconds run below command
./chip-tool pairing open-commissioning-window 1 1 179 1000 3840(on TH1)

PFA logs :

**Comment by tehampson** [comment] 2022-04-26 14:41
Okay I got access to test cases portion of the spec, things are making a lot more sense now. I was getting a different error because I ignored the "After the timeout that is after 900 seconds run below command". But because the window isn't open we actually expecting the `Failed to open commissioning window. Cluster status 1`.

179 and 901 are invalid timeout arguments, since these values since `MaxCommissioningTimeout()` is 900, and `MinCommissioningTimeout()` is 180. That is exactly what the test case is trying to test. The spec itself in section [11.19.8.1. OpenCommissioningWindow (OCW) Command](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/master/src/service_device_management/AdminCommissioningCluster.adoc#81-opencommissioningwindow-ocw-command) says:

>In case of any other parameter error, this command SHALL fail with a status code of `COMMAND_INVALID`

This is a parameter error. The testcase says (the expected behaviour):
> DUT_CE does not open its Commissioning window to allow a second commissioning

Which we are doing. We are not opening up a commissioning window, and because the command is not resulting in a commissioning window being opened the actual behaviour of the command returning an error lines up with the expected behaviour.

sowmyassp what do you want to change here? Do you want the test case updated to be more verbose in stating that the command should return with an error?

**Comment by tehampson** [comment] 2022-04-26 14:46
I am closing issue, please re-open is there is anything else you think should be done. But the testcase has now been updated to say that you know "DUT_CE does not open its Commissioning window to allow a second commissioning", because "DUT_CE shows 'Failed to open commissioning window. Global status 0x85'

**Closed by tehampson** 2022-04-26 14:46 UTC
Labels: V1.0, cert
