### ISSUE TITLE
[BUG] Android Build Fail in specific NDK version

### ISSUE THREAD

**Issue by joonhaengHeo** [project-chip/connectedhomeip#26289] opened 2023-04-28 02:40 UTC
### Reproduction steps

When building with the NDK version provided in the Android Build Guide document, the following build error occurs.
NDK Version : 21.4.7075529
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/android_building.md

 FAILED: obj/src/access/libaccess.AccessControl.cpp.o
2023-04-28 11:24:54 INFO    /home/joonhaeng/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang++ -MMD -MF obj/src/access/libaccess.AccessControl.cpp.o.d -Wconversion -march=armv8-a -O0 -g2 -fno-common -ffunction-sections -fdata-sections -fvisibility=hidden -fno-exceptions -funwind-tables -fPIC -Wall -Werror -Wstack-usage=8192 -Wextra -Wshadow -Wunreachable-code -Wvla -Wformat -Wformat-nonliteral -Wformat-security -Wimplicit-fallthrough -Wheader-hygiene -Wshorten-64-to-32 -Wformat-type-confusion -Wno-deprecated-declarations -Wno-missing-field-initializers -Wno-unknown-warning-option -Wno-unused-parameter -fdiagnostics-color -fno-strict-aliasing -fmacro-prefix-map=../../= -std=gnu++14 -fno-rtti -Wnon-virtual-dtor -DCHIP_HAVE_CONFIG_H=1 -I../../src/include -I../../src -Igen/include -I../../zzz_generated/app-common -I../../config/standalone -I../../third_party/nlassert/repo/include -I../../third_party/nlio/repo/include -I../../third_party/nlfaultinjection/repo/include -I../../third_party/mbedtls/repo/include -c ../../src/access/AccessControl.cpp -o obj/src/access/libaccess.AccessControl.cpp.o
2023-04-28 11:24:54 INFO    clang++: error: unknown argument: '-fmacro-prefix-map=../../='

I believe that a revision to the document is necessary, as building with NDK version 24.0.8215888 succeeds without any issues. Additionally, I am aware that the SDK version of Android ChipTool has also been updated to 26, so I think this section also requires a revision.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

e4d000d29ed09ad2dd74125b22a854305a526393

### Platform

android

**Comment by bzbarsky-apple** [comment] 2023-04-28 04:08
Duplicate of https://github.com/project-chip/connectedhomeip/issues/25987

**Closed by bzbarsky-apple** 2023-04-28 04:08 UTC
