### ISSUE TITLE
NRF image fails to build

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#1558] opened 2020-07-10 18:42 UTC
#### Problem

Image failed to build with:

```
+ wget -qO- https://www.nordicsemi.com/-/media/Software-and-other-downloads/Desktop-software/nRF-command-line-tools/sw/Versions-10-x-x/10-7-0/nRFCommandLineTools1070Linuxamd64tar.gz
+ tar xz -C /tmp
+ dpkg -i /tmp/JLink_Linux_V662b_x86_64.deb
Selecting previously unselected package jlink.
(Reading database ... 30635 files and directories currently installed.)
Preparing to unpack .../JLink_Linux_V662b_x86_64.deb ...
Removing /opt/SEGGER/JLink ...
/opt/SEGGER/JLink not found (OK)
Unpacking jlink (6.622) ...
dpkg: dependency problems prevent configuration of jlink:
 jlink depends on libncurses5 (>= 5.5); however:
  Package libncurses5 is not installed.

dpkg: error processing package jlink (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 jlink

```

 #### Proposed Solution
Add ncurses library to the image.

**Comment by rwalker-apple** [comment] 2020-07-10 18:46
ncurses is already part of the image, the problem is that debian doesn't honor ncurses6 as ncurses5 compatible.  the other nrf docker image has a fix for this.  wish these 2 images were combined.

**Comment by andy31415** [comment] 2020-07-10 18:49
I believe there is an open issue to merge. I will look into having a quick fix for now: android image seems to be stuck to 2.18 - need to make it 3.0 and nrf fails.

**Comment by rwalker-apple** [comment] 2020-07-10 19:09
yeah, this is a new Dockerfile from the Nordic folks that probably needed rebasing on my ubuntu:focal PR before landing

**Closed** 2020-07-11 02:24 UTC
