### ISSUE TITLE
clean_tree.sh deletes tracked files

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#1400] opened 2020-07-01 16:11 UTC
#### Problem
After I run `scripts/helpers/clean_tree.sh`, my `git status` looks like this:
```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	deleted:    examples/common/QRCode/repo
	deleted:    examples/common/m5stack-tft/repo
	deleted:    third_party/mbedtls/repo
	deleted:    third_party/nlassert/repo
	deleted:    third_party/nlfaultinjection/repo
	deleted:    third_party/nlio/repo
	deleted:    third_party/nlunit-test/repo
```

`clean_tree.sh` should not be introducing changes to the tree.

This started happening after the commit of 4d762b6dee6c332d8a830cacce3de91489ab1d1c (<https://github.com/project-chip/connectedhomeip/pull/1262>), which removed those directories (in particular, the parent directories of those "repo" directories) from `.gitignore`.

In general, it's not clear to me how the submodule setup here is supposed to interact with `Makefile-bootstrap`'s `repos` and `clean-repos` targets.  The latter is what seems to cause the issue in this case, by the way.

 #### Proposed Solution
Sort out how this submodule setup interacts with `Makefile-bootstrap`.  Possibly we get rid of `Makefile-bootstrap` and update all documentation referencing it to describe the corresponding `git submodule ....` commands?

@sagar-apple @mspang @andy31415

**Comment by mspang** [comment] 2020-07-01 20:36
Deleting subrepositories risks destroying local changes so this is something that we should be careful about. It's also fairly inefficient to repeatedly clean & re-clone.

That said, it's still possible to do it without dirtying the tree, it just requires running:

  git submodule deinit --all

before deleting.

I think the "dist" / out of repo case can work alongside the native submodules. It would involve

(1) Converting the native submodules to repos.conf when building the distro archive (or just verifying they are in sync in CI)
(2) Having a common bootstrap that adapts between native submodules and repo.conf

That way we still get the native submodule behavior while in source control. e.g., You get an indication from "git status" when your tree falls out of line with what chip's tracking, which should be what chip's CI should test against.

On that dirtiness issue, the cause is that repos.conf points at branches which move independently from chip. I think this is an anti-pattern because we lose all control over timing of the dependency updates which is important when transitioning over a backward incompatible change. Without tracking dependency revisions, old chip revisions can't be expected to compile in the present because the bootstrap will sync versions that are inconsistent with respect to the transition. It's quite tedious to check out a working state with a branch based approach, and tools like "git bisect" will not be usable to track down regressions.

**Comment by gerickson** [comment] 2020-07-01 21:01
With respect to:

> On that dirtiness issue, the cause is that repos.conf points at branches which move independently from chip.

The `commit = <The 'commit' key allows you to specify a particular commit
hash or tag if you do not want HEAD of the specified branch.>` KVP of *repos.conf* allows locking to a specific point in time for a dependent external project.

**Comment by mspang** [comment] 2020-07-03 00:48
I see several possible paths forward to get back to consistency
(1) Back out the submodules change and stick with nlbuild-autotools. We'd lose some of the perks of native submodules and you'll need to have "make" and nlbuild-autotools even if building with another build system such as cmake.
(2) Use submodules exclusively (but then we lose the support for managing dependencies in the tarball case)
(3) Keep both and make sure they stay in sync (with CI checks).
(4) Use native submodules while in git, and generate repos.conf when generating tarballs.

Options (4) seems optimal to me, with (3) as a close second.

How bad is the dual approach really? The issues we're encountering seem minor to me, and fixable (e.g. nlbuild-autotools should avoid running "git rm" on the submodules or git commands in general. Changing the git index goes far beyond what I would expect from a "clean" operation. Deleting the checked out repository would actually not cause an issue, although I think it's debatable whether developers expect make "clean" to delete repositories from the source tree. I certainly wouldn't).

**Comment by mspang** [comment] 2020-07-03 01:15
I've uploaded some changes toward either (3) or (4) here:

https://github.com/project-chip/connectedhomeip/pull/1430
https://github.com/project-chip/connectedhomeip/pull/1432

The first PR merges the two files together and the second one adds a script that syncs the listed branch and updates both the submodules and repos.conf.

For (3), the remaining step would be
- Integrate with CircleCI to make it an error if things get out of sync.

For (4), the remaining step would be
- Delete repos.conf and instead generate it when generting a dist archive, and move bootstrap onto the appropriate path based on whether there's a .git present.

**Comment by mspang** [comment] 2020-07-03 01:49
It looks like another perk we're getting with native submodules is that github can show submodule diffs in PRs.

**Comment by mspang** [comment] 2020-07-03 21:29
Proposed fix for clean_tree.sh leaving staged deletions here:
https://github.com/nestlabs/nlbuild-autotools/pull/67

**Comment by bzbarsky-apple** [comment] 2020-07-06 18:31
My 2 cents:

1) I think we should have an explicit step to change what versions of the subrepos we pull in.  That means not putting `master` in `repos.conf` if we use `repos.conf`.
2) If we keep both `repos.conf` and git submodules, we should definitely have CI that ensures the two are in sync.  @mspang's work above is nice progress toward this.
3) If we keep both systems, I expect more pain points will arise, but we can probably deal with them as they do...
4) Of the options listed in https://github.com/project-chip/connectedhomeip/issues/1400#issuecomment-653275478 I think I like option 4 the best, assuming it addresses the use cases we wanted out of `repos.conf`.

**Comment by rwalker-apple** [comment] 2020-07-10 02:11
FYI: I recently removed `make -f Makefile-bootstrap repos-clean` from clean_tree.sh....

**Comment by mspang** [comment] 2020-07-10 18:51
Sounds like we can close it in that case.

**Closed** 2020-07-10 19:09 UTC
