### ISSUE TITLE
[Build] Build on Linux failed

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#28119] opened 2023-07-20 16:08 UTC
### Build issue(s)

https://github.com/project-chip/connectedhomeip/actions/runs/5604176593/job/15182457968

**Comment by bzbarsky-apple** [comment] 2023-07-20 17:51
Duplicate of https://github.com/project-chip/connectedhomeip/issues/27821

**Closed by bzbarsky-apple** 2023-07-20 17:51 UTC
Labels: build issue, needs triage
