### ISSUE TITLE
[TE9] chip-tool segmentation fault when running TC-PS-2.2

### ISSUE THREAD

**Issue by ifyall** [project-chip/connectedhomeip#18644] opened 2022-05-19 22:41 UTC
#### Problem
When running TC-PS-2.2 in TE9, the chip-tool crashed with a segmentation fault when executing the command 'powersource subscribe-event-by-id'

> ubuntu@ubuntu:~$ chip-tool powersource subscribe-event-by-id 0 120 3600 12344321 1
> [1652385557.647020][34542:34542] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_kvs
> [1652385557.647561][34542:34542] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_factory.ini
> [1652385557.647722][34542:34542] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_config.ini
> [1652385557.647830][34542:34542] CHIP:DL: ChipLinuxStorage::Init: Using KVS config file: /tmp/chip_counters.ini
> [1652385557.648183][34542:34542] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-iDi3au)
> [1652385557.648865][34542:34542] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
> [1652385557.648925][34542:34542] CHIP:DL: NVS set: chip-counters/reboot-count = 114 (0x72)
> [1652385557.649768][34542:34542] CHIP:DL: Got Ethernet interface: eth0
> [1652385557.650471][34542:34542] CHIP:DL: Found the primary Ethernet interface:eth0
> [1652385557.651172][34542:34542] CHIP:DL: Got WiFi interface: wlan0
> [1652385557.651256][34542:34542] CHIP:DL: Failed to reset WiFi statistic counts
> [1652385557.651344][34542:34542] CHIP:IN: UDP::Init bind&listen port=0
> [1652385557.651488][34542:34542] CHIP:IN: UDP::Init bound to port=45219
> [1652385557.651519][34542:34542] CHIP:IN: BLEBase::Init - setting/overriding transport
> [1652385557.651543][34542:34542] CHIP:IN: TransportMgr initialized
> [1652385557.651605][34542:34542] CHIP:DIS: Init fabric pairing table with server storage
> [1652385557.651936][34542:34542] CHIP:IN: Loading from storage for fabric index 0x1
> [1652385557.655385][34542:34542] CHIP:IN: Loading from storage for fabric index 0x2
> [1652385557.656658][34542:34542] CHIP:IN: Loading from storage for fabric index 0x3
> [1652385557.657874][34542:34542] CHIP:DIS: Add fabric pairing table delegate
> [1652385557.664710][34542:34542] CHIP:ZCL: Using ZAP configuration...
> [1652385557.668967][34542:34542] CHIP:DL: Avahi client registered
> [1652385557.670211][34542:34542] CHIP:CTL: System State Initialized...
> [1652385557.670299][34542:34542] CHIP:CTL: Setting attestation nonce to random value
> [1652385557.670388][34542:34542] CHIP:CTL: Setting CSR nonce to random value
> [1652385557.670515][34542:34542] CHIP:CTL: Setting attestation nonce to random value
> [1652385557.670565][34542:34542] CHIP:CTL: Setting CSR nonce to random value
> [1652385557.671490][34542:34542] CHIP:CTL: Generating NOC
> [1652385557.672461][34542:34542] CHIP:DIS: Verifying the received credentials
> [1652385557.674905][34542:34542] CHIP:DIS: Added new fabric at index: 0x1, Initialized: 1
> [1652385557.674956][34542:34542] CHIP:DIS: Assigned compressed fabric ID: 0x01E738535DD7208F, node ID: 0x000000000001B669
> [1652385557.674989][34542:34542] CHIP:CTL: Joined the fabric at index 1. Compressed fabric ID is: 0x01E738535DD7208F
> [1652385557.675098][34542:34542] CHIP:CTL: Setting attestation nonce to random value
> [1652385557.675180][34542:34542] CHIP:CTL: Setting CSR nonce to random value
> [1652385557.676304][34542:34542] CHIP:CTL: Generating NOC
> [1652385557.677522][34542:34542] CHIP:DIS: Verifying the received credentials
> [1652385557.680101][34542:34542] CHIP:DIS: Added new fabric at index: 0x2, Initialized: 1
> [1652385557.680155][34542:34542] CHIP:DIS: Assigned compressed fabric ID: 0x4D808C102B78AC41, node ID: 0x000000000001B669
> [1652385557.680190][34542:34542] CHIP:CTL: Joined the fabric at index 2. Compressed fabric ID is: 0x4D808C102B78AC41
> [1652385557.680293][34542:34542] CHIP:CTL: Setting attestation nonce to random value
> [1652385557.680375][34542:34542] CHIP:CTL: Setting CSR nonce to random value
> [1652385557.681503][34542:34542] CHIP:CTL: Generating NOC
> [1652385557.682917][34542:34542] CHIP:DIS: Verifying the received credentials
> [1652385557.684699][34542:34542] CHIP:DIS: Added new fabric at index: 0x3, Initialized: 1
> [1652385557.684736][34542:34542] CHIP:DIS: Assigned compressed fabric ID: 0xA5A256CC44153F13, node ID: 0x000000000001B669
> [1652385557.684760][34542:34542] CHIP:CTL: Joined the fabric at index 3. Compressed fabric ID is: 0xA5A256CC44153F13
> [1652385557.764727][34542:34547] CHIP:DL: CHIP task running
> [1652385557.764958][34542:34547] CHIP:DL: HandlePlatformSpecificBLEEvent 32787
> [1652385557.764992][34542:34547] CHIP:TOO: Sending command to node 0xbc5c01
> [1652385557.765027][34542:34547] CHIP:CSM: FindOrEstablishSession: PeerId = 01E738535DD7208F:0000000000BC5C01
> [1652385557.765054][34542:34547] CHIP:CSM: FindOrEstablishSession: No existing OperationalDeviceProxy instance found
> [1652385557.765097][34542:34547] CHIP:DIS: Resolving 01E738535DD7208F:0000000000BC5C01 ...
> [1652385557.766989][34542:34547] CHIP:DL: Avahi resolve found
> [1652385557.767071][34542:34547] CHIP:DIS: Node ID resolved for 01E738535DD7208F:0000000000BC5C01
> [1652385557.767104][34542:34547] CHIP:DIS:     Addr 0: [2601:1c0:4701:53b0:c6ac:59ff:fe9c:6454]:5540
> [1652385557.768006][34542:34547] CHIP:DIS: Lookup clearing interface for non LL address
> [1652385557.768043][34542:34547] CHIP:DIS: UDP:[2601:1c0:4701:53b0:c6ac:59ff:fe9c:6454%eth0]:5540: new best score: 7
> [1652385557.768067][34542:34547] CHIP:DIS: Checking node lookup status after 3 ms
> [1652385557.768089][34542:34547] CHIP:DIS: Keeping DNSSD lookup active
> [1652385557.965480][34542:34547] CHIP:DIS: Checking node lookup status after 201 ms
> [1652385557.965599][34542:34547] CHIP:CTL: Updating device address to UDP:[2601:1c0:4701:53b0:c6ac:59ff:fe9c:6454]:5540 while in state 1
> [1652385557.965656][34542:34547] CHIP:CTL: OperationalDeviceProxy[01E738535DD7208F:0000000000BC5C01]: State change 1 --> 2
> [1652385557.966085][34542:34547] CHIP:SC: Initiating session on local FabricIndex 1 from 0x000000000001B669 -> 0x0000000000BC5C01
> [1652385557.968220][34542:34547] CHIP:SC: Including MRP parameters
> [1652385557.968989][34542:34547] CHIP:IN: Prepared unauthenticated message 0xaaaad7bced08 to 0x0000000000000000 (0)  of type 0x30 and protocolId (0, 0) on exchange 23458i with MessageCounter:2334500426.
> [1652385557.969095][34542:34547] CHIP:IN: Sending unauthenticated msg 0xaaaad7bced08 with MessageCounter:2334500426 to 0x0000000000000000 at monotonic time: 000000000447263E msec
> [1652385557.969518][34542:34547] CHIP:SC: Sent Sigma1 msg
> [1652385557.969589][34542:34547] CHIP:CTL: OperationalDeviceProxy[01E738535DD7208F:0000000000BC5C01]: State change 2 --> 3
> [1652385557.969654][34542:34547] CHIP:DIS: Discovery does not require any more timeouts
> [1652385558.130409][34542:34547] CHIP:EM: Received message of type 0x33 with protocolId (0, 0) and MessageCounter:1619303474 on exchange 23458i
> [1652385558.130470][34542:34547] CHIP:EM: Found matching exchange: 23458i, Delegate: 0xffff6c001180
> [1652385558.130517][34542:34547] CHIP:EM: Rxd Ack; Removing MessageCounter:2334500426 from Retrans Table on exchange 23458i
> [1652385558.130541][34542:34547] CHIP:EM: Removed CHIP MessageCounter:2334500426 from RetransTable on exchange 23458i
> [1652385558.130580][34542:34547] CHIP:SC: Received Sigma2Resume msg
> [1652385558.130677][34542:34547] CHIP:SC: Found MRP parameters in the message
> [1652385558.130726][34542:34547] CHIP:SC: Peer assigned session session ID 64530
> [1652385558.131898][34542:34547] CHIP:SC: Unable to delete session resumption link for node 0000000000BC5C01: ../../examples/chip-tool/config/PersistentStorage.cpp:140: CHIP Error 0x000000A0: Value not found in the persisted storage
> [1652385558.153292][34542:34547] CHIP:SC: Sending status report. Protocol code 0, exchange 23458
> [1652385558.153361][34542:34547] CHIP:EM: Piggybacking Ack for MessageCounter:1619303474 on exchange: 23458i
> [1652385558.153408][34542:34547] CHIP:IN: Prepared unauthenticated message 0xaaaad7bced08 to 0x0000000000000000 (0)  of type 0x40 and protocolId (0, 0) on exchange 23458i with MessageCounter:2334500427.
> [1652385558.153454][34542:34547] CHIP:IN: Sending unauthenticated msg 0xaaaad7bced08 with MessageCounter:2334500427 to 0x0000000000000000 at monotonic time: 00000000044726F7 msec
> [1652385558.153754][34542:34547] CHIP:IN: New secure session created for device <0000000000BC5C01, 1>, LSID:3617 PSID:64530!
> [1652385558.153793][34542:34547] CHIP:CTL: OperationalDeviceProxy[01E738535DD7208F:0000000000BC5C01]: State change 3 --> 4
> [1652385558.153848][34542:34547] CHIP:TOO: Sending SubscribeEvent to:
> [1652385558.153873][34542:34547] CHIP:TOO:      cluster 0x0000_002F, event: 0x0000_0000, endpoint 1
> [1652385558.154022][34542:34547] CHIP:IN: Prepared secure message 0xaaaad7bced28 to 0x0000000000BC5C01 (1)  of type 0x3 and protocolId (0, 1) on exchange 23459i with MessageCounter:12296355.
> [1652385558.154061][34542:34547] CHIP:IN: Sending encrypted msg 0xaaaad7bced28 with MessageCounter:12296355 to 0x0000000000BC5C01 (1) at monotonic time: 00000000044726F7 msec
> [1652385558.154199][34542:34547] CHIP:DMG: MoveToState ReadClient[0xffff6c009040]: Moving to [AwaitingIn]
> [1652385558.241571][34542:34547] CHIP:EM: Received message of type 0x10 with protocolId (0, 0) and MessageCounter:1619303475 on exchange 23458i
> [1652385558.241670][34542:34547] CHIP:EM: Found matching exchange: 23458i, Delegate: (nil)
> [1652385558.241774][34542:34547] CHIP:EM: Rxd Ack; Removing MessageCounter:2334500427 from Retrans Table on exchange 23458i
> [1652385558.241834][34542:34547] CHIP:EM: Removed CHIP MessageCounter:2334500427 from RetransTable on exchange 23458i
> [1652385558.328143][34542:34547] CHIP:EM: Received message of type 0x5 with protocolId (0, 1) and MessageCounter:1544731 on exchange 23459i
> [1652385558.328222][34542:34547] CHIP:EM: Found matching exchange: 23459i, Delegate: 0xffff6c009040
> [1652385558.328369][34542:34547] CHIP:EM: Rxd Ack; Removing MessageCounter:12296355 from Retrans Table on exchange 23459i
> [1652385558.328410][34542:34547] CHIP:EM: Removed CHIP MessageCounter:12296355 from RetransTable on exchange 23459i
> [1652385558.328498][34542:34547] CHIP:DMG: ReportDataMessage =
> [1652385558.328544][34542:34547] CHIP:DMG: {
> [1652385558.328611][34542:34547] CHIP:DMG:      SubscriptionId = 0x43ef536f35ea477b,
> [1652385558.328654][34542:34547] CHIP:DMG:      InteractionModelRevision = 1
> [1652385558.328693][34542:34547] CHIP:DMG: }
> [1652385558.328771][34542:34547] CHIP:DMG: MoveToState ReadClient[0xffff6c009040]: Moving to [AwaitingSu]
> [1652385558.328866][34542:34547] CHIP:EM: Piggybacking Ack for MessageCounter:1544731 on exchange: 23459i
> [1652385558.328963][34542:34547] CHIP:IN: Prepared secure message 0xaaaad7bced08 to 0x0000000000BC5C01 (1)  of type 0x1 and protocolId (0, 1) on exchange 23459i with MessageCounter:12296356.
> [1652385558.329041][34542:34547] CHIP:IN: Sending encrypted msg 0xaaaad7bced08 with MessageCounter:12296356 to 0x0000000000BC5C01 (1) at monotonic time: 00000000044727A6 msec
> [1652385558.419550][34542:34547] CHIP:EM: Received message of type 0x4 with protocolId (0, 1) and MessageCounter:1544732 on exchange 23459i
> [1652385558.419609][34542:34547] CHIP:EM: Found matching exchange: 23459i, Delegate: 0xffff6c009040
> [1652385558.419656][34542:34547] CHIP:EM: Rxd Ack; Removing MessageCounter:12296356 from Retrans Table on exchange 23459i
> [1652385558.419680][34542:34547] CHIP:EM: Removed CHIP MessageCounter:12296356 from RetransTable on exchange 23459i
> [1652385558.419737][34542:34547] CHIP:DMG: SubscribeResponseMessage =
> [1652385558.419763][34542:34547] CHIP:DMG: {
> [1652385558.419787][34542:34547] CHIP:DMG:      SubscriptionId = 0x43ef536f35ea477b,
> [1652385558.419813][34542:34547] CHIP:DMG:      MinIntervalFloorSeconds = 0x78,
> [1652385558.419857][34542:34547] CHIP:DMG:      MaxIntervalCeilingSeconds = 0xe10,
> [1652385558.419882][34542:34547] CHIP:DMG:      InteractionModelRevision = 1
> [1652385558.419905][34542:34547] CHIP:DMG: }
> [1652385558.419944][34542:34547] CHIP:DMG: Subscription established with SubscriptionID = 0x43EF536F35EA477B MinInterval = 120s MaxInterval = 3600s Peer = 01:0000000000BC5C01
> [1652385558.419973][34542:34547] CHIP:DMG: MoveToState ReadClient[0xffff6c009040]: Moving to [Subscripti]
> [1652385558.420012][34542:34547] CHIP:DMG: Refresh LivenessCheckTime for 3620000 milliseconds with SubscriptionId = 0x43EF536F35EA477B Peer = 01:0000000000BC5C01
> [1652385558.420050][34542:34547] CHIP:EM: Sending Standalone Ack for MessageCounter:1544732 on exchange 23459i
> [1652385558.420117][34542:34547] CHIP:IN: Prepared secure message 0xffff81125968 to 0x0000000000BC5C01 (1)  of type 0x10 and protocolId (0, 0) on exchange 23459i with MessageCounter:12296357.
> [1652385558.420161][34542:34547] CHIP:IN: Sending encrypted msg 0xffff81125968 with MessageCounter:12296357 to 0x0000000000BC5C01 (1) at monotonic time: 0000000004472801 msec
> [1652385558.420291][34542:34547] CHIP:EM: Flushed pending ack for MessageCounter:1544732 on exchange 23459i
> [1652385587.765216][34542:34542] CHIP:CTL: Shutting down the commissioner
> [1652385587.765305][34542:34542] CHIP:CTL: Shutting down the controller
> [1652385587.765363][34542:34542] CHIP:CTL: Shutting down the commissioner
> [1652385587.765412][34542:34542] CHIP:CTL: Shutting down the controller
> [1652385587.765472][34542:34542] CHIP:IN: Expiring all connections for fabric 1!!
> [1652385587.765560][34542:34542] CHIP:CTL: Shutting down the commissioner
> [1652385587.765613][34542:34542] CHIP:CTL: Shutting down the controller
> [1652385587.765658][34542:34542] CHIP:IN: Expiring all connections for fabric 2!!
> [1652385587.765727][34542:34542] CHIP:CTL: Shutting down the commissioner
> [1652385587.765775][34542:34542] CHIP:CTL: Shutting down the controller
> [1652385587.765818][34542:34542] CHIP:IN: Expiring all connections for fabric 3!!
> [1652385587.765878][34542:34542] CHIP:CTL: Shutting down the System State, this will teardown the CHIP Stack
> [1652385587.767634][34542:34542] CHIP:DMG: IM WH moving to [Uninitialized]
> [1652385587.767703][34542:34542] CHIP:DMG: IM WH moving to [Uninitialized]
> [1652385587.767746][34542:34542] CHIP:DMG: IM WH moving to [Uninitialized]
> [1652385587.767788][34542:34542] CHIP:DMG: IM WH moving to [Uninitialized]
> [1652385587.767833][34542:34542] CHIP:DMG: All ReadHandler-s are clean, clear GlobalDirtySet
> [1652385587.767959][34542:34542] CHIP:BLE: BleConnectionDelegate::CancelConnection is not implemented.
> [1652385587.768403][34542:34542] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-h0uiVs)
> [1652385587.769574][34542:34542] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
> [1652385587.769697][34542:34542] CHIP:DL: NVS set: chip-counters/total-operational-hours = 0 (0x0)
> [1652385587.769752][34542:34542] CHIP:DL: Inet Layer shutdown
> [1652385587.769797][34542:34542] CHIP:DL: BLE shutdown
> [1652385587.769843][34542:34542] CHIP:DL: System Layer shutdown
> [1652385587.770065][34542:34542] CHIP:TOO: Run command failure: ../../examples/chip-tool/commands/common/CHIPCommand.cpp:392: CHIP Error 0x00000032: Timeout
> Segmentation fault (core dumped)

 #### Proposed Solution
Need investigation of the root cause of the segmentation fault.

**Comment by isiu-apple** [comment] 2022-05-19 23:38
For event subscriptions, try running chiptool in interactive mode:

```
chip-tool interactive start
chip-tool powersource subscribe-event-by-id 0 120 3600 12344321 1
```

**Comment by andy31415** [comment] 2022-05-20 13:03
Segfault is likely unclear shutdown due to timeout

**Comment by bzbarsky-apple** [comment] 2022-05-21 06:06
@ifyall Is this reproducible on ToT?  I just tried running that command and I am not seeing a segfault...

**Comment by bzbarsky-apple** [comment] 2022-05-25 03:37
@cjandhyala You added the "cert blocker" label, but is this reproducible?

**Comment by andy31415** [comment] 2022-05-25 14:54
assigning this to @cjandhyala - need ToT reproduction steps (since Boris tried and it did not reproduce) or closing.

@ifyall could you also add info regarding setup:
   - what platforms was the command run on
   - how often does it reproduce
   - if you are able to re-run it quickly enough, can you test on ToT on your environment?
   
 We also now have a doc: https://github.com/project-chip/connectedhomeip/blob/master/docs/BUG_REPORT.md . It generally asks for platform info and also asks for logs to be provided as attachments (and only curated subsets being inline) to avoid making the issue description too large.

**Comment by billwatersiii** [comment] 2022-05-27 21:28
I do not see the Segmentation fault on the ToT.

@ifyall, I guess we can close this with a "can not reproduce" or "it just went away".

**Closed** 2022-05-27 21:39 UTC
Labels: V1.0, cert blocker
