### ISSUE TITLE
[CERT-TEST-FAILURE]  - TC-TCTL-3.2 - Test failed

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27786] opened 2023-07-07 09:39 UTC
### Feature Area

Area:Refrigerators

### Test Case

TC-TCTL-3.2

### Summary

**All-clusters-app has to be enabled with below mentioned Attribute :**

- [ ] TemperatureSetpoint

**All-clusters-app has to be enabled with below mentioned Attributes :**

- [ ] SetTemperature

### GitHub hash of the SDK that was being used

40fb7c246671e9d37ca8bb2cfbf37f81c1509334

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

**Comment by jadhavrohit924** [comment] 2023-07-19 09:22
Duplicate of #27782 . `SetTemperature` enabled with [701fcb2](https://github.com/project-chip/connectedhomeip/commit/701fcb21f9a1bc4c7792c6e0709a3c74101fa6f5)

**Closed by jadhavrohit924** 2023-07-19 09:22 UTC
Labels: examples, spec, cert blocker, refrigerators
