### ISSUE TITLE
[TC-DGGEN-2.1] & [TC-DGGEN-3.1]  -General Diagnostics-chip-tool needs to implement mandatory TestEventTriggersEnabled attribute.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#18751] opened 2022-05-24 12:10 UTC
#### Problem
[TC-DGGEN-2.1]-General Diagnostics-chip-tool needs to implement mandatory TestEventTriggersEnabled attribute.
 
**PFA screenshot below:-**
![image](https://user-images.githubusercontent.com/95841834/170030475-58e9898f-4d51-4d16-bf56-b33658bcef01.png)

**Test-Plan screenshot:-**
![image](https://user-images.githubusercontent.com/95841834/170030633-ebd6883d-1612-4b33-b22e-5d79f4ecfc71.png)

Spec screenshot:-
![image](https://user-images.githubusercontent.com/95841834/170030911-00eb5df7-152a-4ea8-a0ae-d6a161cb91c3.png)

**Comment by Rajashreekalmane** [comment] 2022-05-24 12:30
[https://github.com/CHIP-Specifications/chip-test-plans/issues/1335](url)

**Comment by bzbarsky-apple** [comment] 2022-05-25 01:44
Duplicate of https://github.com/project-chip/connectedhomeip/issues/18322

**Closed by bzbarsky-apple** 2022-05-25 01:44 UTC
Labels: cert blocker
