### ISSUE TITLE
[TC-LO-2.1]- While verifying SupportedLocales attribute to write chip-tool throws an error 0x87(CONSTRAINT_ERROR) instead 0x88(UNSUPPORTED_WRITE(0x88)

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#16614] opened 2022-03-24 12:03 UTC
#### Problem
[TC-LO-2.1]- While verifying SupportedLocales attribute to write chip-tool throws an error 0x87(CONSTRAINT_ERROR) instead 0x88(UNSUPPORTED_WRITE(0x88) 

 * expected behavior:-UNSUPPORTED_WRITE(0x88)
 * actual behavior:- CONSTRAINT_ERROR(0x87)

 * steps to reproduce:- sudo ./chip-tool any write-by-id 0x002B 1 newsupportedlocales 3 0

system configuration
Chip-Tool: RPI
DUT: RPI
Platform : IP and Wifi
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/20e1a4a705770d5222a8ebf04e12ab2ce0304df6
Dut: All-Clusters-app

 *PFA screenshot below:-
[TC-LO-2.1.txt](https://github.com/project-chip/connectedhomeip/files/8487686/TC-LO-2.1.txt)

Test-Plan Reference:-
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/cluster/Localization.adoc#tc-lo-2-1localization-configuration-cluster-attributes

**Comment by yufengwangca** [comment] 2022-04-07 22:40
This is because this attribute is not writable

 <attribute side="server" code="0x02" define="SUPPORTED_LOCALES" type="ARRAY" entryType="CHAR_STRING" length="254" writable="false" optional="false">SupportedLocales</attribute>

**Comment by cjandhyala** [comment] 2022-04-08 01:02
@yufengwangca The error code we were supposed to get is "UNSUPPORTED_WRITE(0x88)" , instead we are getting "CONSTRAINT_ERROR(0x87)"

**Comment by andy31415** [comment] 2022-05-13 13:22
Seems like the same as #17598

**Comment by vivien-apple** [comment] 2022-05-18 16:40
It happens because the code is going thought some old ember code path at Failed to prepare data to write: ../../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/app/util/ember-compatibility-functions.cpp:866: CHIP Error 0x0000002F: Invalid argument

For some reason I can not reproduce while trying with #18561 (which is itself on top of https://github.com/project-chip/connectedhomeip/issues/17633)
I will wait for those to land and see if that still happens. There is no reason that this attributes goes into our compatibility layer..

**Comment by vivien-apple** [comment] 2022-05-18 19:10
Ok... Now I know why it was working with https://github.com/project-chip/connectedhomeip/pull/18561.
The command used in the description is assuming that "SupportedLocales" have the correct attribute id per spec. It does not currently as mentioned in #17633 and if the command is updated to represent that so it becomes `chip-tool any write-by-id 0x002B 2 newsupportedlocales 3 0` then `UNSUPPORTED_WRITE` is received.

Closing since the real issue is #17633.

**Closed by vivien-apple** 2022-05-18 19:10 UTC
Labels: V1.0, spec, cert, cert blocker
