### ISSUE TITLE
Missing Attributes inTestplan and TE_7_5

### ISSUE THREAD

**Issue by somu1710** [project-chip/connectedhomeip#13266] opened 2021-12-29 05:54 UTC
#### Problem
<what's wrong or missing, please include any applicable:
 * expected behavior
 * actual behavior
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by Survensa** [comment] 2021-12-29 06:54
Duplicate of #

**Closed** 2021-12-29 06:55 UTC
