### ISSUE TITLE
[CERT-TEST-FAILURE]  - TC-DISHMS-3.3 - Test failed

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#27789] opened 2023-07-07 09:47 UTC
### Feature Area

Area:Dishwashers

### Test Case

TC-DISHMS-3.3

### Summary

All-clusters-app has to be enabled with below mentioned attributes :

- [ ]  supported-modes
- [ ]  current-mode
- [ ]  start-up-mode
- [ ]  on-mode

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

d55f68526864b2986404d1da9c2ccd8b64735b6e - master

### Platform

raspi

### Platform Version(s)

RPI4 8GB RAM

**Comment by bzbarsky-apple** [comment] 2023-07-07 15:46
Duplicate of https://github.com/project-chip/connectedhomeip/issues/27705

**Closed** 2023-07-25 05:31 UTC
Labels: bug, examples, cert blocker, needs triage, dishwashers
