### ISSUE TITLE
[Feature] Soft -AP Discovery and Provisioning

### ISSUE THREAD

**Issue by JonathanWitthoeft** [project-chip/connectedhomeip#27420] opened 2023-06-22 20:12 UTC
### Feature description

Only BLE transport is fully supported for provisioning to a Wi-Fi network. When can we expect a Matter controller application that will actually discover and provision Wi-Fi only Matter devices? 

All previous issues asking for this have been closed with little to no feedback.

### Platform

all

**Comment by woody-apple** [comment] 2023-06-23 01:04
This is tracked here: https://github.com/project-chip/connectedhomeip/issues/17487, closing as a duplicate of this. 

That said, I can't speak as to future specifications, or timeframes. If you're interested in joining the conversation around future specifications please check out https://csa-iot.org/all-solutions/matter/ with information about how to join the CSA!

**Closed by woody-apple** 2023-06-23 01:04 UTC
Labels: feature work, feature request, needs triage
