### ISSUE TITLE
[TC-PSCFG-1.1] Attribute list showing value mismatch error

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#17970] opened 2022-05-02 19:28 UTC
Summary:
As per testplan of TC-PSCFG-1.1 attributelist exepected value value: [0, 65528, 65529, 65530, 65531, 65532, 65533] but got 
value: [0, 65528, 65529, 65531, 65532, 65533] mandatory attribute 65530 is missing
 
Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/166311988-af65cd87-a15e-447a-b694-3d81be988ccb.png)

Execution logs:
[PSCFG_1_1_AL.txt](https://github.com/project-chip/connectedhomeip/files/8605584/PSCFG_1_1_AL.txt)
![PSCFG_1_1AL](https://user-images.githubusercontent.com/102359958/166312446-7a61147e-1426-422d-b469-20343cc54bdf.png)

**Comment by bzbarsky-apple** [comment] 2022-05-21 08:02
65530 == 0xfffa is EventList.

**Comment by bzbarsky-apple** [comment] 2022-05-21 08:03
Duplicate of #15011

**Closed by bzbarsky-apple** 2022-05-21 08:02 UTC
