### ISSUE TITLE
Darwin Build Failure

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#32836] opened 2024-04-03 22:19 UTC

**Comment by woody-apple** [comment] 2024-04-03 22:19
https://github.com/project-chip/connectedhomeip/actions/runs/8541055337/job/23399517563?pr=32752

**Comment by bzbarsky-apple** [comment] 2024-04-05 19:23
This is failing in TestDiagnosticLogsDownloadCommand.

Duplicate of https://github.com/project-chip/connectedhomeip/issues/32636

**Closed by bzbarsky-apple** 2024-04-05 19:23 UTC
Labels: build issue, darwin
