### ISSUE TITLE
Implement Bulk Data Exchange Protocol

### ISSUE THREAD

**Issue by yufengwangca** [project-chip/connectedhomeip#3103] opened 2020-10-07 03:26 UTC
#### Problem
Bulk Data Exchange Protocol has been agreed in SCTT, which defines messages and protocol for the reliable block transfer of arbitrary data. Current plan is to implement BDX as a CHIP protocol along side Interaction Model protocol and Secure Channel Protocol.

 #### Proposed Solution
Implement Bulk Data Exchange Protocol in CHIP stack.

@woody-apple @pan-apple @andy31415 @robszewczyk

**Comment by woody-apple** [comment] 2020-10-21 23:20
Duplicate of: https://github.com/project-chip/connectedhomeip/issues/1816

**Closed by woody-apple** 2020-10-21 23:20 UTC
Labels: feature_request, message_layer_integration
