### ISSUE TITLE
Builds occasionally failing due to MRP test

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#17014] opened 2022-04-04 19:23 UTC
#### Problem
MRP is failing intermittently on Darwin and Linux:
```
[1649097260.205425][32700:32700] CHIP:EM: Handling via exchange: 13826r, Delegate: 0x7ffd2ad8d180
[2278](https://github.com/project-chip/connectedhomeip/runs/5821352173?check_suite_focus=true#step:8:2278)
[1649097260.205431][32700:32700] CHIP:EM: OnMessageReceived failed, err = ../src/messaging/ExchangeMgr.cpp:296: Error 0x0000002A
[2279](https://github.com/project-chip/connectedhomeip/runs/5821352173?check_suite_focus=true#step:8:2279)
'#3:','Test that unencrypted message is dropped if exchange requires encryption                                         ','PASSED'
[2280](https://github.com/project-chip/connectedhomeip/runs/5821352173?check_suite_focus=true#step:8:2280)
'#1:','Initialize                                                                                                       ','PASSED'
[2281](https://github.com/project-chip/connectedhomeip/runs/5821352173?check_suite_focus=true#step:8:2281)
```

Example here:
https://github.com/project-chip/connectedhomeip/runs/5821352173?check_suite_focus=true

 #### Proposed Solution
Fix

**Comment by bzbarsky-apple** [comment] 2022-04-04 19:34
Duplicate of https://github.com/project-chip/connectedhomeip/issues/16912

**Closed by bzbarsky-apple** 2022-04-04 19:34 UTC
Labels: build issue, V1.0
