### ISSUE TITLE
5675): This code is temporary, and must be updated to use the IM API. Currently, we use a temporary Protocol

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14061] opened 2022-01-25 08:09 UTC
TempZCL to carry over legacy ZCL messages, use an ephemeral exchange to send message and use its unsolicited message handler to receive messages. We need to set flag kFromInitiator to allow receiver to deliver message to corresponding unsolicited message handler, and we also need to set flag kNoAutoRequestAck since there is no persistent exchange to receive the ack message. This logic needs to be deleted after we convert all legacy ZCL messages to IM messages.

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/util/chip-message-send.cpp#L119-L124

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by harimau-qirex** [comment] 2022-01-31 21:34
Appears to be a duplicate of #5675.

**Closed by harimau-qirex** 2022-01-31 21:34 UTC
Labels: V1.0, todo :spiral_notepad:, v1_triage_split_11
