### ISSUE TITLE
event notification for newly created ACL entry

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14285] opened 2022-01-26 02:03 UTC
false

---

https://github.com/project-chip/connectedhomeip/blob/1202bc79f8a53c0b1515851bae0b9e295c2b79fc/src/app/clusters/operational-credentials-server/operational-credentials-server.cpp#L76-L81

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in 1202bc79f8a53c0b1515851bae0b9e295c2b79fc.

**Comment by mlepage-google** [comment] 2022-01-27 21:25
This is already tracked by #14326, what do I do with this issue, can we close it?

**Comment by harimau-qirex** [comment] 2022-01-31 21:36
Duplicate of #14326.

**Closed by harimau-qirex** 2022-01-31 21:36 UTC
Labels: V1.0, acl, todo :spiral_notepad:, v1_triage_split_11

**Comment by mlepage-google** [comment] 2022-01-31 22:52
Yes, duplicate, thanks. And I just tested this in the REPL, it is working on master.
