### ISSUE TITLE
TE7.5 [TC-IDM-5.2]CHIP:SPT: VerifyOrDie failure at ../../examples/chip-tool/third_party/connectedhomeip/src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0 Aborted (core dumped)

### ISSUE THREAD

**Issue by nanmu2018** [project-chip/connectedhomeip#14482] opened 2022-01-28 07:01 UTC
Problem：
[TC-IDM-5.2] CHIP:SPT: VerifyOrDie failure at ../../examples/chip-tool/third_party/connectedhomeip/src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0
Aborted (core dumped)

platform:
Testing image on RasPi：v1.7.img
Connectedhomeip commitID : b0af6ba
OTBR commitID：72bb3d45684f837e67e7f1ec20a9a8e3ac4a4419
lighting-app run on the EFR32MG24 board base on commitID : b0af6ba

```
ubuntu@matter-7-5:~/connectedhomeip/out/standalone$ ./chip-tool basic  mfg-specific-ping  12344321 1   --commissioner-name  alpha  --timedInteractionTimeoutMs   -200
[1643351007.436518][3699:3699] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-utN8OD)
[1643351007.437242][3699:3699] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1643351007.437301][3699:3699] CHIP:DL: NVS set: chip-counters/reboot-count = 7 (0x7)
[1643351007.438267][3699:3699] CHIP:DL: Got Ethernet interface: eth0
[1643351007.439021][3699:3699] CHIP:DL: Found the primary Ethernet interface:eth0
[1643351007.439746][3699:3699] CHIP:DL: Got WiFi interface: wlan0
[1643351007.439826][3699:3699] CHIP:DL: Failed to reset WiFi statistic counts
[1643351007.439903][3699:3699] CHIP:IN: UDP::Init bind&listen port=5542
[1643351007.440028][3699:3699] CHIP:IN: UDP::Init bound to port=5542
[1643351007.440059][3699:3699] CHIP:IN: UDP::Init bind&listen port=5542
[1643351007.440164][3699:3699] CHIP:IN: UDP::Init bound to port=5542
[1643351007.440194][3699:3699] CHIP:IN: TransportMgr initialized
[1643351007.440237][3699:3699] CHIP:DIS: Init fabric pairing table with server storage
[1643351007.440542][3699:3699] CHIP:DL: writing settings to file (/tmp/chip_counters.ini-Udqb7e)
[1643351007.441171][3699:3699] CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
[1643351007.441229][3699:3699] CHIP:DL: NVS set: chip-counters/GlobalMCTR = 7000 (0x1B58)
[1643351007.441361][3699:3699] CHIP:ZCL: Using ZAP configuration...
[1643351007.444842][3699:3699] CHIP:DL: MDNS failed to join multicast group on wlan0 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643351007.452390][3699:3699] CHIP:DL: MDNS failed to join multicast group on vethda6fe02 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643351007.454312][3699:3699] CHIP:DL: MDNS failed to join multicast group on vethd1a29ba for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643351007.456148][3699:3699] CHIP:DL: MDNS failed to join multicast group on veth6fb6734 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643351007.458102][3699:3699] CHIP:DL: MDNS failed to join multicast group on wpan0 for address type IPv4: ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:772: Inet Error 0x00000110: Address not found
[1643351007.458448][3699:3699] CHIP:CTL: System State Initialized...
[1643351007.461157][3699:3699] CHIP:CTL: Generating NOC
[1643351007.461658][3699:3699] CHIP:CTL: Generating ICAC
[1643351007.462457][3699:3699] CHIP:DIS: Verifying the received credentials
[1643351007.464212][3699:3699] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000001 and root pubkey
[1643351007.464250][3699:3699] CHIP:IN: 0x04, 0x25, 0xeb, 0x71, 0x73, 0xbf, 0x52, 0x2a,
[1643351007.464275][3699:3699] CHIP:IN: 0xda, 0x7a, 0x50, 0x2c, 0x64, 0x98, 0x7c, 0x8a,
[1643351007.464298][3699:3699] CHIP:IN: 0xb4, 0x3a, 0xe0, 0x4b, 0xbf, 0xcc, 0xed, 0xe2,
[1643351007.464321][3699:3699] CHIP:IN: 0x28, 0xef, 0x87, 0xab, 0xcf, 0x10, 0xc4, 0x45,
[1643351007.464344][3699:3699] CHIP:IN: 0x5d, 0x50, 0xbf, 0xed, 0xff, 0x62, 0xe9, 0x87,
[1643351007.464366][3699:3699] CHIP:IN: 0xf6, 0xac, 0x90, 0x2d, 0x2c, 0x49, 0x6d, 0x6d,
[1643351007.464388][3699:3699] CHIP:IN: 0x93, 0x7e, 0xc6, 0xb4, 0x18, 0x65, 0x90, 0xe2,
[1643351007.464411][3699:3699] CHIP:IN: 0x2c, 0x80, 0xe1, 0x25, 0x5c, 0xb7, 0xfc, 0x0e,
[1643351007.464431][3699:3699] CHIP:IN: 0x3d,
[1643351007.464485][3699:3699] CHIP:IN: Generated compressed fabric ID
[1643351007.464511][3699:3699] CHIP:IN: 0x56, 0x97, 0xd4, 0x7a, 0x18, 0xde, 0x2e, 0x34,
[1643351007.464542][3699:3699] CHIP:DIS: Added new fabric at index: 1, Initialized: 1
[1643351007.464564][3699:3699] CHIP:DIS: Assigned compressed fabric ID: 0x5697D47A18DE2E34, node ID: 0x000000000001B669
[1643351007.464587][3699:3699] CHIP:CTL: Joined the fabric at index 1. Compressed fabric ID is: 0x5697D47A18DE2E34
[1643351007.464654][3699:3699] CHIP:IN: UDP::Init bind&listen port=5550
[1643351007.464804][3699:3699] CHIP:IN: UDP::Init bound to port=5550
[1643351007.464831][3699:3699] CHIP:IN: UDP::Init bind&listen port=5550
[1643351007.464922][3699:3699] CHIP:IN: UDP::Init bound to port=5550
[1643351007.464946][3699:3699] CHIP:IN: TransportMgr initialized
[1643351007.466117][3699:3699] CHIP:CTL: Generating NOC
[1643351007.466433][3699:3699] CHIP:CTL: Generating ICAC
[1643351007.467151][3699:3699] CHIP:DIS: Verifying the received credentials
[1643351007.468880][3699:3699] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000002 and root pubkey
[1643351007.468919][3699:3699] CHIP:IN: 0x04, 0x25, 0xeb, 0x71, 0x73, 0xbf, 0x52, 0x2a,
[1643351007.468943][3699:3699] CHIP:IN: 0xda, 0x7a, 0x50, 0x2c, 0x64, 0x98, 0x7c, 0x8a,
[1643351007.468967][3699:3699] CHIP:IN: 0xb4, 0x3a, 0xe0, 0x4b, 0xbf, 0xcc, 0xed, 0xe2,
[1643351007.468989][3699:3699] CHIP:IN: 0x28, 0xef, 0x87, 0xab, 0xcf, 0x10, 0xc4, 0x45,
[1643351007.469012][3699:3699] CHIP:IN: 0x5d, 0x50, 0xbf, 0xed, 0xff, 0x62, 0xe9, 0x87,
[1643351007.469035][3699:3699] CHIP:IN: 0xf6, 0xac, 0x90, 0x2d, 0x2c, 0x49, 0x6d, 0x6d,
[1643351007.469057][3699:3699] CHIP:IN: 0x93, 0x7e, 0xc6, 0xb4, 0x18, 0x65, 0x90, 0xe2,
[1643351007.469079][3699:3699] CHIP:IN: 0x2c, 0x80, 0xe1, 0x25, 0x5c, 0xb7, 0xfc, 0x0e,
[1643351007.469100][3699:3699] CHIP:IN: 0x3d,
[1643351007.469153][3699:3699] CHIP:IN: Generated compressed fabric ID
[1643351007.469180][3699:3699] CHIP:IN: 0xf6, 0x4f, 0x0b, 0x6c, 0xc4, 0x1a, 0x70, 0x9e,
[1643351007.469209][3699:3699] CHIP:DIS: Added new fabric at index: 2, Initialized: 1
[1643351007.469233][3699:3699] CHIP:DIS: Assigned compressed fabric ID: 0xF64F0B6CC41A709E, node ID: 0x000000000001B669
[1643351007.469256][3699:3699] CHIP:CTL: Joined the fabric at index 2. Compressed fabric ID is: 0xF64F0B6CC41A709E
[1643351007.469320][3699:3699] CHIP:IN: UDP::Init bind&listen port=5550
[1643351007.470195][3699:3699] CHIP:IN: UDP::Init bound to port=5550
[1643351007.470257][3699:3699] CHIP:IN: UDP::Init bind&listen port=5550
[1643351007.470366][3699:3699] CHIP:IN: UDP::Init bound to port=5550
[1643351007.470398][3699:3699] CHIP:IN: TransportMgr initialized
[1643351007.471369][3699:3699] CHIP:CTL: Generating NOC
[1643351007.471702][3699:3699] CHIP:CTL: Generating ICAC
[1643351007.472471][3699:3699] CHIP:DIS: Verifying the received credentials
[1643351007.474340][3699:3699] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000003 and root pubkey
[1643351007.474386][3699:3699] CHIP:IN: 0x04, 0x25, 0xeb, 0x71, 0x73, 0xbf, 0x52, 0x2a,
[1643351007.474411][3699:3699] CHIP:IN: 0xda, 0x7a, 0x50, 0x2c, 0x64, 0x98, 0x7c, 0x8a,
[1643351007.474433][3699:3699] CHIP:IN: 0xb4, 0x3a, 0xe0, 0x4b, 0xbf, 0xcc, 0xed, 0xe2,
[1643351007.474456][3699:3699] CHIP:IN: 0x28, 0xef, 0x87, 0xab, 0xcf, 0x10, 0xc4, 0x45,
[1643351007.474479][3699:3699] CHIP:IN: 0x5d, 0x50, 0xbf, 0xed, 0xff, 0x62, 0xe9, 0x87,
[1643351007.474502][3699:3699] CHIP:IN: 0xf6, 0xac, 0x90, 0x2d, 0x2c, 0x49, 0x6d, 0x6d,
[1643351007.474525][3699:3699] CHIP:IN: 0x93, 0x7e, 0xc6, 0xb4, 0x18, 0x65, 0x90, 0xe2,
[1643351007.474547][3699:3699] CHIP:IN: 0x2c, 0x80, 0xe1, 0x25, 0x5c, 0xb7, 0xfc, 0x0e,
[1643351007.474567][3699:3699] CHIP:IN: 0x3d,
[1643351007.474625][3699:3699] CHIP:IN: Generated compressed fabric ID
[1643351007.474650][3699:3699] CHIP:IN: 0xed, 0xd9, 0x8a, 0xfc, 0xbd, 0x25, 0x4a, 0x40,
[1643351007.474681][3699:3699] CHIP:DIS: Added new fabric at index: 3, Initialized: 1
[1643351007.474705][3699:3699] CHIP:DIS: Assigned compressed fabric ID: 0xEDD98AFCBD254A40, node ID: 0x000000000001B669
[1643351007.474727][3699:3699] CHIP:CTL: Joined the fabric at index 3. Compressed fabric ID is: 0xEDD98AFCBD254A40
[1643351007.474819][3699:3699] CHIP:IN: UDP::Init bind&listen port=5550
[1643351007.474955][3699:3699] CHIP:IN: UDP::Init bound to port=5550
[1643351007.474983][3699:3699] CHIP:IN: UDP::Init bind&listen port=5550
[1643351007.475073][3699:3699] CHIP:IN: UDP::Init bound to port=5550
[1643351007.475098][3699:3699] CHIP:IN: TransportMgr initialized
[1643351007.475418][3699:3705] CHIP:DL: CHIP task running
[1643351007.475547][3699:3705] CHIP:TOO: Sending command to node 0xbc5c01
[1643351007.476207][3699:3705] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643351007.476964][3699:3705] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643351007.477136][3699:3705] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643351007.477289][3699:3705] CHIP:DIS: Attempt to mDNS broadcast failed:  ../../examples/chip-tool/third_party/connectedhomeip/src/inet/UDPEndPointImplSockets.cpp:417: OS Error 0x02000065: Network is unreachable
[1643351007.478213][3699:3705] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643351007.478266][3699:3705] CHIP:DIS:     Addr 0: [2001:db8::f4c1:3529:6091:9435]:5540
[1643351007.478289][3699:3705] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643351007.478947][3699:3705] CHIP:IN: Generating DestinationID. Fabric ID 0x0000000000000001, Dest node ID 0x0000000000BC5C01, Random data
[1643351007.478992][3699:3705] CHIP:IN: 0xff, 0x81, 0x41, 0xdd, 0xc3, 0xd2, 0x21, 0x53,
[1643351007.479019][3699:3705] CHIP:IN: 0x80, 0x8f, 0x09, 0x3e, 0xd1, 0xad, 0x6c, 0x10,
[1643351007.479044][3699:3705] CHIP:IN: 0xae, 0xac, 0xd2, 0x8e, 0x1c, 0x52, 0x2f, 0x23,
[1643351007.479068][3699:3705] CHIP:IN: 0x2f, 0x65, 0x78, 0xbc, 0x9a, 0xd0, 0x3e, 0x16,
[1643351007.479089][3699:3705] CHIP:IN: Root pubkey
[1643351007.479113][3699:3705] CHIP:IN: 0x04, 0x25, 0xeb, 0x71, 0x73, 0xbf, 0x52, 0x2a,
[1643351007.479136][3699:3705] CHIP:IN: 0xda, 0x7a, 0x50, 0x2c, 0x64, 0x98, 0x7c, 0x8a,
[1643351007.479160][3699:3705] CHIP:IN: 0xb4, 0x3a, 0xe0, 0x4b, 0xbf, 0xcc, 0xed, 0xe2,
[1643351007.479183][3699:3705] CHIP:IN: 0x28, 0xef, 0x87, 0xab, 0xcf, 0x10, 0xc4, 0x45,
[1643351007.479205][3699:3705] CHIP:IN: 0x5d, 0x50, 0xbf, 0xed, 0xff, 0x62, 0xe9, 0x87,
[1643351007.479228][3699:3705] CHIP:IN: 0xf6, 0xac, 0x90, 0x2d, 0x2c, 0x49, 0x6d, 0x6d,
[1643351007.479250][3699:3705] CHIP:IN: 0x93, 0x7e, 0xc6, 0xb4, 0x18, 0x65, 0x90, 0xe2,
[1643351007.479273][3699:3705] CHIP:IN: 0x2c, 0x80, 0xe1, 0x25, 0x5c, 0xb7, 0xfc, 0x0e,
[1643351007.479294][3699:3705] CHIP:IN: 0x3d,
[1643351007.479314][3699:3705] CHIP:IN: IPK
[1643351007.479337][3699:3705] CHIP:IN: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
[1643351007.479360][3699:3705] CHIP:IN: 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
[1643351007.479396][3699:3705] CHIP:IN: Generated DestinationID output
[1643351007.479422][3699:3705] CHIP:IN: 0xa5, 0x6e, 0xd3, 0x58, 0x7d, 0xac, 0xcd, 0x1b,
[1643351007.479445][3699:3705] CHIP:IN: 0xfa, 0xe9, 0x45, 0xc7, 0xcf, 0xf4, 0x7d, 0xe6,
[1643351007.479467][3699:3705] CHIP:IN: 0x3b, 0x01, 0x6a, 0xfe, 0x7a, 0x79, 0x7a, 0x31,
[1643351007.479490][3699:3705] CHIP:IN: 0x1d, 0x0b, 0x01, 0xdd, 0x86, 0x85, 0x3b, 0x86,
[1643351007.479514][3699:3705] CHIP:SC: Including MRP parameters
[1643351007.479582][3699:3705] CHIP:IN: Prepared plaintext message 0xaaaae5c18810 to 0x0000000000000000 (0)  of type 0x30 and protocolId (0, 0) on exchange 16646i with MessageCounter:3617776721.
[1643351007.479625][3699:3705] CHIP:IN: Sending plaintext msg 0xaaaae5c18810 with MessageCounter:3617776721 to 0x0000000000000000 at monotonic time: 4206122 msec
[1643351007.479772][3699:3705] CHIP:SC: Sent Sigma1 msg
[1643351007.479808][3699:3705] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643351007.480137][3699:3705] CHIP:DIS: Discovered node without a pending query
[1643351007.480166][3699:3705] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643351007.480192][3699:3705] CHIP:DIS:     Addr 0: [2001:db8::f4c1:3529:6091:9435]:5540
[1643351007.480215][3699:3705] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643351007.480245][3699:3705] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643351007.480394][3699:3705] CHIP:DIS: Discovered node without a pending query
[1643351007.480419][3699:3705] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643351007.480443][3699:3705] CHIP:DIS:     Addr 0: [2001:db8::f4c1:3529:6091:9435]:5540
[1643351007.480464][3699:3705] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643351007.480489][3699:3705] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643351007.480636][3699:3705] CHIP:DIS: Discovered node without a pending query
[1643351007.480660][3699:3705] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643351007.480683][3699:3705] CHIP:DIS:     Addr 0: [2001:db8::f4c1:3529:6091:9435]:5540
[1643351007.480704][3699:3705] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643351007.480730][3699:3705] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643351007.480877][3699:3705] CHIP:DIS: Discovered node without a pending query
[1643351007.480901][3699:3705] CHIP:DIS: Node ID resolved for 0x0000000000BC5C01
[1643351007.480924][3699:3705] CHIP:DIS:     Addr 0: [2001:db8::f4c1:3529:6091:9435]:5540
[1643351007.480945][3699:3705] CHIP:CTL: OperationalDiscoveryComplete for device ID 0x0000000000BC5C01
[1643351007.480970][3699:3705] CHIP:CTL: Address resolved for node: 0x0000000000BC5C01
[1643351009.451484][3699:3705] CHIP:EM: Received message of type 0x31 with protocolId (0, 0) and MessageCounter:2132135621 on exchange 16646i
[1643351009.451593][3699:3705] CHIP:EM: Found matching exchange: 16646i, Delegate: 0xffff809d7348
[1643351009.451756][3699:3705] CHIP:EM: Rxd Ack; Removing MessageCounter:3617776721 from Retrans Table on exchange 16646i
[1643351009.451882][3699:3705] CHIP:EM: Removed CHIP MessageCounter:3617776721 from RetransTable on exchange 16646i
[1643351009.452020][3699:3705] CHIP:SC: Received Sigma2 msg
[1643351009.452162][3699:3705] CHIP:SC: Peer assigned session session ID 6
[1643351009.455341][3699:3705] CHIP:IN: Generating compressed fabric ID using uncompressed fabric ID 0x0000000000000001 and root pubkey
[1643351009.455396][3699:3705] CHIP:IN: 0x04, 0x25, 0xeb, 0x71, 0x73, 0xbf, 0x52, 0x2a,
[1643351009.455427][3699:3705] CHIP:IN: 0xda, 0x7a, 0x50, 0x2c, 0x64, 0x98, 0x7c, 0x8a,
[1643351009.455454][3699:3705] CHIP:IN: 0xb4, 0x3a, 0xe0, 0x4b, 0xbf, 0xcc, 0xed, 0xe2,
[1643351009.455478][3699:3705] CHIP:IN: 0x28, 0xef, 0x87, 0xab, 0xcf, 0x10, 0xc4, 0x45,
[1643351009.455500][3699:3705] CHIP:IN: 0x5d, 0x50, 0xbf, 0xed, 0xff, 0x62, 0xe9, 0x87,
[1643351009.455523][3699:3705] CHIP:IN: 0xf6, 0xac, 0x90, 0x2d, 0x2c, 0x49, 0x6d, 0x6d,
[1643351009.455546][3699:3705] CHIP:IN: 0x93, 0x7e, 0xc6, 0xb4, 0x18, 0x65, 0x90, 0xe2,
[1643351009.455569][3699:3705] CHIP:IN: 0x2c, 0x80, 0xe1, 0x25, 0x5c, 0xb7, 0xfc, 0x0e,
[1643351009.455590][3699:3705] CHIP:IN: 0x3d,
[1643351009.455649][3699:3705] CHIP:IN: Generated compressed fabric ID
[1643351009.455677][3699:3705] CHIP:IN: 0x56, 0x97, 0xd4, 0x7a, 0x18, 0xde, 0x2e, 0x34,
[1643351009.456588][3699:3705] CHIP:SC: Found MRP parameters in the message
[1643351009.456642][3699:3705] CHIP:SC: Sending Sigma3
[1643351009.457029][3699:3705] CHIP:EM: Piggybacking Ack for MessageCounter:2132135621 on exchange: 16646i
[1643351009.457085][3699:3705] CHIP:IN: Prepared plaintext message 0xaaaae5c18810 to 0x0000000000000000 (0)  of type 0x32 and protocolId (0, 0) on exchange 16646i with MessageCounter:3617776722.
[1643351009.457126][3699:3705] CHIP:IN: Sending plaintext msg 0xaaaae5c18810 with MessageCounter:3617776722 to 0x0000000000000000 at monotonic time: 4208099 msec
[1643351009.457303][3699:3705] CHIP:SC: Sent Sigma3 msg
[1643351009.805200][3699:3705] CHIP:EM: Received message of type 0x40 with protocolId (0, 0) and MessageCounter:2132135622 on exchange 16646i
[1643351009.805304][3699:3705] CHIP:EM: Found matching exchange: 16646i, Delegate: 0xffff809d7348
[1643351009.805438][3699:3705] CHIP:EM: Rxd Ack; Removing MessageCounter:3617776722 from Retrans Table on exchange 16646i
[1643351009.805770][3699:3705] CHIP:EM: Removed CHIP MessageCounter:3617776722 from RetransTable on exchange 16646i
[1643351009.805874][3699:3705] CHIP:SC: Success status report received. Session was established
[1643351009.805944][3699:3705] CHIP:IN: New secure session created for device 0x0000000000BC5C01, key 6!!
[1643351009.806179][3699:3705] CHIP:TOO: Sending cluster (0x00000028) command (0x00000000) on endpoint 1
[1643351009.806333][3699:3705] CHIP:DMG: ICR moving to [AddingComm]
[1643351009.806434][3699:3705] CHIP:DMG: ICR moving to [AddedComma]
[1643351009.806609][3699:3705] CHIP:IN: Prepared encrypted message 0xaaaae5c18810 to 0x0000000000BC5C01 (1)  of type 0xa and protocolId (0, 1) on exchange 16647i with MessageCounter:4818778.
[1643351009.806708][3699:3705] CHIP:IN: Sending encrypted msg 0xaaaae5c18810 with MessageCounter:4818778 to 0x0000000000BC5C01 (1) at monotonic time: 4208449 msec
[1643351009.807077][3699:3705] CHIP:DMG: ICR moving to [AwaitingTi]
[1643351009.807417][3699:3705] CHIP:CTL: Device connected callback with null pairing delegate. Ignoring
[1643351009.807494][3699:3705] CHIP:EM: Sending Standalone Ack for MessageCounter:2132135622 on exchange 16646i
[1643351009.807572][3699:3705] CHIP:IN: Prepared plaintext message 0xffff8095e9c8 to 0x0000000000000000 (0)  of type 0x10 and protocolId (0, 0) on exchange 16646i with MessageCounter:3617776723.
[1643351009.807664][3699:3705] CHIP:IN: Sending plaintext msg 0xffff8095e9c8 with MessageCounter:3617776723 to 0x0000000000000000 at monotonic time: 4208450 msec
[1643351009.807873][3699:3705] CHIP:EM: Flushed pending ack for MessageCounter:2132135622 on exchange 16646i
[1643351009.907238][3699:3705] CHIP:EM: Received message of type 0x1 with protocolId (0, 1) and MessageCounter:14547384 on exchange 16647i
[1643351009.907339][3699:3705] CHIP:EM: Found matching exchange: 16647i, Delegate: 0xffff6c0043b0
[1643351009.907424][3699:3705] CHIP:EM: Rxd Ack; Removing MessageCounter:4818778 from Retrans Table on exchange 16647i
[1643351009.907492][3699:3705] CHIP:EM: Removed CHIP MessageCounter:4818778 from RetransTable on exchange 16647i
[1643351009.907602][3699:3705] CHIP:DMG: StatusResponseMessage =
[1643351009.907660][3699:3705] CHIP:DMG: {
[1643351009.907707][3699:3705] CHIP:DMG:        Status = 0x0,
[1643351009.907757][3699:3705] CHIP:DMG: }
[1643351009.907808][3699:3705] CHIP:IM: Received status response, status is 0
[1643351009.907924][3699:3705] CHIP:EM: Piggybacking Ack for MessageCounter:14547384 on exchange: 16647i
[1643351009.908057][3699:3705] CHIP:IN: Prepared encrypted message 0xaaaae5c18810 to 0x0000000000BC5C01 (1)  of type 0x8 and protocolId (0, 1) on exchange 16647i with MessageCounter:4818779.
[1643351009.908157][3699:3705] CHIP:IN: Sending encrypted msg 0xaaaae5c18810 with MessageCounter:4818779 to 0x0000000000BC5C01 (1) at monotonic time: 4208550 msec
[1643351009.908514][3699:3705] CHIP:DMG: ICR moving to [CommandSen]
[1643351010.034553][3699:3705] CHIP:EM: Received message of type 0x9 with protocolId (0, 1) and MessageCounter:14547385 on exchange 16647i
[1643351010.034633][3699:3705] CHIP:EM: Found matching exchange: 16647i, Delegate: 0xffff6c0043b0
[1643351010.034703][3699:3705] CHIP:EM: Rxd Ack; Removing MessageCounter:4818779 from Retrans Table on exchange 16647i
[1643351010.034741][3699:3705] CHIP:EM: Removed CHIP MessageCounter:4818779 from RetransTable on exchange 16647i
[1643351010.034797][3699:3705] CHIP:DMG: ICR moving to [ResponseRe]
[1643351010.034876][3699:3705] CHIP:DMG: InvokeResponseMessage =
[1643351010.034921][3699:3705] CHIP:DMG: {
[1643351010.034964][3699:3705] CHIP:DMG:        suppressResponse = false,
[1643351010.035006][3699:3705] CHIP:DMG:        InvokeResponseIBs =
[1643351010.035061][3699:3705] CHIP:DMG:        [
[1643351010.035103][3699:3705] CHIP:DMG:                InvokeResponseIB =
[1643351010.035158][3699:3705] CHIP:DMG:                {
[1643351010.035202][3699:3705] CHIP:DMG:                        CommandStatusIB =
[1643351010.035258][3699:3705] CHIP:DMG:                        {
[1643351010.035312][3699:3705] CHIP:DMG:                                CommandPathIB =
[1643351010.035366][3699:3705] CHIP:DMG:                                {
[1643351010.035429][3699:3705] CHIP:DMG:                                        EndpointId = 0x1,
[1643351010.035613][3699:3705] CHIP:DMG:                                        ClusterId = 0x28,
[1643351010.035666][3699:3705] CHIP:DMG:                                        CommandId = 0x10020000,
[1643351010.035709][3699:3705] CHIP:DMG:                                },
[1643351010.035763][3699:3705] CHIP:DMG:
[1643351010.035803][3699:3705] CHIP:DMG:                                StatusIB =
[1643351010.035846][3699:3705] CHIP:DMG:                                {
[1643351010.035888][3699:3705] CHIP:DMG:                                        status = 0x85,
[1643351010.035931][3699:3705] CHIP:DMG:                                },
[1643351010.035975][3699:3705] CHIP:DMG:
[1643351010.036012][3699:3705] CHIP:DMG:                        },
[1643351010.036059][3699:3705] CHIP:DMG:
[1643351010.036094][3699:3705] CHIP:DMG:                },
[1643351010.036139][3699:3705] CHIP:DMG:
[1643351010.036172][3699:3705] CHIP:DMG:        ],
[1643351010.036215][3699:3705] CHIP:DMG:
[1643351010.036246][3699:3705] CHIP:DMG: },
[1643351010.036336][3699:3705] CHIP:DMG: Received Command Response Status for Endpoint=1 Cluster=0x0000_0028 Command=0x1002_0000 Status=0x85
[1643351010.036402][3699:3705] CHIP:TOO: Default Failure Response: 0x85
[1643351010.036485][3699:3705] CHIP:DMG: ICR moving to [AwaitingDe]
[1643351010.036539][3699:3705] CHIP:EM: Sending Standalone Ack for MessageCounter:14547385 on exchange 16647i
[1643351010.036647][3699:3705] CHIP:IN: Prepared encrypted message 0xffff8095e9d8 to 0x0000000000BC5C01 (1)  of type 0x10 and protocolId (0, 0) on exchange 16647i with MessageCounter:4818780.
[1643351010.036714][3699:3705] CHIP:IN: Sending encrypted msg 0xffff8095e9d8 with MessageCounter:4818780 to 0x0000000000BC5C01 (1) at monotonic time: 4208679 msec
[1643351010.036911][3699:3705] CHIP:EM: Flushed pending ack for MessageCounter:14547385 on exchange 16647i
[1643351010.037332][3699:3699] CHIP:-: ../../examples/chip-tool/third_party/connectedhomeip/zzz_generated/chip-tool/zap-generated/cluster/Commands.h:2502: CHIP Error 0x000000AC: Internal error at ../../examples/chip-tool/commands/common/CHIPCommand.cpp:59
[1643351010.037442][3699:3699] CHIP:TOO: Run command failure: ../../examples/chip-tool/third_party/connectedhomeip/zzz_generated/chip-tool/zap-generated/cluster/Commands.h:2502: CHIP Error 0x000000AC: Internal error
[1643351010.042609][3699:3699] CHIP:SPT: VerifyOrDie failure at ../../examples/chip-tool/third_party/connectedhomeip/src/inet/InetLayer.h:121: sEndPointPool.Allocated() == 0
Aborted (core dumped)
```

**Comment by andy31415** [comment] 2022-01-30 14:37
What were the steps involved here?

**Comment by andy31415** [comment] 2022-01-30 14:42
Seems like a duplicate of #14472 but with a different test case run.
We seem to have quite a few stack traces showing potential memory corruption.

**Closed by andy31415** 2022-01-30 14:42 UTC
