### ISSUE TITLE
[Workflow] REPL Tests - Linux / ModuleNotFoundError: No module named 'pyperclip'

### ISSUE THREAD

**Issue by lboue** [project-chip/connectedhomeip#35581] opened 2024-09-13 17:12 UTC
### Workflow issues

REPL Tests - Linux / ModuleNotFoundError: No module named 'pyperclip'

I am facing an issue with `REPL Tests - Linux` CI pipeline:

Exemple: [job 30120518953](https://github.com/project-chip/connectedhomeip/actions/runs/10853057290/job/30120518953?pr=35410#logs)

### Platform

other

**Comment by andy31415** [comment] 2024-10-21 15:28
Closing as not reproducible: PR got merged and I have not seen this error since then. Should re-open if this happens frequently.

**Closed** 2024-10-24 13:46 UTC
Labels: linux, workflows, needs triage
