### ISSUE TITLE
Error when compilation of lock-app

### ISSUE THREAD

**Issue by esliu-apple** [project-chip/connectedhomeip#27610] opened 2023-07-04 08:25 UTC
### Reproduction steps

With Matter SHA 3c8b8cf9680e0715d50a9866b125effd7530dbd5.

I'm running into this error when compiling NRF52840 board as door lock, while compiling as lightbulb is OK.

```
/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/subsys/bluetooth/host/conn.c:547:12: note: 'pending_no_cb' was declared here
  547 |  uint32_t *pending_no_cb;
      |            ^~~~~~~~~~~~~
[559/774] Building C object zephyr/drivers/ieee802154/CMakeFiles/drivers__ieee802154.dir/ieee802154_nrf5.c.obj
FAILED: zephyr/drivers/ieee802154/CMakeFiles/drivers__ieee802154.dir/ieee802154_nrf5.c.obj
ccache /Users/emmanuelliu/chip-nordic-tools/gnuarmemb/bin/arm-none-eabi-gcc -DKERNEL -DMBEDTLS_CONFIG_FILE=\"nrf-config.h\" -DMBEDTLS_USER_CONFIG_FILE=\"nrf-config-user.h\" -DNRF52840_XXAA -DNRF_802154_ACK_TIMEOUT_ENABLED=1 -DNRF_802154_CARRIER_FUNCTIONS_ENABLED=0 -DNRF_802154_CCA_CORR_LIMIT_DEFAULT=2 -DNRF_802154_CCA_CORR_THRESHOLD_DEFAULT=45 -DNRF_802154_CCA_ED_THRESHOLD_DEFAULT=45 -DNRF_802154_CCA_MODE_DEFAULT=NRF_RADIO_CCA_MODE_ED -DNRF_802154_ECB_PRIORITY=-1 -DNRF_802154_ENCRYPTION_ENABLED=1 -DNRF_802154_IE_WRITER_ENABLED=1 -DNRF_802154_INTERNAL_RADIO_IRQ_HANDLING=0 -DNRF_802154_PENDING_EXTENDED_ADDRESSES=16 -DNRF_802154_PENDING_SHORT_ADDRESSES=16 -DNRF_802154_RX_BUFFERS=16 -DNRF_802154_SECURITY_WRITER_ENABLED=1 -DNRF_802154_SWI_PRIORITY=1 -DNRF_802154_TX_STARTED_NOTIFY_ENABLED=1 -DNRF_802154_USE_RAW_API=1 -DUSE_PARTITION_MANAGER=1 -DZCBOR_ASSERTS -D_ANSI_SOURCE -D_FORTIFY_SOURCE=1 -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR_SUPERVISOR__ -D__ZEPHYR__=1 -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrf/drivers/mpsl/clock_control -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/include -I/Users/emmanuelliu/connectedhomeip/examples/lock-app/nrfconnect/build/zephyr/include/generated -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/soc/arm/nordic_nrf/nrf52 -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/lib/libc/newlib/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/soc/arm/nordic_nrf/common/. -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/subsys/bluetooth -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/subsys/net/lib/sockets/. -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/subsys/settings/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrf/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrf/lib/multithreading_lock/. -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrf/subsys/bluetooth/controller/. -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/drivers/flash -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrf/tests/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/modules/openthread/platform/. -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/hal/cmsis/CMSIS/Core/Include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/hal/nordic/nrfx -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/hal/nordic/nrfx/drivers/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/hal/nordic/nrfx/mdk -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/modules/hal_nordic/nrfx/. -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/crypto/tinycrypt/lib/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/lib/zcbor/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nfc/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/mpsl/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/mpsl/include/protocol -I/Users/emmanuelliu/connectedhomeip/examples/lock-app/nrfconnect/build/modules/nrfxlib/nrfxlib/nrf_security/src/include/generated -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nrf_security/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nrf_security/../crypto/nrf_oberon/core/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nrf_security/../crypto/nrf_oberon/core/library -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/crypto/mbedtls/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/crypto/mbedtls/library -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nrf_security/../crypto/nrf_oberon/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nrf_security/../crypto/nrf_oberon/include/mbedtls -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nrf_security/../crypto/nrf_oberon/core/oberon/drivers -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/crypto/nrf_oberon/include/mbedtls -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/crypto/nrf_oberon/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nrf_802154/driver/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/nrf_802154/sl/include -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/softdevice_controller/include -I/Users/emmanuelliu/connectedhomeip/examples/lock-app/nrfconnect/build/modules/openthread/build/etc/cmake -I/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/lib/openthread/etc/cmake -isystem /Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/lib/openthread/include -isystem /Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/modules/lib/openthread/examples/platforms -isystem /Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/nrfxlib/crypto/nrf_cc310_platform/include -fno-strict-aliasing -Os -imacros /Users/emmanuelliu/connectedhomeip/examples/lock-app/nrfconnect/build/zephyr/include/generated/autoconf.h -fno-common -g -gdwarf-4 -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -mfpu=fpv4-sp-d16 -mfloat-abi=hard --sysroot=/Users/emmanuelliu/chip-nordic-tools/gnuarmemb/arm-none-eabi -imacros /Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/include/zephyr/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -Werror=implicit-int -fno-pic -fno-pie -fno-asynchronous-unwind-tables -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/Users/emmanuelliu/connectedhomeip/examples/lock-app/nrfconnect=CMAKE_SOURCE_DIR -fmacro-prefix-map=/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf=WEST_TOPDIR -ffunction-sections -fdata-sections -specs=nano.specs -D_POSIX_THREADS -std=c99 -MD -MT zephyr/drivers/ieee802154/CMakeFiles/drivers__ieee802154.dir/ieee802154_nrf5.c.obj -MF zephyr/drivers/ieee802154/CMakeFiles/drivers__ieee802154.dir/ieee802154_nrf5.c.obj.d -o zephyr/drivers/ieee802154/CMakeFiles/drivers__ieee802154.dir/ieee802154_nrf5.c.obj -c /Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/drivers/ieee802154/ieee802154_nrf5.c
/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/drivers/ieee802154/ieee802154_nrf5.c: In function 'nrf5_configure':
/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/drivers/ieee802154/ieee802154_nrf5.c:947:3: error: a label can only be part of a statement and a declaration is not a statement
  947 |   uint64_t csl_rx_time = target_time_convert_to_64_bits(config->csl_rx_time);
      |   ^~~~~~~~
/Users/emmanuelliu/chip-nordic-tools/nrfconnect/sdk-nrf/zephyr/drivers/ieee802154/ieee802154_nrf5.c:964:3: error: a label can only be part of a statement and a declaration is not a statement
  964 |   uint64_t start = target_time_convert_to_64_bits(config->rx_slot.start);
      |   ^~~~~~~~
[572/774] Building C object modules/mcuboot/boot/bootut...tloader/mcuboot/boot/bootutil/src/bootutil_public.c.obj
ninja: build stopped: subcommand failed.
FATAL ERROR: command exited with status 1: /Users/emmanuelliu/connectedhomeip/.environment/pigweed-venv/bin/cmake --build /Users/emmanuelliu/connectedhomeip/examples/lock-app/nrfconnect/build
```

Steps to reproduce:

git clone --recurse-submodules https://github.com/project-chip/connectedhomeip.git
cd connectedhomeip
git reset --hard 3c8b8cf9680e0715d50a9866b125effd7530dbd5
git clean -Xdf
git submodule update --init
source scripts/bootstrap.sh
source scripts/activate.sh
source ./042122_install_nordic_tools.sh
python3 scripts/setup/nrfconnect/update_ncs.py --update
cd examples/lock-app/nrfconnect/
west build -b nrf52840dk_nrf52840 -- -DCONFIG_CHIP_LIB_SHELL=y -DCONFIG_CHIP_LOG_SIZE_OPTIMIZATION=n

### Bug prevalence

When ever I do this today.

### GitHub hash of the SDK that was being used

3c8b8cf9680e0715d50a9866b125effd7530dbd5

### Platform

nrf, python

### Platform Version(s)

Darwin

**Comment by bzbarsky-apple** [comment] 2023-07-06 20:29
Duplicate of #27634 (which was filed later, but is already assigned to hopefully the right person).

**Closed by bzbarsky-apple** 2023-07-06 20:29 UTC
Labels: bug, needs triage
