### ISSUE TITLE
TC-GENDIAG-1.1 NetworkInterfaceType

### ISSUE THREAD

**Issue by chrisbeach59** [project-chip/connectedhomeip#14236] opened 2022-01-25 14:15 UTC
#### Problem
typedef struct _NetworkInterfaceType
{
    chip::CharSpan Name;
    bool FabricConnected;
    bool OffPremiseServicesReachableIPv4;
    bool OffPremiseServicesReachableIPv6;
    chip::ByteSpan HardwareAddress;
    uint8_t Type;
} NetworkInterfaceType;

Is missing IPV4 Address and IPV6 Address that the test case is looking for.

 #### Proposed Solution
Add IPV4 and IPV6 Mac addresses

**Comment by franck-apple** [comment] 2022-05-17 09:52
dupe of #14840. Closing.

**Closed by franck-apple** 2022-05-17 09:52 UTC
Labels: V1.0, spec, cert
