### ISSUE TITLE
Add IM/Ember ACL support

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#8442] opened 2021-07-15 20:48 UTC
There is a declarative thing where for every attribute or command the relevant access is encoded in the XML and then we generate whatever from it. And we match ACLs against that whatever.

**Comment by tcarmelveilleux** [comment] 2021-10-04 20:41
@tecimovic is working on XML encoding

**Comment by mlepage-google** [comment] 2022-01-27 22:04
Dupe of:
- #10246 for the zap parts
- #10247 for the ember parts

Mitigated in the interim by #14283

Closing.

**Closed by mlepage-google** 2022-01-27 22:04 UTC
Labels: V1.X, Interaction Model Work
