### ISSUE TITLE
Crash in chip::Ble::BLEEndPoint::ConnectionObjectIs

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#5193] opened 2021-03-05 22:19 UTC
#### Problem
```
Thread 5 name:  Dispatch queue: com.chip.ble.work_queue
Thread 5 Crashed ↩:
0   CHIP                          	0x00000001edb39f50 chip::Ble::BLEEndPoint::ConnectionObjectIs(void*) + 20 (BLEEndPoint.h:104)
1   CHIP                          	0x00000001edb39c84 chip::Transport::BLE::OnBleConnectionComplete(void*, void*) + 64 (BLE.cpp:170)
2   CHIP                          	0x00000001edb1d984 -[BleConnection peripheral:didDiscoverCharacteristicsForService:error:] + 124 (BleConnectionDelegateImpl.mm:199)
3   CoreBluetooth                 	0x00000001b387da00 -[CBPeripheral handleAttributeEvent:args:attributeSelector:delegateSelector:delegateFlag:] + 228 (CBPeripheral)
4   CoreBluetooth                 	0x00000001b387dac0 -[CBPeripheral handleServiceEvent:serviceSelector:delegateSelector:delegateFlag:] + 124 (CBPeripheral)
5   CoreBluetooth                 	0x00000001b387a0b4 -[CBPeripheral handleMsg:args:] + 364 (CBPeripheral)
6   CoreBluetooth                 	0x00000001b386cb84 -[CBCentralManager handleMsg:args:] + 196 (CBCentralManager)
7   CoreBluetooth                 	0x00000001b389b60c -[CBManager xpcConnectionDidReceiveMsg:args:] + 208 (CBManager)
8   CoreBluetooth                 	0x00000001b388d3d4 __30-[CBXpcConnection _handleMsg:]_block_invoke + 68 (CBXpcConnection)
9   libdispatch.dylib             	0x0000000197e96f9c _dispatch_call_block_and_release + 32 (init.c)
10  libdispatch.dylib             	0x0000000197e98d04 _dispatch_client_callout + 20 (object.m)
11  libdispatch.dylib             	0x0000000197ea0854 _dispatch_lane_serial_drain + 644 (inline_internal.h)
12  libdispatch.dylib             	0x0000000197ea1480 _dispatch_lane_invoke + 472 (queue.c)
13  libdispatch.dylib             	0x0000000197ea06fc _dispatch_lane_serial_drain + 300 (inline_internal.h)
14  libdispatch.dylib             	0x0000000197ea1444 _dispatch_lane_invoke + 412 (queue.c)
15  libdispatch.dylib             	0x0000000197eac174 _dispatch_workloop_worker_thread + 768 (queue.c)
16  libsystem_pthread.dylib       	0x00000001ea58f704 _pthread_wqthread + 276 (pthread.c)
17  libsystem_pthread.dylib       	0x00000001ea596744 start_wqthread + 8
```

**Comment by vivien-apple** [comment] 2021-03-09 09:21
Duplicate of #4339

**Closed by vivien-apple** 2021-03-09 09:21 UTC
