### ISSUE TITLE
[TC-LC-1.1] Global attributes missing from "User Label" cluster

### ISSUE THREAD

**Issue by manjunath-grl** [project-chip/connectedhomeip#17807] opened 2022-04-27 13:52 UTC
Summary:
AttributeList and FeatureMap global attributes missing from User Label cluster when executed.

Testplan screenshot:
![image](https://user-images.githubusercontent.com/102359958/165534311-e023c2c7-fc8c-473d-a946-a1e50338ed34.png)

Execution logs and screenshot:
![LC-1 1](https://user-images.githubusercontent.com/102359958/165534442-6f90a63a-5ff7-46cd-96ee-c8154d996b80.png)
[LC_1_1.txt](https://github.com/project-chip/connectedhomeip/files/8572594/LC_1_1.txt)

**Comment by bzbarsky-apple** [comment] 2022-05-09 15:50
Duplicate of 16725.

**Closed by bzbarsky-apple** 2022-05-09 15:50 UTC
