### ISSUE TITLE
CHIPDeviceController needs proper support for setting network credentials during a commissioning session

### ISSUE THREAD

**Issue by chrisdecenzo** [project-chip/connectedhomeip#21314] opened 2022-07-28 00:26 UTC
#### Problem
 * In many cases, the selection of network credentials needs to be done asynchronously during the PASE session. For example, after the commissioner determines the network technology of the target (WiFi or Thread) and after a network scan has been done. Often this selection will need user or cloud input, so it needs to be asynchronous.
 * A workaround was quickly added in PR https://github.com/project-chip/connectedhomeip/pull/20766 which includes a pause/resume feature of the AutoCommissioner but a cleaner fix would be to introduce steps in CHIPDeviceController for requesting network credentials. This would allow commissioning apps to avoid needing to create their own AutoCommissioner and pass it in to CHIPDeviceController.

 #### Proposed Solution
* Add optional steps to CHIPDeviceController for obtaining network credentials from its caller.

**Comment by mrjerryjohns** [comment] 2022-08-01 18:06
Can we close this issue @chrisdecenzo ?

**Comment by bzbarsky-apple** [comment] 2022-08-05 14:25
And to be clear, the issue is not "creating your own AutoCommissioner"; the issue is the extra pause API and whatnot, which introduces yet another way of doing async operations via the delegate when we have a perfectly good way already: async call into the delegate.

**Closed** 2022-08-16 03:44 UTC
Labels: V1.0, commissioning
