### ISSUE TITLE
FeatureMap Attribute is not present in following clusters

### ISSUE THREAD

**Issue by kowsisoundhar12** [project-chip/connectedhomeip#17483] opened 2022-04-19 03:55 UTC
Feature Map global attribute is not present in following Clusters:

1.Identify Cluster
2.lluminance Measurement Cluster
3.Color Control Cluster
4.Flow Measurement Cluster
5.Occupancy Sensing Cluster
6.Pressure Measurement Cluster
7.Boolean State Cluster

[I-1-1-attribute-missing.zip](https://github.com/project-chip/connectedhomeip/files/8509699/I-1-1-attribute-missing.zip)
[ILL-1-1-Attribute-missing.zip](https://github.com/project-chip/connectedhomeip/files/8509700/ILL-1-1-Attribute-missing.zip)
[CC-1-1-ATtribute-missing.zip](https://github.com/project-chip/connectedhomeip/files/8509701/CC-1-1-ATtribute-missing.zip)
[FLW-1-1-Attribute-missing.zip](https://github.com/project-chip/connectedhomeip/files/8509702/FLW-1-1-Attribute-missing.zip)
[OCC-1-1-Attribute-missing.zip](https://github.com/project-chip/connectedhomeip/files/8509703/OCC-1-1-Attribute-missing.zip)
[PRS-1-1-Featuremap-missing.zip](https://github.com/project-chip/connectedhomeip/files/8509704/PRS-1-1-Featuremap-missing.zip)

**Comment by manjunath-grl** [comment] 2022-05-02 19:22
Feature Map global attribute is not present in following Clusters:
1.Power Source Configuration

[PSCFG11_FM.txt](https://github.com/project-chip/connectedhomeip/files/8605563/PSCFG11_FM.txt)

**Comment by bzbarsky-apple** [comment] 2022-05-09 15:50
Duplicate of #16725

**Closed by bzbarsky-apple** 2022-05-09 15:50 UTC
