### ISSUE TITLE
[Build] ERROR at //third_party/connectedhomeip/third_party/jsoncpp/BUILD.gn:26:1: Source file not found.source_set("jsoncpp"){

### ISSUE THREAD

**Issue by tianrongqin** [project-chip/connectedhomeip#29839] opened 2023-10-18 05:09 UTC
### Build issue(s)

when I build the esp32 which is in connectedhomeip,it can't build successfully and display "ERROR at //third_party/connectedhomeip/third_party/jsoncpp/BUILD.gn:26:1: Source file not found.source_set("jsoncpp"){".How can  I do to slove this problem?

### Platform

esp32

**Comment by bzbarsky-apple** [comment] 2023-10-18 12:59
@tianrongqin What exact steps are you following to build?  Which SHA are you building?

@dhrishi @shubhamdp

**Comment by bzbarsky-apple** [comment] 2023-10-18 12:59
Duplicate of https://github.com/project-chip/connectedhomeip/issues/29842

**Closed by bzbarsky-apple** 2023-10-18 12:59 UTC
Labels: build issue, esp32, needs triage
