### ISSUE TITLE
[XML] Update Fan Control Cluster XML to match updated spec

### ISSUE THREAD

**Issue by ReneJosefsen** [project-chip/connectedhomeip#27399] opened 2023-06-21 20:05 UTC
The data types names has been updated in Fan Control Cluster and must be updated in the XML as well.

**Added:**
- FanModeEnum
- FanModeSequenceEnum
- RocktBitmap
- WindBitmap

Spec PR: https://github.com/CHIP-Specifications/connectedhomeip-spec/pull/7210 (already merged)

**Comment by bzbarsky-apple** [comment] 2023-06-22 03:21
Duplicate of https://github.com/project-chip/connectedhomeip/issues/27358

**Closed by bzbarsky-apple** 2023-06-22 03:21 UTC
