### ISSUE TITLE
We need to encode scene field sets in TLV.

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14050] opened 2022-01-25 08:00 UTC
https://github.com/project-chip/connectedhomeip/issues/10334

---

https://github.com/project-chip/connectedhomeip/blob/f0f5de0d79ae1c51d7fddbf70900ebac0acd899a/src/app/clusters/scenes/scenes.cpp#L862-L867

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in f0f5de0d79ae1c51d7fddbf70900ebac0acd899a.

**Comment by tcarmelveilleux** [comment] 2022-01-31 20:22
Duplicate of https://github.com/project-chip/connectedhomeip/issues/10334

**Closed by tcarmelveilleux** 2022-01-31 20:22 UTC
Labels: duplicate, V1.0, todo :spiral_notepad:
