### ISSUE TITLE
Invoke Request message with multiple path support needed

### ISSUE THREAD

**Issue by akrithika27** [project-chip/connectedhomeip#23992] opened 2022-12-09 07:04 UTC
### Feature description

```bash
Invoke Request message with multiple path support needed

Test Case - TC-IDM-1.1 step#3
```

### Platform

raspi

**Comment by bzbarsky-apple** [comment] 2022-12-09 08:43
Duplicate of https://github.com/project-chip/connectedhomeip/issues/23381

**Closed by bzbarsky-apple** 2022-12-09 08:43 UTC
Labels: Interaction Model Work
