### ISSUE TITLE
[Build] Android CHIPTool failed

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#28118] opened 2023-07-20 16:08 UTC
### Build issue(s)

https://github.com/project-chip/connectedhomeip/actions/runs/5604176594/job/15182456147

**Comment by woody-apple** [comment] 2023-07-20 16:10
Another here: https://github.com/project-chip/connectedhomeip/actions/runs/5602013665/job/15175721320

**Comment by woody-apple** [comment] 2023-07-20 16:12
Another here: https://github.com/project-chip/connectedhomeip/actions/runs/5594249511/job/15153019730

**Comment by woody-apple** [comment] 2023-07-20 16:13
Another: https://github.com/project-chip/connectedhomeip/actions/runs/5594171552/job/15152788365

**Comment by woody-apple** [comment] 2023-07-20 16:14
https://github.com/project-chip/connectedhomeip/actions/runs/5594200898/job/15152878815

**Comment by woody-apple** [comment] 2023-07-20 16:14
https://github.com/project-chip/connectedhomeip/actions/runs/5594185817/job/15152834249

**Comment by woody-apple** [comment] 2023-07-20 16:15
Tagging as common failure, @andy31415 can someone take a peek?

**Comment by woody-apple** [comment] 2023-07-20 16:16
https://github.com/project-chip/connectedhomeip/actions/runs/5594171552/job/15152788365

**Comment by woody-apple** [comment] 2023-07-20 16:17
This appears to be our top build failure looking at all builds over the last 4 days

**Comment by andy31415** [comment] 2023-07-20 21:21
I am working with pigweed to remove the need of creating a mapfile, since that seems to pollute too much our output (and may be the cause of the failure because it is 800MB).

Will re-assess once we have a pigweed update with that change (expecting sometime next week, assuming we can fix other failures that I saw relating to RPC builds and tracing)

**Comment by andy31415** [comment] 2023-07-21 21:16
Newest pigweed updated in #28161 , if any new failures occur we should be able to investigate.

I assume fixed for now because we save 800MB of space and reduce log sizes. So closing for now, but can re-open if not actually fix.

**Closed by andy31415** 2023-07-21 21:16 UTC
Labels: build issue, android
