### ISSUE TITLE
[TC-WIFIDIAG-3.1] reset-counts  command not supported in wifi diagnostics Cluster in TE7

### ISSUE THREAD

**Issue by praveenCY** [project-chip/connectedhomeip#12058] opened 2021-11-20 00:03 UTC
#### Problem
reset-counts  command not supported in wifi diagnostics Cluster

IMClusterCommandHandler.cpp doesnot have support for WiFiNetworkDiagnostics reset-counts

namespace WiFiNetworkDiagnostics {

void DispatchServerCommand(CommandHandler * apCommandObj, const ConcreteCommandPath & aCommandPath, TLV::TLVReader & aDataTlv)
{
    // We are using TLVUnpackError and TLVError here since both of them can be CHIP_END_OF_TLV
    // When TLVError is CHIP_END_OF_TLV, it means we have iterated all of the items, which is not a real error.
    // Any error value TLVUnpackError means we have received an illegal value.
    // The following variables are used for all commands to save code size.
    CHIP_ERROR TLVError = CHIP_NO_ERROR;
    bool wasHandled     = false;
    {
        switch (aCommandPath.mCommandId)
        {
        case Commands::ResetCounts::Id: {
            Commands::ResetCounts::DecodableType commandData;
            TLVError = DataModel::Decode(aDataTlv, commandData);
            if (TLVError == CHIP_NO_ERROR)
            {
                wasHandled = emberAfWiFiNetworkDiagnosticsClusterResetCountsCallback(apCommandObj, aCommandPath, commandData);
            }
            break;
        }
        default: {
            // Unrecognized command ID, error status will apply.
            ReportCommandUnsupported(apCommandObj, aCommandPath);
            return;
        }
        }
    }

Logs: [LOCK-TC-WIFIDIAG-3.1.txt](https://github.com/project-chip/connectedhomeip/files/7573473/LOCK-TC-WIFIDIAG-3.1.txt)

**Comment by bzbarsky-apple** [comment] 2022-05-05 05:23
@praveenCY Is this still an issue?

**Comment by franck-apple** [comment] 2022-05-17 09:47
dupe of #18321. Closing

**Closed by franck-apple** 2022-05-17 09:47 UTC
Labels: V1.0, spec, utility-cluster, cert
