### ISSUE TITLE
Android chip-tool crash during saving wifi credentials screen

### ISSUE THREAD

**Issue by jamesluo11** [project-chip/connectedhomeip#21571] opened 2022-08-03 03:46 UTC
#### Problem
Complied the master latest branch(JAVA 8), got the android chip-tool.
While chip-tool crash without any prompt during saving wifi credentials screen
<what's wrong or missing, please include any applicable:
 * expected behavior
 Pairing process succeed 
 * actual behavior
 The pairing process did NOT start,   chip-tool crash after clicking "SAVE NETWORK".
 * steps to reproduce
 Just normally follow the steps: "PROVISION CHIP DEVICE WITH WI-FI" -> "SUBMIT" -> "SAVE NETWORK". Then app crash without any prompt.
 * system configuration
 oppo android phone 
 * screenshots, images, logs, etc.
 >
[android chip-tool crash.log](https://github.com/project-chip/connectedhomeip/files/9247776/android.chip-tool.crash.log)

 #### Proposed Solution
<suggested fix, suggested enhancement>

**Comment by robertfarnum** [comment] 2022-08-03 12:28
The logs indicate this is a duplicate of https://github.com/project-chip/connectedhomeip/issues/21493 being worked on by @chrisdecenzo

**Comment by andy31415** [comment] 2022-09-15 20:38
Closed as the dup was closed.

**Closed by andy31415** 2022-09-15 20:38 UTC
Labels: android
