### ISSUE TITLE
Removal of fabric causes crash on all cluster mac app

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#17579] opened 2022-04-21 02:10 UTC
**Steps to reproduce:**

cd connectedhomeip
source scripts/bootstrap.sh
source scripts/activate.sh
scripts/examples/gn_build_example.sh examples/all-clusters-app/linux out/debug chip_config_network_layer_ble=false
./out/debug/chip-all-clusters-app --discriminator 3841 --secured-device-port 5560 --KVS /tmp/chip_kvs_test

From iPhone ;
Launch CHIPTool app
Pair using the QR code
Unpair -> This will unpair but will also cause the following crash;

[1650506418969] [49631:7034916] CHIP: [EM] Piggybacking Ack for MessageCounter:10452993 on exchange: 30588r
[1650506418969] [49631:7034916] CHIP: [SPT] VerifyOrDie failure at ../../examples/all-clusters-app/linux/third_party/connectedhomeip/src/transport/SessionManager.cpp:209: fabric != nullptr
zsh: abort      ./out/debug/chip-all-clusters-app --discriminator 3841 --secured-device-port 

Attaching the complete log;

[allClusterApp-CrashLog.txt](https://github.com/project-chip/connectedhomeip/files/8526733/allClusterApp-CrashLog.txt)

**Comment by bzbarsky-apple** [comment] 2022-04-21 18:52
Duplicate of #16748

**Closed by bzbarsky-apple** 2022-04-21 18:52 UTC
