### ISSUE TITLE
[BUG] [TE2- v1.2] Descriptor cluster's TagList feature is not implemented in the SDK but present in the specs for v1.2

### ISSUE THREAD

**Issue by PSONALl** [project-chip/connectedhomeip#28605] opened 2023-08-09 12:18 UTC
### Reproduction steps

Descriptor cluster's TagList feature is not implemented in the SDK but present in the specs for v1.2

### Bug prevalence

EveryTime

### GitHub hash of the SDK that was being used

5b4f8004662d00bdb111367fec7d3ea978c23372 

### Platform

core

### Platform Version(s)

v1.2

**Comment by bzbarsky-apple** [comment] 2023-08-09 15:56
@PSONALl Is this a duplicate of https://github.com/project-chip/connectedhomeip/issues/28389 or https://github.com/project-chip/connectedhomeip/issues/28098 ?

**Comment by PSONALl** [comment] 2023-08-10 06:05
> @PSONALl Is this a duplicate of #28389 or #28098 ?

Yes, I think the issue's cause might be the same. But the thing to be noted is that along with the TagList Attribute, TagList Feature is also not defined in cluster-enums.h

**Comment by bzbarsky-apple** [comment] 2023-08-10 17:18
Ah, good point.  If this issue is about the missing XML bit, fix coming up.

**Closed** 2023-08-11 12:04 UTC
Labels: bug, Spec XML align, cluster xml for 1.2, needs triage
