### ISSUE TITLE
Unable to control M5 board after it reboots - 0x09 error on iOS chiptool

### ISSUE THREAD

**Issue by kean-apple** [project-chip/connectedhomeip#16195] opened 2022-03-14 20:07 UTC
Problem: If M5 board reboots or crashes, controller eg. iOS chiptool is no longer able to control the board when it powers back up

SHA: d86a7d49e050f6d9eec438934ea205aa93ce77fd

1. Pair M5 board with iOS chiptool app
2. Verify able to toggle light via iOS chiptool
3. Press Red button on M5 board to reset it
4. Verify able to toggle light via iOS chiptool

In step 4, I'm seeing 0x09 error on CHIPtool . Not able to toggle light anymore

**Comment by kean-apple** [comment] 2022-03-14 20:08
[M5-reboot-0x9error-controlling-it-CHIPtool-logs.txt](https://github.com/project-chip/connectedhomeip/files/8248224/M5-reboot-0x9error-controlling-it-CHIPtool-logs.txt)
[reboot-M5-0x9error-controlling-it-M5-logs.txt](https://github.com/project-chip/connectedhomeip/files/8248225/reboot-M5-0x9error-controlling-it-M5-logs.txt)

Possibly same as  https://github.com/project-chip/connectedhomeip/issues/15766 .. filing new GitHub since seeing a 0x09 error instead of 0x01

**Comment by kean-apple** [comment] 2022-03-14 20:09
This issue has severe impact on any Living on/Dogfood type program since if the accessory or M5 board reboots, we can no longer control it

**Comment by bzbarsky-apple** [comment] 2022-03-15 19:45
This is a duplicate of the "we keep trying to use the dead CASE session" issue, no?

**Comment by bzbarsky-apple** [comment] 2022-05-25 01:43
Duplicate of #15766

**Closed by bzbarsky-apple** 2022-05-25 01:43 UTC
Labels: smoke test
