### ISSUE TITLE
TC-GC-2.2 remove-all-groups

### ISSUE THREAD

**Issue by chrisbeach59** [project-chip/connectedhomeip#19738] opened 2022-06-17 19:59 UTC
Step 12a remove all groups succeeds 
Step 12 b expected groupkeymanagement group table to be empty but 2 entries remain

Endpoint: 0 Cluster: 0x0000_003F Attribute 0x0000_0001 DataVersion: 1127221666
[1655495794.848833][42783:42788] CHIP:TOO:   GroupTable: 2 entries
[1655495794.848904][42783:42788] CHIP:TOO:     [1]: {
[1655495794.848930][42783:42788] CHIP:TOO:       GroupId: 2
[1655495794.848957][42783:42788] CHIP:TOO:       Endpoints: 0 entries
[1655495794.848986][42783:42788] CHIP:TOO:       GroupName: grp2
[1655495794.849010][42783:42788] CHIP:TOO:       FabricIndex: 1
[1655495794.849032][42783:42788] CHIP:TOO:      }
[1655495794.849062][42783:42788] CHIP:TOO:     [2]: {
[1655495794.849086][42783:42788] CHIP:TOO:       GroupId: 3
[1655495794.849109][42783:42788] CHIP:TOO:       Endpoints: 0 entries
[1655495794.849134][42783:42788] CHIP:TOO:       GroupName: grp3
[1655495794.849158][42783:42788] CHIP:TOO:       FabricIndex: 1
[1655495794.849179][42783:42788] CHIP:TOO:      }
[1655495794.849285][42783:42788] CHIP:EM: Sending Standalone Ack for M

**Comment by bzbarsky-apple** [comment] 2022-06-17 20:31
Duplicate of #19610

**Closed by bzbarsky-apple** 2022-06-17 20:31 UTC
Labels: request cert blocker
