### ISSUE TITLE
Global attribute-Event-List is not implemented in chip-tool.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#23925] opened 2022-12-06 07:35 UTC
### Feature description

```bash
As per Spec (7.13. Global Elements) chip-tool need to be implemented Mandatory global attribute event-list.
```

### Platform

raspi 

### Platform Version(s)
Chip-tool - RPI-4, 8GB RAM
Platform :Wifi and onnetwork
Commit-ID: https://github.com/project-chip/connectedhomeip/commit/25e241ebcbf11b1f63dbe25546b1f10219866ad0
Dut application: All-Clusters-app

### Anything else?

Below mentioned cluster needs an EventList attribute implementation 

- [ ] Pump configuration and control cluster
- [ ] Level Control Cluster
- [ ] Pressure Measurement Cluster
- [ ] Window Covering Cluster
- [ ] Ethernet Network Diagnostics Cluster
- [ ] Power Source Cluster
- [ ] Pump configuration and control cluster
- [ ] Illuminance Measurement Cluster
- [ ] General Diagnostics Cluster
- [ ] Unit Localization Cluster
- [ ] Time Format Localization Cluster
- [ ] Localization Configuration Cluster
- [ ] Flow Measurement Cluster
- [ ] Fixed Label Cluster
- [ ] User Label Cluster
- [ ] Thermostat Cluster
- [ ] Color Control Cluster
- [ ] Identify Cluster
- [ ] Basic Information Cluster
- [ ] Node Operational Credentials Cluster
- [ ] Thread Network Diagnostics Cluster
- [ ] Boolean State Cluster
- [ ] Groups
- [ ] Door Lock
- [ ] OnOff Cluster
- [ ] Relative Humidity Measurement Cluster
- [ ] Occupancy Sensing Cluster
- [ ] Switch cluster
- [ ] Binding Cluster
- [ ] Descriptor Cluster
- [ ] WiFi Network Diagnostics Cluster
- [ ] Power Source Configuration Cluster
- [ ] Actions Cluster
- [ ] Diagnostic log cluster
- [ ] Bridged Device Basic Information Cluster
- [ ] Software Diagnostics Cluster
- [ ] Network Commisioning Cluster
- [ ] Temperature Measurement Cluster
- [ ] Thermostat User Configuration
- [ ] General Commissioning Cluster

PFA Spec screenshot below:-
![image](https://user-images.githubusercontent.com/95841834/205846726-30bee394-11b1-48d5-913a-4239941da729.png)

PFA Chip-tool  screenshot below:-
![image](https://user-images.githubusercontent.com/95841834/205847061-dc3e29a5-dd84-49df-a612-7e4a917b48a6.png)

**Comment by bzbarsky-apple** [comment] 2022-12-06 16:20
Duplicate of #15011.

**Closed by bzbarsky-apple** 2022-12-06 16:20 UTC
