### ISSUE TITLE
Need to add re-subscription capability for IM

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#9756] opened 2021-09-16 17:15 UTC
#### Problem
We may need to provide the default re-subscription mechanism using fibonacci, and user can also enable/disable this, and user may also wanna provide the customized re-subscription mechanism and override the default one.

**Comment by mrjerryjohns** [comment] 2021-11-19 22:08
Duplicate of #10593

**Closed by mrjerryjohns** 2021-11-19 22:08 UTC
Labels: Interaction Model Work
