### ISSUE TITLE
[CERT-TEST-FAILURE] [TC-DISHMS-2.2] - Test failed

### ISSUE THREAD

**Issue by Survensa** [project-chip/connectedhomeip#27229] opened 2023-06-14 10:34 UTC
### Summary

**All-clusters-app has to be enabled with below mentioned Attributes :**

- [ ] SupportedModes
- [ ] CurrentMode
- [ ] StartUpMode
- [ ] OnMode

**All-clusters-app has to be enabled with below mentioned commands :**
- [ ] ChangeToMode

### GitHub hash of the SDK that was being used

40fb7c246671e9d37ca8bb2cfbf37f81c1509334

### Platform

raspi

### Platform Version(s)

RPI - 4, 8GB RAM

**Comment by bzbarsky-apple** [comment] 2023-07-07 15:49
There is no ChangeToMode, and the rest is a duplicate of https://github.com/project-chip/connectedhomeip/issues/27705

**Comment by bzbarsky-apple** [comment] 2023-07-07 15:50
Ah, things got renamed, so this part is ok.

**Closed** 2023-07-25 05:32 UTC
Labels: examples, spec, cert blocker
