### ISSUE TITLE
source scripts/activate.sh fails with python 3.10.4

### ISSUE THREAD

**Issue by absoluteabutaj** [project-chip/connectedhomeip#19675] opened 2022-06-16 10:09 UTC
After cloning and initialising the sub-module I tried to run `source scripts/activate.sh`  which provides,

```
as@machine:~/connectedhomeip$ git submodule update --init
as@machine:~/connectedhomeip$ git pull
Already up to date.
as@machine:~/connectedhomeip$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
as@machine:~/connectedhomeip$ source scripts/activate.sh 

  WELCOME TO...

           ░▓░
           ▓█▓
           ▓█▓                                                     ▒█     ▒█
      ▒██▒▒▓██▒███▒                ░▒▓▒░  ░▒▓▒░       ░░▓█▒░ ░█  █████████████░    ░▒█▒░       ░░▒░
       ░▓█████▓██░               ▒█▒░░▒▓██▓▒░░▒█▒   ░█▓▒░░▒████    █▓░    █▓░    ▒█▒░░░▒█▓░   ██▒░░
    ▒█▒░         ░██▒           ░█░     █▓     ░█░ ░▓▒      ░▓█    █▓     █▓    ▒█░░    ░██  ▒▓
    ░▓██▓░     ░██▓█░           ░█      ▓█      █░ ░█░       ██    █▓     █▓    ▓██████████  ▒█
     ░▓███▒   ▒███▒░            ░█      ▓█      █░  ██░    ░███    █▓     █▓    ░█▒░         ▒█
 ░▒████████░ ░███▓▓█▓▓▒         ░█      ▒▒      █░   ░█▓██▓█░▒█    ░▓▓█░  ░▓▓█░   ▒▓▓██▓█░   ▒▓
 ░██▒░  ▒██▒ ▒██░  ░▒█▓
         ░▓░ ░▓░

  BOOTSTRAP! Bootstrap may take a few minutes; please be patient.

Downloading and installing packages into local source directory:

  Setting up CIPD package manager...done (4.3s)
  Setting up Python environment.....[|]============================================================
Unexpected Python version: Python 3.10.4
============================================================
failed (0.1s)
as@machine:~/connectedhomeip$ 
```

I check with the issue [#5455](https://github.com/project-chip/connectedhomeip/issues/5455) but it doesn't helped.

My machine is running `Ubuntu 22.04 LTS x86_64` 

What am I missing?

**Comment by bzbarsky-apple** [comment] 2022-06-16 14:17
@mspang @andy31415

**Comment by cduvenhorst** [comment] 2022-06-21 15:38
> Which means is it only compatible with Python 3.8 and 3.9?

Yes. For a (unsafe) workaround see #16664.

Issue can be closed.

**Comment by cduvenhorst** [comment] 2022-06-25 11:11
[Solution](https://github.com/project-chip/connectedhomeip/issues/16664#issuecomment-1166247616).

**Comment by absoluteabutaj** [comment] 2022-06-25 12:55
@cduvenhorst  - I'll try that out.

**Comment by turon** [comment] 2022-06-29 07:08
Is this a duplicate of #16664?

**Closed** 2022-06-29 19:11 UTC
