### ISSUE TITLE
Test case to Simulate disconnecting and reconnecting to a Thread network on TH fails with : Error 0x0000002F

### ISSUE THREAD

**Issue by phonnakasturi-apple** [project-chip/connectedhomeip#18646] opened 2022-05-20 00:34 UTC
Test case to Simulate disconnecting and reconnecting to a Thread network on TH fails:

**Python command:**
sudo ./chip-tool-darwin  threadnetworkdiagnostics  read-event connection-status 30 0

**Error**
[1653006314770] [95607:996751] CHIP: [TOO] Run command failure: ../../third_party/connectedhomeip/examples/chip-tool/commands/common/Commands.cpp:113: Error 0x0000002F

Attaching the screenshot;

<img width="670" alt="TC-DIAG-TH_NW-3 5-error" src="https://user-images.githubusercontent.com/101904389/169425599-22e299cf-38e3-4324-9e53-79e136171b43.png">

**Comment by bzbarsky-apple** [comment] 2022-05-25 03:31
chip-tool-darwin does not support reading events, because the Darwin framework does not.

**Comment by bzbarsky-apple** [comment] 2022-05-25 03:31
Duplicate of #18185

**Closed by bzbarsky-apple** 2022-05-25 03:31 UTC
