### ISSUE TITLE
[BUG] UnpairDeviceCallback never callback

### ISSUE THREAD

**Issue by VinhBH1** [project-chip/connectedhomeip#33942] opened 2024-06-17 08:54 UTC
### Reproduction steps

Run example in Android CHIP
Connect device
=> unpair device 
in lightbulbs unpair succesful (color light from yellow => white),
 but in log say timeout

### Bug prevalence

alway

### GitHub hash of the SDK that was being used

d83caf7

### Platform

android

### Anything else?

![image](https://github.com/project-chip/connectedhomeip/assets/169765313/d848740a-53a7-4658-9503-f26b2dfb12e7)

**Comment by joonhaengHeo** [comment] 2024-07-11 02:11
@VinhBH1 
I couldn't reproduce your issue. When I tested with Android Chip-tool and Sample App(lighting-app) of Test Harness, onSuccess was called. Can you check the Full Log when the issue occurred?

**Comment by yunhanw-google** [comment] 2024-10-08 03:30
I also cannot reproduce this issue, close it now, please retry with latest app from master, and reopen it with the logs, thanks

**Closed by yunhanw-google** 2024-10-08 03:30 UTC
Labels: bug, android, needs triage
