### ISSUE TITLE
Can I bind 2 endpoints on the same aggregator?

### ISSUE THREAD

**Issue by LongND0105** [project-chip/connectedhomeip#28206] opened 2023-07-24 09:38 UTC
I have a Zigbee to Matter bridge. I create a aggregator device (contains zigbee device). I create 1 on/off light endpoint and 1 light switch endpoint (using macro in order to create dymanic endpoint), now I want to bind the on/off light to the light switch. In theory, can I do that and if so, how do I do it?

**Comment by bzbarsky-apple** [comment] 2023-09-01 16:55
Duplicate of https://github.com/project-chip/connectedhomeip/issues/21626

**Closed by bzbarsky-apple** 2023-09-01 16:55 UTC
Labels: darwin
