### ISSUE TITLE
Attributes and commands of "Ethernet Network Diagnostics" cluster are failing

### ISSUE THREAD

**Issue by ghost** [project-chip/connectedhomeip#13648] opened 2022-01-18 13:57 UTC
Summary: 
               Attributes and commands of Ethernet Network Diagnostics cluster  showing failure response when made a run.
Attributes:
PacketRxCount, PacketTxCount, TxErrCount, CollisionCount, OverrunCount, CarrierDetect, TimeSinceReset 
commands:
ResetCounts

Spec screenshot:
![image](https://user-images.githubusercontent.com/84442963/149950858-68f57507-ed29-476c-b072-c1080bed6599.png)

Execution log and screenshot:
![EthDiag](https://user-images.githubusercontent.com/84442963/149950919-bae4eb97-54f1-460b-96e8-8fbd46ab270a.png)
[ethernet_Diag.txt](https://github.com/project-chip/connectedhomeip/files/7889574/ethernet_Diag.txt)

**Comment by bzbarsky-apple** [comment] 2022-01-19 21:46
@yufengwangca

**Comment by kowsisoundhar12** [comment] 2022-05-06 15:33
Testscript name ---> [TC-ETHDIAG-1.2] Command received functionality with server as DUT

ResetCounts Command is giving failure response ,because of this command following attributes response value is not resetting to "0"

1.PacketRxCount,
2.PacketTxCount
3. TxErrCount
4. CollisionCount
5. OverrunCount attribute
![testplan](https://user-images.githubusercontent.com/57476670/167165137-cc7f01ea-5ffc-4778-aefd-5c6be8f4c64e.png)
![ETHDIAG-2-1](https://user-images.githubusercontent.com/57476670/167165149-75885aa9-d2dd-40b5-961e-12d3cee59abd.png)
[Uploading ETHDIAG-2-1-EXecution-logs.zip…]()

**Comment by naveenkommareddi** [comment] 2022-05-17 01:47
this is a DUP of [18321](https://github.com/project-chip/connectedhomeip/issues/18321)

**Comment by franck-apple** [comment] 2022-05-17 09:50
dupe of #18321. Closing

**Closed by franck-apple** 2022-05-17 09:50 UTC
Labels: V1.0, spec, utility-cluster, cert
