### ISSUE TITLE
[CERT-TEST-FAILURE] - TC-DISHMS-3.2 - Test failed

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/connectedhomeip#27788] opened 2023-07-07 09:41 UTC
### Feature Area

Area:Dishwashers

### Test Case

TC-DISHMS-3.2

### Summary
All-clusters-app has to be enabled with below mentioned attributes :

- [ ]  supported-modes                                                                   
- [ ]  current-mode                                                                      
- [ ]  start-up-mode                                                                     
- [ ]  on-mode       

All-clusters-app has to be enabled with below mentioned commands :

- [ ] ChangeToMode

### Bug prevalence

Everytime

### GitHub hash of the SDK that was being used

d55f68526864b2986404d1da9c2ccd8b64735b6e - master

### Platform

raspi

### Platform Version(s)

RPI4 8GB RAM

**Comment by bzbarsky-apple** [comment] 2023-07-07 15:47
There is no ChangeToMode in Dishwasher Mode cluster, and the rest is a duplicate of https://github.com/project-chip/connectedhomeip/issues/27705

**Closed** 2023-07-25 05:31 UTC
Labels: bug, cert blocker, needs triage, dishwashers
