### ISSUE TITLE
[pre-sve][TC-DRLK-2.8] set invalid user returns success 

### ISSUE THREAD

**Issue by mamayorg** [project-chip/connectedhomeip#19922] opened 2022-06-23 21:24 UTC
**Problem**
Using set-user command with an invalid UserType=10 returns a response of success instead of INVALID_COMMAND

 **Commands**
Commands used
./chip-tool doorlock read number-of-total-users-supported 1 1
./chip-tool doorlock set-user 0 1 xxx 6452 1 0 0 1 1  --timedInteractionTimeoutMs 1000
./chip-tool doorlock get-user 1 1 1
./chip-tool doorlock set-user 0 2 xxx 6451 1 10 3 1 1 --timedInteractionTimeoutMs 1000  (SUCCESS instead of INVALID_COMMAND)

 * expected behavior: return response is INVALID_COMMAND
 * actual behavior:  returns response shows SUCCESS

  **Commit**
Commit id: 1e3f12041013dd71a53d035dbf2f6d142fc06c4e
Platform: EFR32
Network: Thread

 
Reference: #19563

[TC_DRLK_2.8_.txt](https://github.com/project-chip/connectedhomeip/files/8971026/TC_DRLK_2.8_.txt)
[TC_DRLK_2.8_step#4.txt](https://github.com/project-chip/connectedhomeip/files/8971122/TC_DRLK_2.8_step.4.txt)

**Comment by bzbarsky-apple** [comment] 2022-06-23 21:36
Duplicate of #19563

**Closed by bzbarsky-apple** 2022-06-23 21:36 UTC
