### ISSUE TITLE
[crash]

### ISSUE THREAD

**Issue by aajain-com** [project-chip/connectedhomeip#21561] opened 2022-08-02 23:00 UTC
#### Problem
Crash seen with `aa9457e6b94b735076dff6297176183bf9780177 `

```
Thread 10 Crashed:
0   Matter                        	       0x18f055c84 chip::SessionManager::SystemLayer() (in Matter) + 12 (connectedhomeip/src/transport/SessionManager.h:185)
1   Matter                        	       0x18efd03d0 chip::app::ReadClient::CancelLivenessCheckTimer() (in Matter) + 60 (connectedhomeip/src/app/ReadClient.cpp:782)
2   Matter                        	       0x18efd04f8 chip::app::ReadClient::~ReadClient() (in Matter) + 96 (connectedhomeip/src/app/ReadClient.cpp:117)
3   Matter                        	       0x18efd05bc chip::app::ReadClient::~ReadClient() (in Matter) + 32 (connectedhomeip/src/app/ReadClient.cpp:112)
4   Matter                        	       0x18efd05ec chip::app::ReadClient::~ReadClient() (in Matter) + 32 (connectedhomeip/src/app/ReadClient.cpp:112)
5   Matter                        	       0x18ea38e78 (anonymous namespace)::SubscriptionCallback::~SubscriptionCallback() (in Matter) + 124 
6   Matter                        	       0x18ea39bb0 invocation function for block in (anonymous namespace)::SubscriptionCallback::ReportError(NSError*) (in Matter) + 32 (connectedhomeip/src/darwin/Framework/CHIP/MTRBaseDevice.mm:1556)

```

**Comment by bzbarsky-apple** [comment] 2022-08-03 19:32
Duplicate of #20085

**Closed by bzbarsky-apple** 2022-08-03 19:32 UTC
Labels: darwin, V1.0, crash
