### ISSUE TITLE
[Pre-SVE] TC_G-2.1 step 1 incorrect name support value

### ISSUE THREAD

**Issue by HubertHugo** [project-chip/connectedhomeip#19765] opened 2022-06-20 12:20 UTC
SHA: 1e3f12041013dd71a53d035dbf2f6d142fc06c4e
platform: nRF52840
all clusters app
I get:
```
[1655727243.480076][108025:108030] CHIP:TOO: Endpoint: 0 Cluster: 0x0000_0004 Attribute 0x0000_0000 DataVersion: 2368869956
[1655727243.480128][108025:108030] CHIP:TOO:   name support: 128
```
but feature map is 0 so GN should be 0 and because of it name support value should be also 0.

**Comment by sankarselvam** [comment] 2022-06-20 15:14
Looks like duplicate of https://github.com/project-chip/connectedhomeip/issues/19613

**Comment by bzbarsky-apple** [comment] 2022-06-20 16:39
Duplicate of #19613.

**Closed by bzbarsky-apple** 2022-06-20 16:39 UTC
