### ISSUE TITLE
Figure out what to do with ember events

### ISSUE THREAD

**Issue by bzbarsky-apple** [project-chip/connectedhomeip#1941] opened 2020-07-31 19:35 UTC
#### Problem
The initial landing in #1609 commented out a call to `emAfInitEvents` in `emberAfInit`.

 #### Proposed Solution
Figure out whether this call needs to happen and if so what it should do.  If it doesn't need to happen, remove the commented-out bit.

@rwalker-apple @bhaskar-apple @selissia @wehale @tecimovic

**Comment by vivien-apple** [comment] 2020-09-04 13:05
FTR In #2431 @bhaskar-apple has stubbed some commands that seems related to events, namely:
```#define emberEventControlSetDelayMS(control, delay) (void) 0```
```#define emberEventControlSetInactive(control) (void) 0```

**Comment by rwalker-apple** [comment] 2020-09-04 22:25
duplicate of #658

**Closed by rwalker-apple** 2020-09-04 22:25 UTC
Labels: bug
