### ISSUE TITLE
Add IM event Yaml and Chip tool testing

### ISSUE THREAD

**Issue by yunhanw-google** [project-chip/connectedhomeip#12460] opened 2021-12-02 07:40 UTC
#### Problem
pending PR for #12059, no example integration for IM eventing so far. Once it is ready, it is good to test with TestCluster where we can use command to instruct server to generate event, then call readEvent to retrieve events, for other real cluster, like diagnostic cluster or basic application cluster, their event generation is related to platform, which is a little hard to achieve in yaml automation test.

**Comment by vivien-apple** [comment] 2022-01-27 20:29
Duplicate of #11343

**Closed by vivien-apple** 2022-01-27 20:29 UTC
Labels: V1.0, Interaction Model Work, Test Harness, cert, sdk requirements from test harness
