### ISSUE TITLE
Java JNI library has been broken for a week

### ISSUE THREAD

**Issue by jonsmirl** [project-chip/connectedhomeip#21554] opened 2022-08-02 18:50 UTC
This can easily be demonstrated by trying to use Android chip-tool. Android chip-tool won't function because the library it relies on is non-functioning.

Could tests be added to ensure that the Java JNI library is at least capable of commissioning a node?

Here's a fix for the first bug, but after you fix this one it cascades into more problems......

```
diff --git a/src/controller/java/CHIPDeviceController-JNI.cpp b/src/controller/java/CHIPDeviceController-JNI.cpp
index 3e8db12d8..8b3523634 100644
--- a/src/controller/java/CHIPDeviceController-JNI.cpp
+++ b/src/controller/java/CHIPDeviceController-JNI.cpp
@@ -220,8 +220,8 @@ JNI_METHOD(jlong, newDeviceController)(JNIEnv * env, jobject self, jobject contr
         jbyteArray operationalCertificate  = (jbyteArray) env->CallObjectMethod(controllerParams, getOperationalCertificate);
         jbyteArray ipk                     = (jbyteArray) env->CallObjectMethod(controllerParams, getIpk);
         uint16_t failsafeTimerSeconds      = env->CallIntMethod(controllerParams, getFailsafeTimerSeconds);
-        bool attemptNetworkScanWiFi        = env->CallIntMethod(controllerParams, getAttemptNetworkScanWiFi);
-        bool attemptNetworkScanThread      = env->CallIntMethod(controllerParams, getAttemptNetworkScanThread);
+        bool attemptNetworkScanWiFi        = env->CallBooleanMethod(controllerParams, getAttemptNetworkScanWiFi);
+        bool attemptNetworkScanThread      = env->CallBooleanMethod(controllerParams, getAttemptNetworkScanThread);
 
         std::unique_ptr<chip::Controller::AndroidOperationalCredentialsIssuer> opCredsIssuer(
             new chip::Controller::AndroidOperationalCredentialsIssuer());
```

**Comment by robertfarnum** [comment] 2022-08-03 12:28
This is a duplicate of https://github.com/project-chip/connectedhomeip/issues/21493 being worked on by @chrisdecenzo

**Comment by andy31415** [comment] 2022-09-15 20:40
Duplicate has been fixed.

**Closed by andy31415** 2022-09-15 20:40 UTC
Labels: android
