### ISSUE TITLE
Missing level control cluster implementation

### ISSUE THREAD

**Issue by bhaskar-apple** [project-chip/connectedhomeip#1307] opened 2020-06-26 18:42 UTC
#### Problem
Missing level control cluster implementation

 #### Proposed Solution
Add it to `Add Silicon Labs ZCL framework files #1164`

**Comment by woody-apple** [comment] 2020-08-13 22:22
Marking as a duplicate of:
https://github.com/project-chip/connectedhomeip/issues/2060

**Closed by woody-apple** 2020-08-13 22:22 UTC
Labels: bug, enhancement
