### ISSUE TITLE
Change Endpoints to INT16U array once it is supported 

### ISSUE THREAD

**Issue by woody-apple** [project-chip/connectedhomeip#14646] opened 2022-02-01 14:47 UTC
https://github.com/project-chip/connectedhomeip/blob/bebbd74187a721154f82061f1023a347d7ce7f57/src/app/zap-templates/zcl/data-model/chip/bridged-actions-cluster.xml#L83-L88

---

###### This issue was generated by [todo-issue](https://github.com/DerJuulsn/todo-issue) based on a `TODO` comment in bebbd74187a721154f82061f1023a347d7ce7f57.

**Comment by bzbarsky-apple** [comment] 2022-05-05 20:00
Duplicate of #14074

**Closed by bzbarsky-apple** 2022-05-05 20:00 UTC
Labels: V1.0, spec, todo :spiral_notepad:
