### ISSUE TITLE
[crash] Matter:  chip::SessionManager::SystemLayer

### ISSUE THREAD

**Issue by aajain-com** [project-chip/connectedhomeip#21770] opened 2022-08-09 20:58 UTC
#### Problem
Crash with `aa9457e6b94b735076dff6297176183bf9780177 ` SHA.

```
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Codes: 0x0000000000000001, 0x0000000000000018
VM Region Info: 0x18 is not in any region.  Bytes before following region: 68719476712
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      commpage (reserved)     1000000000-7000000000 [384.0G] ---/--- SM=NUL  ...(unallocated)
Termination Reason: SIGNAL 11 Segmentation fault: 11
Terminating Process: exc handler [1054]
```

```
Thread 7 Crashed ↩::   Dispatch queue: com.csa.matter.framework.controller.workqueue
0   Matter                        	       0x10426a9b4 chip::SessionManager::SystemLayer() + 12 (connectedhomeip/src/transport/SessionManager.h:185)
1   Matter                        	       0x1041e52f0 chip::app::ReadClient::CancelLivenessCheckTimer() + 60 (connectedhomeip/src/app/ReadClient.cpp:735)
2   Matter                        	       0x1041e5410 chip::app::ReadClient::~ReadClient() + 88 (connectedhomeip/src/app/ReadClient.cpp:116)
3   Matter                        	       0x1041e5484 chip::app::ReadClient::~ReadClient() + 32 (connectedhomeip/src/app/ReadClient.cpp:113)
4   Matter                        	       0x1041e54b4 chip::app::ReadClient::~ReadClient() + 32 (connectedhomeip/src/app/ReadClient.cpp:113)
5   Matter                        	       0x103c4fbbc (anonymous namespace)::SubscriptionCallback::~SubscriptionCallback() + 124 (usr/include/c++/v1/__memory/unique_ptr.h:57)
6   Matter                        	       0x103c508b8 ___ZN12_GLOBAL__N_120SubscriptionCallback11ReportErrorEP7NSError_block_invoke_2 + 32 (connectedhomeip/src/darwin/Framework/CHIP/MTRBaseDevice.mm:1556)
```

```
2022-08-08 09:40:33.0642 -0700 default 0x02986 0x0 homed[1054] (Matter): 🔵 [1659976833077] [1054:10630] CHIP: [DIS] Keeping DNSSD lookup active
2022-08-08 09:40:33.0988 -0700 default 0x02a1f 0x0 homed[1054] (Matter): 🟢 [1659976833112] [1054:10783] CHIP: [EM] Retransmitting MessageCounter:195541916 on exchange 49365i Send Cnt 1
2022-08-08 09:40:33.0988 -0700 default 0x02a1f 0x0 homed[1054] (Matter): 🔵 [1659976833112] [1054:10783] CHIP: [IN] Sending encrypted msg 0x10d722f38 with MessageCounter:195541916 to 0x000000001BF74625 (11) at monotonic time: 000000000009E7FF msec
2022-08-08 09:40:33.0990 -0700 default 0x02a1f 0x0 homed[1054] (Matter): 🔵 [1659976833112] [1054:10783] CHIP: [DIS] OperationalDeviceProxy[11:000000001BF74625]: Operational node lookup already in progress. Will NOT start a new one.
2022-08-08 09:40:33.1875 -0700 default 0x02986 0x0 homed[1054] (Matter): 🔵 [1659976833200] [1054:10630] CHIP: [EM] Received message of type 0x5 with protocolId (0, 1) and MessageCounter:161769145 on exchange 49364i
2022-08-08 09:40:33.1875 -0700 default 0x02986 0x0 homed[1054] (Matter): 🟢 [1659976833200] [1054:10630] CHIP: [EM] Found matching exchange: 49364i, Delegate: 0x10d35d4a0
2022-08-08 09:40:33.1876 -0700 default 0x02986 0x0 homed[1054] (Matter): 🟢 [1659976833201] [1054:10630] CHIP: [EM] Rxd Ack; Removing MessageCounter:195541915 from Retrans Table on exchange 49364i
2022-08-08 09:40:33.1876 -0700 default 0x02986 0x0 homed[1054] (Matter): 🟢 [1659976833201] [1054:10630] CHIP: [EM] Removed CHIP MessageCounter:195541915 from RetransTable on exchange 49364i
2022-08-08 09:40:33.1884 -0700 default 0x02986 0x0 homed[1054] (Matter): 🟢 [1659976833201] [1054:10630] CHIP: [EM] Sending Standalone Ack for MessageCounter:161769145 on exchange 49364i
2022-08-08 09:40:33.1884 -0700 default 0x02a21 0x0 homed[1054] (Matter): 🟢 [1659976833201] [1054:10785] CHIP: [CTL] Response Time: PFvPvRKN4chip3app9DataModel13DecodableListItEEE+316489810 0.443746 seconds
2022-08-08 09:40:33.1885 -0700 default 0x02986 0x0 homed[1054] (Matter): 🔵 [1659976833201] [1054:10630] CHIP: [IN] Prepared secure message 0x16f5ad258 to 0x000000001BF74625 (11)  of type 0x10 and protocolId (0, 0) on exchange 49364i with MessageCounter:195541918.
2022-08-08 09:40:33.1885 -0700 default 0x02986 0x0 homed[1054] (Matter): 🔵 [1659976833201] [1054:10630] CHIP: [IN] Sending encrypted msg 0x16f5ad258 with MessageCounter:195541918 to 0x000000001BF74625 (11) at monotonic time: 000000000009E858 msec
2022-08-08 09:40:33.1886 -0700 default 0x02986 0x0 homed[1054] (Matter): 🟢 [1659976833202] [1054:10630] CHIP: [EM] Flushed pending ack for MessageCounter:161769145 on exchange 49364i
2022-08-08 09:40:33.1890 -0700 default 0x02a21 0x0 homed[1054] (Matter): 🟢 [1659976833202] [1054:10785] CHIP: [CTL] Response Time: PFvPvRKN4chip3app9DataModel13DecodableListIjEEE+3861994162
2022-08-08 09:40:33.1890 -0700 default 0x02a21 0x0 homed[1054] (Matter): 🟢 [1659976833202] [1054:10785] CHIP: [DMG] SendReadRequest ReadClient[0x10db43b70]: Sending Read Request
2022-08-08 09:40:33.1892 -0700 default 0x02a21 0x0 homed[1054] (Matter): 🔵 [1659976833202] [1054:10785] CHIP: [IN] Prepared secure message 0x104c3cf58 to 0x000000001BF74625 (11)  of type 0x2 and protocolId (0, 1) on exchange 49367i with MessageCounter:195541919.
2022-08-08 09:40:33.1892 -0700 default 0x02a21 0x0 homed[1054] (Matter): 🔵 [1659976833202] [1054:10785] CHIP: [IN] Sending encrypted msg 0x104c3cf58 with MessageCounter:195541919 to 0x000000001BF74625 (11) at monotonic time: 000000000009E859 msec
2022-08-08 09:40:33.1894 -0700 default 0x02a21 0x0 homed[1054] (Matter): 🟢 [1659976833202] [1054:10785] CHIP: [DMG] MoveToState ReadClient[0x10db43b70]: Moving to [AwaitingIn]
2022-08-08 09:40:33.2540 -0700 default 0x02a1f 0x0 homed[1054] (Matter): 🔵 [1659976833267] [1054:10783] CHIP: [DIS] Checking node lookup status after 203 ms
2022-08-08 09:40:33.2540 -0700 default 0x02a1f 0x0 homed[1054] (Matter): 🟢 [1659976833267] [1054:10783] CHIP: [DIS] OperationalDeviceProxy[11:000000001BF74625]: Updating device address to UDP:[fdba:6cf7:2b86:0:ad33:bcb3:8586:e0ab]:5540 while in state 5
2022-08-08 09:40:33.3238 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [CTL] Shutting down the commissioner
2022-08-08 09:40:33.3238 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [CTL] Stopping commissioning discovery over DNS-SD
2022-08-08 09:40:33.3238 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [CTL] Shutting down the controller
2022-08-08 09:40:33.3238 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [IN] SecureSession[0x1030b7910]: Released - Type:2 LSID:99
2022-08-08 09:40:33.3239 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [IN] Expiring all sessions for fabric 0xb!!
2022-08-08 09:40:33.3239 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [IN] SecureSession[0x10d357d10]: MarkForEviction Type:2 LSID:100
2022-08-08 09:40:33.3239 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🔵 [1659976833337] [1054:10783] CHIP: [SC] SecureSession[0x10d357d10]: Moving from state 'kActive' --> 'kPendingEviction'
2022-08-08 09:40:33.3239 -0700   error 0x02a1f 0x9381 homed[1054] (Matter): 🔴 [1659976833337] [1054:10783] CHIP: [DMG] Time out! failed to receive report data from Exchange: 49365i
2022-08-08 09:40:33.3239 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [DMG] mResubscribePolicy is null
2022-08-08 09:40:33.3240 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [DMG] MoveToState ReadClient[0x10d70eb10]: Moving to [      Idle]
2022-08-08 09:40:33.3240 -0700   error 0x02a1f 0x9381 homed[1054] (Matter): 🔴 [1659976833337] [1054:10783] CHIP: [DMG] Time out! failed to receive report data from Exchange: 49366i
2022-08-08 09:40:33.3241 -0700   error 0x02a1f 0x9381 homed[1054] (Matter): 🔴 [1659976833337] [1054:10783] CHIP: [DMG] Time out! failed to receive report data from Exchange: 49367i
2022-08-08 09:40:33.3241 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833337] [1054:10783] CHIP: [IN] SecureSession[0x10d357d10]: Released - Type:2 LSID:100
2022-08-08 09:40:33.3241 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🔵 [1659976833337] [1054:10783] CHIP: [FP] Forgetting fabric 0xb
2022-08-08 09:40:33.3241 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🔵 [1659976833337] [1054:10783] CHIP: [TS] Pending Last Known Good Time: 2022-08-08T16:22:51
2022-08-08 09:40:33.3246 -0700 default 0x02a22 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10786] CHIP: [CTL] Response Time: PFvPvN4chip4SpanIKcEEE+3672595051 0.573910 seconds
2022-08-08 09:40:33.3249 -0700 default 0x02a22 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10786] CHIP: [CTL] Response Time: PFvPvRKN4chip3app9DataModel13DecodableListIjEEE+3861994162 0.136018 seconds
2022-08-08 09:40:33.3252 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): PersistentStorageDelegate Sync Get Value for Key: g/lkgt
2022-08-08 09:40:33.3253 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🔵 [1659976833338] [1054:10783] CHIP: [TS] Previous Last Known Good Time: 2022-08-08T16:22:51
2022-08-08 09:40:33.3253 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🔵 [1659976833338] [1054:10783] CHIP: [TS] Reverted Last Known Good Time to previous value
2022-08-08 09:40:33.3253 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10783] CHIP: [CTL] Shutting down the System State, this will teardown the CHIP Stack
2022-08-08 09:40:33.3253 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10783] CHIP: [IN] SecureSession[0x10db33f10]: Released - Type:2 LSID:98
2022-08-08 09:40:33.3254 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10783] CHIP: [DMG] IM WH moving to [Uninitialized]
2022-08-08 09:40:33.3254 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10783] CHIP: [DMG] IM WH moving to [Uninitialized]
2022-08-08 09:40:33.3254 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10783] CHIP: [DMG] IM WH moving to [Uninitialized]
2022-08-08 09:40:33.3254 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10783] CHIP: [DMG] IM WH moving to [Uninitialized]
2022-08-08 09:40:33.3254 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🟢 [1659976833338] [1054:10783] CHIP: [DMG] All ReadHandler-s are clean, clear GlobalDirtySet
2022-08-08 09:40:33.3255 -0700 default 0x02a1f 0x9381 homed[1054] (Matter): 🔵 [1659976833338] [1054:10783] CHIP: [BLE] CancelConnection
2022-08-08 09:40:33.3255 -0700   error 0x02a1f 0x9381 homed[1054] (Matter): 🔴 [1659976833338] [1054:10783] CHIP: [DL] Inet Layer shutdown
2022-08-08 09:40:33.3255 -0700   error 0x02a1f 0x9381 homed[1054] (Matter): 🔴 [1659976833338] [1054:10783] CHIP: [DL] BLE shutdown
2022-08-08 09:40:33.3255 -0700   error 0x02a1f 0x9381 homed[1054] (Matter): 🔴 [1659976833338] [1054:10783] CHIP: [DL] System Layer shutdown
```

Apple reference: rdar://97466186

**Comment by bzbarsky-apple** [comment] 2022-08-09 21:04
Duplicate of https://github.com/project-chip/connectedhomeip/issues/20085

**Closed by bzbarsky-apple** 2022-08-09 21:04 UTC
Labels: darwin, crash
