### ISSUE TITLE
[TC-DD-3.17] - DUT should terminate the commissioning process when we pass invalid Code, but DUT successfully completed the commissioning process

### ISSUE THREAD

**Issue by sowmyassp** [project-chip/connectedhomeip#18679] opened 2022-05-20 16:24 UTC
**Issue** : According to test-plan of [TC-DD-3.1] In Step 6b and 7b  its mentioned DUT should terminate the commissioning process when we pass invalid code mentioned in step 6a and 7a but DUT successfully completed the commissioning process.

**Expected behaviour** : DUT should terminate the commissioning mode when invalid QR code is passed

**Actual behaviour** : DUT successfully completed the commissioning process.

**Steps to reproduce :**

- DUT side :
1. sudo rm -rf /tmp/chip_*
2. sudo ./chip-all-clusters-app --wifi 

- TH side : 
1. ./chip-tool pairing code 1 749701123365521327694

**Test platform :**
Chip-tool - RPI/MAC
DUT - RPI

**Test-plan reference :**
https://github.com/CHIP-Specifications/chip-test-plans/blob/master/src/devicediscovery.adoc#tc-dd-3-17-commissioning-flow-21-digit-manual-pairing-code-negative-scenario-dut-commissioner

**PFA Logs:**
[DD-3.17_cntrl.txt](https://github.com/project-chip/connectedhomeip/files/8741922/DD-3.17_cntrl.txt)

**Comment by bzbarsky-apple** [comment] 2022-05-25 03:28
Duplicate of #17205

**Closed by bzbarsky-apple** 2022-05-25 03:28 UTC
