### ISSUE TITLE
FeatureMap returns 0x86 (UNSUPPORTED_ATTRIBUTE) in multiple clusters

### ISSUE THREAD

**Issue by yinyihu-silabs** [project-chip/connectedhomeip#18175] opened 2022-05-06 20:59 UTC
pi@raspi-04:~$ ./chip-tool groups read feature-map 1 0 | grep "FeatureMap\|Response Failure"
[1651870433.336697][2511:2517] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

pi@raspi-04:~$ ./chip-tool basic read feature-map 1 0 | grep "FeatureMap\|Response Failure"
[1651870434.051563][2519:2525] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

pi@raspi-04:~$ ./chip-tool descriptor read feature-map 1 0 | grep "FeatureMap\|Response Failure"
[1651870434.751341][2526:2532] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

pi@raspi-04:~$ ./chip-tool identify read feature-map 1 1 | grep "FeatureMap\|Response Failure"
[1651870435.471654][2533:2539] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

pi@raspi-04:~$ ./chip-tool occupancysensing read feature-map 1 1  | grep "FeatureMap\|Response Failure"
[1651870436.181973][2540:2546] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

pi@raspi-04:~$ ./chip-tool operationalcredentials read feature-map 1 0 | grep "FeatureMap\|Response Failure"
[1651870436.901278][2547:2553] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

pi@raspi-04:~$ ./chip-tool generaldiagnostics read feature-map 1 0  | grep "FeatureMap\|Response Failure"
[1651870437.616499][2554:2560] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

pi@raspi-04:~$ ./chip-tool accesscontrol read feature-map 1 0  | grep "FeatureMap\|Response Failure"
[1651870438.336334][2561:2567] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

pi@raspi-04:~$ ./chip-tool userlabel read feature-map 1 0 | grep "FeatureMap\|Response Failure"
[1651870439.041564][2568:2574] CHIP:TOO: Response Failure: IM Error 0x00000586: General error: 0x86 (UNSUPPORTED_ATTRIBUTE)

**Comment by bzbarsky-apple** [comment] 2022-05-09 15:59
Duplicate of #16725.

**Closed by bzbarsky-apple** 2022-05-09 15:59 UTC
