### ISSUE TITLE
esp32 example failed to resolve component

### ISSUE THREAD

**Issue by XingpingGY** [project-chip/connectedhomeip#15588] opened 2022-02-25 15:21 UTC
#### Problem
<failed to resolve component:
 * I just tried to build the formal examples in examples/all-clusters-app/esp32 project on ESP-IDF 4.4 CMD
 *
 * Below is the error
 * '''
 CMake Error at C:/Users/911/tools/Espressif/frameworks/esp-idf-v4.4/tools/cmake/build.cmake:200 (message):
  Failed to resolve component 'tft'.
Call Stack (most recent call first):
  C:/Users/911/tools/Espressif/frameworks/esp-idf-v4.4/tools/cmake/build.cmake:231 (__build_resolve_and_add_req)
  C:/Users/911/tools/Espressif/frameworks/esp-idf-v4.4/tools/cmake/build.cmake:512 (__build_expand_requirements)
  C:/Users/911/tools/Espressif/frameworks/esp-idf-v4.4/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:34 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Users/911/connectedhomeip/examples/all-clusters-app/esp32/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1

-- Configuring incomplete, errors occurred!
See also "C:/Users/911/connectedhomeip/examples/all-clusters-app/esp32/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1
'''
 * steps to reproduce
 * system configuration
 * screenshots, images, logs, etc.
 >

**Comment by dhrishi** [comment] 2022-02-25 18:28
@XingpingGY Can you confirm if you have updated the chip submodules using `git submodule update --init --recursive`? As component tft is at `examples/common/m5stack-tft/repo/components/tft/` which is a part of `m5stack-tft/repo` submodule.

**Comment by XingpingGY** [comment] 2022-02-26 16:14
Thank you for your comments. I will check it carefully.

**Comment by dhrishi** [comment] 2022-03-03 11:17
@XingpingGY Please confirm if this works fine now and close the issue if it does.

**Comment by dhrishi** [comment] 2022-03-08 19:05
Closing due to inactivity. Feel free to re-open

**Closed by dhrishi** 2022-03-08 19:05 UTC

**Comment by aaaaa654** [comment] 2023-03-11 09:02
> @XingpingGY Can you confirm if you have updated the chip submodules using `git submodule update --init --recursive`? As component tft is at `examples/common/m5stack-tft/repo/components/tft/` which is a part of `m5stack-tft/repo` submodule.

Hey , i am having the same issue, i tried running the above command in the main 'connectedhomeip' directory and it installed a bunch of things but the issue is still there? What else should i try?

**Comment by oidebrett** [comment] 2023-05-05 08:20
> > @XingpingGY Can you confirm if you have updated the chip submodules using `git submodule update --init --recursive`? As component tft is at `examples/common/m5stack-tft/repo/components/tft/` which is a part of `m5stack-tft/repo` submodule.
> 
> Hey , i am having the same issue, i tried running the above command in the main 'connectedhomeip' directory and it installed a bunch of things but the issue is still there? What else should i try?

I had the same problem and after some investigation I think that the m5stack-tft repo submodules are not being brought in. Even when you try `git submodule update --init --recursive`

My solution was to run this command at the connectedhomeip root folder.
./scripts/checkout_submodules.py --recursive --force --platform esp32
